#!/usr/bin/env python3
"""Export the first real TFLite MAX_POOL_2D tensor for GestureFlow-NPU.

This is project-local validation data.  It proves the pool result from the
actual INT8 TFLite interpreter before RTL is allowed to fuse pool and DDR
writeback.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


def fnv1a32(array: np.ndarray) -> int:
    value = 0x811C9DC5
    for byte in np.ascontiguousarray(array).view(np.uint8).reshape(-1):
        value = ((value ^ int(byte)) * 0x01000193) & 0xFFFFFFFF
    return value


def c_array(values: np.ndarray, name: str, columns: int = 16) -> str:
    flat = values.reshape(-1).tolist()
    lines = [
        "    " + ", ".join(str(int(value)) for value in flat[index:index + columns])
        for index in range(0, len(flat), columns)
    ]
    return "static const int8_t %s[%d] = {\n%s\n};\n" % (name, len(flat), ",\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", required=True, type=Path)
    parser.add_argument("--c-out", required=True, type=Path)
    parser.add_argument("--svh-out", required=True, type=Path)
    args = parser.parse_args()

    from tflite_runtime.interpreter import Interpreter  # pylint: disable=import-outside-toplevel

    # Keep the pool input tensor alive after invoke. Without this option the
    # TFLite arena may reuse conv output storage for later operators, making a
    # post-invoke software reference silently compare unrelated bytes.
    interpreter = Interpreter(
        model_path=str(args.model.resolve()), experimental_preserve_all_tensors=True
    )
    interpreter.allocate_tensors()
    details = {item["index"]: item for item in interpreter.get_tensor_details()}
    pool_ops = [op for op in interpreter._get_ops_details() if op["op_name"] == "MAX_POOL_2D"]  # pylint: disable=protected-access
    if not pool_ops:
        raise SystemExit("Model has no MAX_POOL_2D operator")
    pool = pool_ops[0]
    source_detail = details[int(pool["inputs"][0])]
    output_detail = details[int(pool["outputs"][0])]
    source_shape = tuple(int(value) for value in source_detail["shape"])
    output_shape = tuple(int(value) for value in output_detail["shape"])
    if source_shape != (1, 96, 96, 16) or output_shape != (1, 48, 48, 16):
        raise SystemExit("Unexpected first MAX_POOL_2D shape %s -> %s" % (source_shape, output_shape))
    if source_detail["dtype"] != np.int8 or output_detail["dtype"] != np.int8:
        raise SystemExit("Expected INT8 pool tensors")
    if source_detail["quantization"] != output_detail["quantization"]:
        raise SystemExit("MAX_POOL_2D quantization changes; fusion needs requant support")

    y, x, channel = np.indices((96, 96, 3))
    camera_rgb = ((y * 17 + x * 5 + channel * 29 + 37) & 0xFF).astype(np.uint8)
    interpreter.set_tensor(interpreter.get_input_details()[0]["index"], (camera_rgb.astype(np.int16) - 128).astype(np.int8)[np.newaxis, ...])
    interpreter.invoke()
    source = np.asarray(interpreter.get_tensor(source_detail["index"]), dtype=np.int8)[0]
    pooled = np.asarray(interpreter.get_tensor(output_detail["index"]), dtype=np.int8)[0]
    reference = source.reshape(48, 2, 48, 2, 16).max(axis=(1, 3))
    if not np.array_equal(reference, pooled):
        mismatch = np.argwhere(reference != pooled)[0]
        raise SystemExit("MAX_POOL_2D mismatch at %s" % mismatch.tolist())

    probes = np.asarray([(0, 0), (0, 47), (1, 1), (24, 24), (47, 0), (47, 47)], dtype=np.uint16)
    probe_values = np.asarray([pooled[row, col] for row, col in probes], dtype=np.int8)
    args.c_out.parent.mkdir(parents=True, exist_ok=True)
    args.svh_out.parent.mkdir(parents=True, exist_ok=True)
    c_text = """/* PROJECT_LOCAL_SELF_RESEARCH_NOT_GOOGLE_OFFICIAL */
/* Generated by export_real_maxpool2d.py. Do not hand edit. */
#ifndef GESTUREFLOW_REAL_MAXPOOL2D_H
#define GESTUREFLOW_REAL_MAXPOOL2D_H
#include <stdint.h>
#define GF_POOL_INPUT_WIDTH 96U
#define GF_POOL_INPUT_HEIGHT 96U
#define GF_POOL_OUTPUT_WIDTH 48U
#define GF_POOL_OUTPUT_HEIGHT 48U
#define GF_POOL_CHANNELS 16U
#define GF_POOL_OUTPUT_BYTES 36864U
#define GF_POOL_OUTPUT_FNV1A 0x%08XU
%s
#endif
""" % (fnv1a32(pooled), c_array(pooled, "gf_pool_output"))
    args.c_out.write_text(c_text, encoding="ascii")

    signed = lambda value: "-8'sd%d" % -int(value) if value < 0 else "8'sd%d" % int(value)
    flat = pooled.reshape(-1)
    svh_text = """// PROJECT_LOCAL_SELF_RESEARCH_NOT_GOOGLE_OFFICIAL
// Generated by export_real_maxpool2d.py. Do not hand edit.
localparam int GF_POOL_WIDTH = 48;
localparam int GF_POOL_HEIGHT = 48;
localparam int GF_POOL_LANES = 16;
localparam logic [31:0] GF_POOL_FNV1A = 32'h%08X;
localparam logic signed [7:0] gf_pool_output_q [0:%d] = '{
  %s
};
""" % (fnv1a32(pooled), len(flat) - 1, ", ".join(signed(value) for value in flat))
    args.svh_out.write_text(svh_text, encoding="ascii")
    print("MAXPOOL_EXPORT_PASS input_fnv1a=0x%08X output_fnv1a=0x%08X bytes=%d" % (fnv1a32(source), fnv1a32(pooled), pooled.nbytes))
    print("input_quant=%s output_quant=%s probes=%s" % (source_detail["quantization"], output_detail["quantization"], probes.tolist()))


if __name__ == "__main__":
    main()
