#!/usr/bin/env python3
"""Export a DMP pointwise full-layer golden for the HaGRID-18 1x1 head tile.

The deployed head is 48->64.  The board runs it as two 32-output tiles, so
this tool emits one tile by slicing the real TFLite weights.  It produces the
same self-contained SVH contract as export_dmp_conv_golden.py.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from export_dmp_conv_golden import fnv1a32, sv_signed8, sv_signed32, sv_uint32
from export_dmp_conv_layer import fold_dmp_bias, pack_dmp_weights


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", required=True, type=Path)
    parser.add_argument("--conv-index", type=int, default=6)
    parser.add_argument("--first-oc", type=int, default=0)
    parser.add_argument("--tile-oc", type=int, default=32)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--svh-out", required=True, type=Path)
    args = parser.parse_args()

    from tflite_runtime.interpreter import Interpreter  # pylint: disable=import-outside-toplevel

    interpreter = Interpreter(
        model_path=str(args.model.resolve()), experimental_preserve_all_tensors=True
    )
    interpreter.allocate_tensors()
    model_input_detail = interpreter.get_input_details()[0]
    ops = interpreter._get_ops_details()  # pylint: disable=protected-access
    convs = [item for item in ops if item["op_name"] == "CONV_2D"]
    conv = convs[args.conv_index]
    details = {item["index"]: item for item in interpreter.get_tensor_details()}
    input_detail = details[int(conv["inputs"][0])]
    weights_all = np.asarray(interpreter.get_tensor(conv["inputs"][1]), dtype=np.int8)
    bias_all = np.asarray(interpreter.get_tensor(conv["inputs"][2]), dtype=np.int32)
    if tuple(weights_all.shape[1:3]) != (1, 1):
        raise SystemExit("Expected a 1x1 CONV_2D layer")
    real_input_channels = weights_all.shape[3]
    if real_input_channels % 8:
        raise SystemExit("Pointwise golden requires input channels divisible by 8")
    input_zp = int(input_detail["quantization"][1])
    weights = weights_all[args.first_oc : args.first_oc + args.tile_oc]
    bias = bias_all[args.first_oc : args.first_oc + args.tile_oc]
    output_lanes = weights.shape[0]
    padded_channels = real_input_channels
    padded = np.zeros((output_lanes, 1, padded_channels), dtype=np.int8)
    padded[:, 0, :] = weights[:, 0, 0, :]

    y, x, channel = np.indices((96, 96, 3))
    camera_rgb = ((y * 17 + x * 5 + channel * 29 + 37) & 0xFF).astype(np.uint8)
    q_input = (camera_rgb.astype(np.int16) - 128).astype(np.int8)
    interpreter.set_tensor(model_input_detail["index"], q_input[np.newaxis, ...])
    interpreter.invoke()
    layer_input = np.asarray(interpreter.get_tensor(input_detail["index"]), dtype=np.int8)[0]
    image_height, image_width, _ = layer_input.shape

    raw = np.broadcast_to(bias.astype(np.int64), (image_height, image_width, output_lanes)).copy()
    raw += np.tensordot(
        layer_input.astype(np.int64) - input_zp,
        weights[:, 0, 0, :].astype(np.int64),
        axes=([2], [1]),
    )
    if raw.min() < np.iinfo(np.int32).min or raw.max() > np.iinfo(np.int32).max:
        raise SystemExit("pointwise raw accumulator exceeds INT32")

    packed = pack_dmp_weights(padded)
    folded_bias = fold_dmp_bias(padded, bias, input_zp, 1, real_input_channels)
    word_count = packed.size

    probes = np.asarray(
        [(0, 0), (0, image_width - 1), (image_height // 2, image_width // 2),
         (image_height - 1, 0), (image_height - 1, image_width - 1)],
        dtype=np.uint16,
    )
    probe_raw = np.asarray([raw[row, column] for row, column in probes], dtype=np.int32)
    raw_fnv = fnv1a32(raw.astype("<i4"))
    tag_upper = args.tag.upper()

    def array_text(values: np.ndarray, formatter, columns: int = 12) -> str:
        flat = values.reshape(-1).tolist()
        rows = [
            "  " + ", ".join(formatter(int(item)) for item in flat[index : index + columns])
            for index in range(0, len(flat), columns)
        ]
        return ",\n".join(rows)

    text = f"""// PROJECT_LOCAL_SELF_RESEARCH_NOT_GOOGLE_OFFICIAL
// Generated by export_dmp_pointwise_golden.py. Do not hand edit.
localparam int GF_DMP_{tag_upper}_WIDTH = {image_width};
localparam int GF_DMP_{tag_upper}_HEIGHT = {image_height};
localparam int GF_DMP_{tag_upper}_INPUT_CHANNELS = {padded_channels};
localparam int GF_DMP_{tag_upper}_INPUT_GROUPS = {padded_channels // 8};
localparam int GF_DMP_{tag_upper}_OUTPUT_LANES = {output_lanes};
localparam int GF_DMP_{tag_upper}_ACTIVE_TAPS = 1;
localparam int GF_DMP_{tag_upper}_INPUT_ZERO_POINT = {input_zp};
localparam int GF_DMP_{tag_upper}_WEIGHT_DMA_WORDS = {word_count};
localparam int GF_DMP_{tag_upper}_PROBE_COUNT = {len(probes)};
localparam logic [31:0] GF_DMP_{tag_upper}_RAW_FNV1A = 32'h{raw_fnv:08X};
"""
    text += (
        f"localparam logic signed [7:0] gf_dmp_{args.tag}_input_q [0:{image_height*image_width*padded_channels-1}] = '{{\n"
        + array_text(layer_input, sv_signed8)
        + "\n};\n"
    )
    text += (
        f"localparam logic [31:0] gf_dmp_{args.tag}_weights_dma [0:{word_count-1}] = '{{\n"
        + array_text(packed, sv_uint32)
        + "\n};\n"
    )
    text += (
        f"localparam logic signed [31:0] gf_dmp_{args.tag}_folded_bias [0:{output_lanes-1}] = '{{\n"
        + array_text(folded_bias, sv_signed32)
        + "\n};\n"
    )
    text += (
        f"localparam logic [15:0] gf_dmp_{args.tag}_probe_y [0:{len(probes)-1}] = '{{\n  "
        + ", ".join(f"16'd{int(row)}" for row, _ in probes)
        + "\n};\n"
    )
    text += (
        f"localparam logic [15:0] gf_dmp_{args.tag}_probe_x [0:{len(probes)-1}] = '{{\n  "
        + ", ".join(f"16'd{int(column)}" for _, column in probes)
        + "\n};\n"
    )
    text += (
        f"localparam logic signed [31:0] gf_dmp_{args.tag}_probe_raw "
        f"[0:{len(probes)-1}][0:{output_lanes-1}] = '{{\n"
    )
    text += ",\n".join(
        "  '{" + ", ".join(sv_signed32(int(value)) for value in vector) + "}"
        for vector in probe_raw
    )
    text += "\n};\n"

    args.svh_out.parent.mkdir(parents=True, exist_ok=True)
    args.svh_out.write_text(text, encoding="ascii")
    print(f"Wrote {args.svh_out.resolve()}")
    print(
        "DMP pointwise golden PASS "
        f"first_oc={args.first_oc} oc={output_lanes} cin={padded_channels} "
        f"words={word_count} raw_fnv=0x{raw_fnv:08X}"
    )


if __name__ == "__main__":
    main()
