// PROJECT_LOCAL_SELF_RESEARCH_NOT_GOOGLE_OFFICIAL
// Generated by export_dmp_conv_layer.py. Do not hand edit.
localparam int GF_DMP_FULL_REAL_INPUT_CHANNELS = 3;
localparam int GF_DMP_FULL_PADDED_INPUT_CHANNELS = 8;
localparam int GF_DMP_FULL_INPUT_GROUPS = 1;
localparam int GF_DMP_FULL_OUTPUT_LANES = 16;
localparam int GF_DMP_FULL_OUTPUT_PAIRS = 8;
localparam int GF_DMP_FULL_ACTIVE_TAPS = 16;
localparam int GF_DMP_FULL_WEIGHT_DMA_WORDS = 768;
localparam logic signed [31:0] gf_dmp_full_folded_bias [0:15] = '{
  -32'sd759152, -32'sd750884, -32'sd772438, -32'sd786287, -32'sd901894, -32'sd753538, -32'sd781288, -32'sd788286, -32'sd774518, -32'sd777615, -32'sd776349, -32'sd777534, -32'sd789501, -32'sd752484, -32'sd777889, -32'sd777629
};
