// PROJECT_LOCAL_SELF_RESEARCH_NOT_GOOGLE_OFFICIAL
// Generated by export_dmp_conv_layer.py. Do not hand edit.
localparam int GF_DMP_BODY2_REAL_INPUT_CHANNELS = 16;
localparam int GF_DMP_BODY2_PADDED_INPUT_CHANNELS = 16;
localparam int GF_DMP_BODY2_INPUT_GROUPS = 2;
localparam int GF_DMP_BODY2_OUTPUT_LANES = 16;
localparam int GF_DMP_BODY2_OUTPUT_PAIRS = 8;
localparam int GF_DMP_BODY2_ACTIVE_TAPS = 16;
localparam int GF_DMP_BODY2_WEIGHT_DMA_WORDS = 1536;
localparam logic signed [31:0] gf_dmp_body2_folded_bias [0:15] = '{
  -32'sd4196223, -32'sd4188360, -32'sd4192690, -32'sd4190937, -32'sd4192177, -32'sd4158419, -32'sd4187368, -32'sd4192928, -32'sd4191147, -32'sd4179466, -32'sd4189547, -32'sd4192838, -32'sd4184459, -32'sd4182643, -32'sd4190047, -32'sd4193153
};
