#!/usr/bin/env python3
"""PROJECT_LOCAL_MOD: generate an XSDB script that loads and runs the upstream
CoreMiniAxi hello_world_add_floats ELF through the 7020 GP0 AXI-Lite window."""

from __future__ import annotations

import struct
from pathlib import Path

from elftools.elf.elffile import ELFFile

ROOT = Path("/home/steveguo/coralnpu-gesture")
ELF_PATH = ROOT / "gesture_project/worktrees/coralnpu-upstream-sim/bazel-out/k8-fastbuild-ST-dd8dc713f32d/bin/examples/coralnpu_v2_hello_world_add_floats.elf"
OUT_PATH = ROOT / "gesture_project/board_validation/zynq7020_coralnpu_official/current/scripts/run_coremini_axi_hello_world_xsdb.tcl"
WIN_OUT_PATH = Path("/mnt/e/coralnpu_vivado/logs/run_coremini_axi_hello_world_xsdb.tcl")

BIT_PATH_WIN = "E:/coralnpu_vivado/projects/coralnpu_coremini_axi_7020_v8_fresh/axi_gpio.runs/impl_1/system_wrapper.bit"
XSA_PATH_WIN = "E:/coralnpu_vivado/projects/coralnpu_coremini_axi_7020_v8_fresh/vitis/system_wrapper/export/system_wrapper/hw/system_wrapper.xsa"
PS7_INIT_PATH_WIN = "E:/coralnpu_vivado/projects/coralnpu_coremini_axi_7020_v8_fresh/vitis/axi_gpio/_ide/psinit/ps7_init.tcl"

BASE = 0x43C00000
STATUS_ADDR = BASE + 0x00040004
MAGIC_ADDR = BASE + 0x00040000
PC_CSR_ADDR = BASE + 0x00030004
RESET_CSR_ADDR = BASE + 0x00030000

INPUT1 = [float(i) for i in range(1, 9)]
INPUT2 = [0.213 for _ in range(8)]
EXPECTED = [a + b for a, b in zip(INPUT1, INPUT2)]


def words_from_bytes(base_addr: int, data: bytes):
    padded = data + bytes((-len(data)) % 4)
    for offset in range(0, len(padded), 4):
        yield base_addr + offset, int.from_bytes(padded[offset:offset + 4], "little")


def find_symbol(elf: ELFFile, name: str) -> int:
    for section in elf.iter_sections():
        if section.header["sh_type"] != "SHT_SYMTAB":
            continue
        for sym in section.iter_symbols():
            if sym.name == name:
                return sym.entry["st_value"]
    raise KeyError(name)


with ELF_PATH.open("rb") as f:
    elf = ELFFile(f)
    entry = elf.header["e_entry"]
    input1_addr = find_symbol(elf, "input1")
    input2_addr = find_symbol(elf, "input2")
    output_addr = find_symbol(elf, "output")
    segments = []
    for seg in elf.iter_segments():
        if seg.header["p_type"] != "PT_LOAD":
            continue
        data = seg.data()
        if not data:
            continue
        segments.append((seg.header["p_paddr"], data))

lines = []
lines.append("# PROJECT_LOCAL_MOD: generated by gen_hello_world_xsdb.py")
lines.append("connect -url tcp:127.0.0.1:3121")
lines.append("targets -set -nocase -filter {name =~ \"APU*\"}")
lines.append("rst -system")
lines.append("after 3000")
lines.append("targets -set -nocase -filter {name =~ \"xc7z020\"}")
lines.append(f"fpga -file {BIT_PATH_WIN}")
lines.append("targets -set -nocase -filter {name =~ \"APU*\"}")
lines.append(f"loadhw -hw {XSA_PATH_WIN} -mem-ranges [list {{0x40000000 0xbfffffff}}] -regs")
lines.append("configparams force-mem-access 1")
lines.append(f"source {PS7_INIT_PATH_WIN}")
lines.append("ps7_init")
lines.append("ps7_post_config")
lines.append("after 1000")
lines.append("targets -set -nocase -filter {name =~ \"*A9*#0\"}")
lines.append(f"puts [format \"MAGIC_BEFORE=0x%08x\" [mrd -value 0x{MAGIC_ADDR:08x}]]")
for paddr, data in segments:
    for addr, word in words_from_bytes(paddr, data):
        lines.append(f"mwr 0x{BASE + addr:08x} 0x{word:08x}")

for idx, val in enumerate(INPUT1):
    word = struct.unpack("<I", struct.pack("<f", val))[0]
    lines.append(f"mwr 0x{BASE + input1_addr + idx * 4:08x} 0x{word:08x}")
for idx, val in enumerate(INPUT2):
    word = struct.unpack("<I", struct.pack("<f", val))[0]
    lines.append(f"mwr 0x{BASE + input2_addr + idx * 4:08x} 0x{word:08x}")

lines.append(f"mwr 0x{PC_CSR_ADDR:08x} 0x{entry:08x}")
lines.append(f"mwr 0x{RESET_CSR_ADDR:08x} 0x00000001")
lines.append(f"mwr 0x{RESET_CSR_ADDR:08x} 0x00000000")
lines.append("set timeout 1000")
lines.append("set halted 0")
lines.append("for {set i 0} {$i < $timeout} {incr i} {")
lines.append(f"  set status [mrd -value 0x{STATUS_ADDR:08x}]")
lines.append("  if {[expr {$status & 0x1}] != 0} {")
lines.append("    set halted 1")
lines.append("    puts [format \"HALTED status=0x%08x\" $status]")
lines.append("    break")
lines.append("  }")
lines.append("  after 10")
lines.append("}")
lines.append("if {!$halted} { error \"CoreMiniAxi did not halt in time\" }")
for idx, exp in enumerate(EXPECTED):
    exp_word = struct.unpack("<I", struct.pack("<f", exp))[0]
    addr = BASE + output_addr + idx * 4
    lines.append(f"set out{idx} [mrd -value 0x{addr:08x}]")
    lines.append(f"puts [format \"output[{idx}] addr=0x{addr:08x} raw=0x%08x expected=0x{exp_word:08x}\" $out{idx}]")
lines.append("configparams force-mem-access 0")
lines.append("exit")

content = "\n".join(lines) + "\n"
OUT_PATH.write_text(content)
WIN_OUT_PATH.write_text(content)
print(f"Wrote {OUT_PATH}")
print(f"Wrote {WIN_OUT_PATH}")
