# PROJECT_LOCAL_MOD: build a Zynq-7020 board project that replaces the
# tutorial AXI GPIO slave with a wrapper around a self-contained
# RvvCoreMini7020NoFloatAxi combined RTL file. For packaging stability we
# generate one project-local bundled SystemVerilog file that contains the full
# RVV body plus the AXI-Lite wrapper as the final top module.

proc generate_bundled_rvv_wrapper {rtl_dir} {
  set wrapper_v [file join $rtl_dir "coralnpu_rvv_coremini7020_nofloat_axil_wrapper.v"]
  set combined_rtl [file join $rtl_dir "rvv_coremini_axi_flat" "RvvCoreMini7020NoFloatAxi_combined.sv"]
  set bundled_top [file join $rtl_dir "rvv_coremini_axi_flat" "coralnpu_rvv_coremini7020_nofloat_axil_wrapper_bundled.sv"]
  set project_root [file dirname $rtl_dir]
  set shared_rtl_dir [file join $project_root "project_local_coremini_axi" "coremini_axi_rtl"]
  set prelude_files [list \
    [file join $shared_rtl_dir "registers.svh"] \
    [file join $shared_rtl_dir "cf_math_pkg.sv"] \
    [file join $shared_rtl_dir "fpnew_pkg.sv"]]

  if {![file exists $wrapper_v]} {
    error "Missing wrapper RTL: $wrapper_v"
  }
  if {![file exists $combined_rtl]} {
    error "Missing combined RVV RTL: $combined_rtl"
  }
  foreach prelude_file $prelude_files {
    if {![file exists $prelude_file]} {
      error "Missing bundled prelude file: $prelude_file"
    }
  }

  set out_fh [open $bundled_top w]
  puts $out_fh "// PROJECT_LOCAL_MOD: bundled RVV body + wrapper for Vivado IP packaging."
  puts $out_fh "// Auto-generated by rework_5_axi_gpio_to_rvv_coremini_7020_nofloat_flat.tcl."
  puts $out_fh ""
  puts $out_fh "`ifndef RVV_PROJECT_LOCAL_CFG_SVH"
  puts $out_fh "`define RVV_PROJECT_LOCAL_CFG_SVH"
  puts $out_fh "`define DISPATCH3"
  puts $out_fh "`define ARBITER_ON"
  puts $out_fh "`define VLEN_128"
  puts $out_fh "`endif"
  puts $out_fh ""

  foreach prelude_file $prelude_files {
    puts $out_fh "// ----- PROJECT_LOCAL_MOD BUNDLED PRELUDE [file tail $prelude_file] BEGIN -----"
    set in_fh [open $prelude_file r]
    fcopy $in_fh $out_fh
    close $in_fh
    puts $out_fh ""
    puts $out_fh "// ----- PROJECT_LOCAL_MOD BUNDLED PRELUDE [file tail $prelude_file] END -----"
    puts $out_fh ""
  }

  set in_fh [open $combined_rtl r]
  fcopy $in_fh $out_fh
  close $in_fh
  puts $out_fh ""
  puts $out_fh "// ----- PROJECT_LOCAL_MOD BUNDLED WRAPPER BEGIN -----"
  set in_fh [open $wrapper_v r]
  fcopy $in_fh $out_fh
  close $in_fh
  puts $out_fh ""
  puts $out_fh "// ----- PROJECT_LOCAL_MOD BUNDLED WRAPPER END -----"
  close $out_fh
  return $bundled_top
}

proc package_rvv_flat_ip {rtl_dir project_root} {
  set bundled_top [generate_bundled_rvv_wrapper $rtl_dir]
  set ip_repo_root [file join $project_root "ip_repo"]
  set ip_root [file join $ip_repo_root "coralnpu_rvv_coremini_flat_axi_1.0"]
  set pack_proj_dir [file join $project_root ".tmp_rvv_flat_pack"]
  set part_name "xc7z020clg400-2"

  if {[file exists $ip_root]} {
    file delete -force $ip_root
  }
  if {[file exists $pack_proj_dir]} {
    file delete -force $pack_proj_dir
  }
  file mkdir $ip_repo_root

  create_project -force coralnpu_rvv_flat_pack $pack_proj_dir -part $part_name
  add_files -norecurse $bundled_top
  set_property file_type SystemVerilog [get_files $bundled_top]
  set_property top coralnpu_rvv_coremini7020_nofloat_axil_wrapper [current_fileset]
  update_compile_order -fileset sources_1

  ipx::package_project -root_dir $ip_root -vendor user.org -library user -taxonomy /UserIP -import_files -force
  set core [ipx::current_core]
  set_property name coralnpu_rvv_coremini_flat_axi $core
  set_property display_name {CoralNPU RVV CoreMini Flat AXI} $core
  set_property description {Project-local flattened RvvCoreMini7020NoFloatAxi wrapper for Zynq-7020 feasibility measurement.} $core
  ipx::save_core $core
  close_project
  file delete -force $pack_proj_dir
  return $ip_repo_root
}

set script_dir [file dirname [file normalize [info script]]]
set project_root [file dirname $script_dir]
set proj_xpr [file join $project_root "axi_gpio.xpr"]
set rtl_dir  $script_dir
set log_dir [file normalize "E:/coralnpu_vivado/logs"]
set ip_repo_root [package_rvv_flat_ip $rtl_dir $project_root]

open_project $proj_xpr
set nav_xdc [file join $project_root "axi_gpio.srcs" "constrs_1" "new" "Navigator.xdc"]
set nav_file_objs [get_files -quiet */Navigator.xdc]
if {[llength $nav_file_objs]} {
  remove_files $nav_file_objs
}
if {[file exists $nav_xdc]} {
  file delete -force $nav_xdc
}
upgrade_ip [get_ips *]
set_property ip_repo_paths $ip_repo_root [current_project]
update_ip_catalog

open_bd_design [get_files */system.bd]

if {[llength [get_bd_intf_ports AXI_GPIO_KEY -quiet]]} {
  delete_bd_objs [get_bd_intf_ports AXI_GPIO_KEY]
}
if {[llength [get_bd_cells axi_gpio_0 -quiet]]} {
  delete_bd_objs [get_bd_cells axi_gpio_0]
}
if {[llength [get_bd_cells coralnpu_rvv_coremini_axi_0 -quiet]]} {
  delete_bd_objs [get_bd_cells coralnpu_rvv_coremini_axi_0]
}
if {[llength [get_bd_cells coralnpu_coremini_axi_0 -quiet]]} {
  catch {disconnect_bd_intf_net [get_bd_intf_nets ps7_0_axi_periph_M00_AXI] [get_bd_intf_pins coralnpu_coremini_axi_0/S_AXI]}
  delete_bd_objs [get_bd_cells coralnpu_coremini_axi_0]
}
if {[llength [get_bd_cells crvv_axi_0 -quiet]]} {
  delete_bd_objs [get_bd_cells crvv_axi_0]
}
if {[llength [get_bd_cells crvvflat_0 -quiet]]} {
  delete_bd_objs [get_bd_cells crvvflat_0]
}
if {[llength [get_bd_cells crvvmod_0 -quiet]]} {
  delete_bd_objs [get_bd_cells crvvmod_0]
}
set old_m00_net [lindex [get_bd_intf_nets -quiet ps7_0_axi_periph_M00_AXI] 0]
if {$old_m00_net ne ""} {
  catch {disconnect_bd_intf_net $old_m00_net [get_bd_intf_pins ps7_0_axi_periph/M00_AXI]}
}

create_bd_cell -type ip -vlnv user.org:user:coralnpu_rvv_coremini_flat_axi:1.0 crvvflat_0
set_property CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {25} [get_bd_cells processing_system7_0]
connect_bd_net [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins crvvflat_0/aclk]
set periph_rst_pin [lindex [get_bd_pins -quiet */peripheral_aresetn] 0]
connect_bd_net $periph_rst_pin [get_bd_pins crvvflat_0/aresetn]
connect_bd_intf_net [get_bd_intf_pins ps7_0_axi_periph/M00_AXI] [get_bd_intf_pins crvvflat_0/S_AXI]

set coral_addr_seg [lindex [get_bd_addr_segs -quiet crvvflat_0/S_AXI/*] 0]
assign_bd_address -offset 0x43C00000 -range 0x00100000 \
  -target_address_space [get_bd_addr_spaces processing_system7_0/Data] \
  $coral_addr_seg

set old_irq_net [lindex [get_bd_nets -quiet axi_gpio_0_ip2intc_irpt] 0]
set irq_pin [lindex [get_bd_pins -quiet processing_system7_0/IRQ_F2P] 0]
if {$old_irq_net ne "" && $irq_pin ne ""} {
  catch {disconnect_bd_net $old_irq_net $irq_pin}
}
set_property CONFIG.PCW_USE_FABRIC_INTERRUPT {0} [get_bd_cells processing_system7_0]

regenerate_bd_layout
validate_bd_design
save_bd_design
generate_target all [get_files */system.bd]
make_wrapper -files [get_files */system.bd] -top -import
update_compile_order -fileset sources_1

set synth_run [get_runs synth_1]
set impl_run  [get_runs impl_1]
reset_run $synth_run
reset_run $impl_run
launch_runs $impl_run -to_step write_bitstream -jobs 8
wait_on_run $impl_run

open_run $impl_run
report_utilization -file [file join $log_dir "coralnpu_rvv_coremini_flat_axi_7020_utilization_impl.rpt"]
report_timing_summary -file [file join $log_dir "coralnpu_rvv_coremini_flat_axi_7020_timing_impl.rpt"]
write_hw_platform -fixed -include_bit -force -file [file join $log_dir "coralnpu_rvv_coremini_flat_axi_7020.xsa"]

close_project
