# PROJECT_LOCAL_MOD: build a Zynq-7020 board project by packaging the proven
# accelerator-only RVV/CoralNPU OOC combined RTL as a custom AXI-Lite IP, then
# wiring that IP into the existing PS/AXI board design.

proc read_list_file {path} {
  set fp [open $path r]
  set data [split [read $fp] "\n"]
  close $fp
  return $data
}

proc append_unique {var_name value} {
  upvar 1 $var_name items
  if {[lsearch -exact $items $value] < 0} {
    lappend items $value
  }
}

proc ensure_bd_pin_connection {src_pin dst_pin} {
  set src_net [lindex [get_bd_nets -quiet -of_objects $src_pin] 0]
  set dst_net [lindex [get_bd_nets -quiet -of_objects $dst_pin] 0]

  if {$src_net ne "" && $dst_net ne "" && [get_property NAME $src_net] eq [get_property NAME $dst_net]} {
    return
  }

  if {$dst_net ne ""} {
    catch {disconnect_bd_net $dst_net $dst_pin}
  }
  connect_bd_net $src_pin $dst_pin
}

proc ensure_bd_intf_connection {src_intf dst_intf} {
  set src_net [lindex [get_bd_intf_nets -quiet -of_objects $src_intf] 0]
  set dst_net [lindex [get_bd_intf_nets -quiet -of_objects $dst_intf] 0]

  if {$src_net ne "" && $dst_net ne "" && [get_property NAME $src_net] eq [get_property NAME $dst_net]} {
    return
  }

  if {$dst_net ne ""} {
    catch {disconnect_bd_intf_net $dst_net $dst_intf}
  }
  connect_bd_intf_net $src_intf $dst_intf
}

proc should_skip_source {rel} {
  set rel [string trimleft [string trim $rel] "./"]
  set base [file tail $rel]

  if {$rel eq ""} {
    return 1
  }
  if {[string match "verification/*" $rel]} {
    return 1
  }

  foreach exact_name {
    "SCore.sv"
    "DebugModule.sv"
    "CoreCSR.sv"
    "Queue1_DebugModuleReqIO.sv"
    "Queue1_DebugModuleRspIO.sv"
    "RvvCoreMini7020Lane1Rb4NoFloat.sv"
    "RvvCoreMini7020Lane1Rb4NoFloatAxi.sv"
    "RvvCoreMini7020Lane1Rb4NoFloatAxi.zip"
  } {
    if {$base eq $exact_name} {
      return 1
    }
  }

  foreach pattern {
    "fpnew*"
    "rvv_backend_falu*"
    "rvv_backend_fdiv*"
    "rvv_backend_freduction*"
    "rvv_backend_sqrt7_rec7.sv"
    "ct_vfdsu*"
    "pa_f*"
    "div_sqrt_*"
    "*_mvp.sv"
    "control_mvp.sv"
    "preprocess_mvp.sv"
    "norm_div_sqrt_mvp.sv"
    "iteration_div_sqrt_mvp.sv"
    "nrbd_nrsc_mvp.sv"
    "defs_div_sqrt_mvp.sv"
    "compressor_3to2.sv"
    "compressor_4to2.sv"
  } {
    if {[string match $pattern $base]} {
      return 1
    }
  }

  return 0
}

proc resolve_flat_source {rtl_dir rel} {
  set rel [string trimleft [string trim $rel] "./"]
  set candidates [list \
    [file join $rtl_dir $rel] \
    [file join $rtl_dir [file tail $rel]] \
  ]
  foreach path $candidates {
    if {[file exists $path]} {
      return $path
    }
  }
  error "Missing source for $rel under $rtl_dir"
}

proc collect_rtl_files {rtl_dir top_name} {
  set rtl_files {}
  set filelists [list \
    [file join $rtl_dir "filelist.f"] \
    [file join $rtl_dir "firrtl_black_box_resource_files.f"] \
  ]

  foreach list_path $filelists {
    if {![file exists $list_path]} {
      error "Missing list file: $list_path"
    }
    foreach rel [read_list_file $list_path] {
      set rel [string trim $rel]
      if {[should_skip_source $rel]} {
        continue
      }
      append_unique rtl_files [resolve_flat_source $rtl_dir $rel]
    }
  }

  append_unique rtl_files [file join $rtl_dir "${top_name}.sv"]
  return $rtl_files
}

proc generate_combined_rtl {rtl_dir out_dir top_name} {
  set combined_path [file join $out_dir "${top_name}_combined.sv"]
  set rtl_files [collect_rtl_files $rtl_dir $top_name]
  set prelude_files [list \
    [file join $rtl_dir "cf_math_pkg.sv"] \
    [file join $rtl_dir "registers.svh"] \
    [file join $rtl_dir "rvv_lsu_axi_bridge_unit_stride_e32.sv"] \
    [file join $rtl_dir "coralnpu_stage3b_tensor_engine.sv"] \
    [file join $rtl_dir "coralnpu_stage3b_axi_dma.sv"] \
    [file join $rtl_dir "rvv_backend_define.svh"] \
    [file join $rtl_dir "rvv_backend_opcode.svh"] \
    [file join $rtl_dir "rvv_backend.svh"] \
    [file join $rtl_dir "rvv_backend_config.svh"] \
    [file join $rtl_dir "rvv_backend_alu.svh"] \
    [file join $rtl_dir "rvv_backend_dispatch.svh"] \
    [file join $rtl_dir "rvv_backend_div.svh"] \
    [file join $rtl_dir "rvv_backend_falu.svh"] \
    [file join $rtl_dir "rvv_backend_pmtrdt.svh"] \
    [file join $rtl_dir "rvv_backend_sva.svh"] \
  ]

  file mkdir $out_dir
  set out_fh [open $combined_path w]
  puts $out_fh "// PROJECT_LOCAL_MOD: accelerator-only bundled RTL for board-level IP packaging."
  puts $out_fh "// Auto-generated by rework_9_axi_gpio_to_rvv_accel_lane1_combined_ip_7020.tcl."
  puts $out_fh "`ifndef RVV_PROJECT_LOCAL_CFG_SVH"
  puts $out_fh "`define RVV_PROJECT_LOCAL_CFG_SVH"
  puts $out_fh "`define USE_GENERIC"
  puts $out_fh "`define ARBITER_ON"
  puts $out_fh "`define VLEN_64"
  puts $out_fh "`define PROJECT_LOCAL_CONV_ACCEL_ONLY"
  puts $out_fh "`endif"
  puts $out_fh ""

  foreach prelude $prelude_files {
    if {![file exists $prelude]} {
      error "Missing bundled prelude: $prelude"
    }
    puts $out_fh "// ----- PROJECT_LOCAL_MOD PRELUDE [file tail $prelude] BEGIN -----"
    set in_fh [open $prelude r]
    fcopy $in_fh $out_fh
    close $in_fh
    puts $out_fh ""
    puts $out_fh "// ----- PROJECT_LOCAL_MOD PRELUDE [file tail $prelude] END -----"
    puts $out_fh ""
  }

  foreach src $rtl_files {
    if {[lsearch -exact $prelude_files $src] >= 0} {
      continue
    }
    puts $out_fh "// ----- PROJECT_LOCAL_MOD SOURCE [file tail $src] BEGIN -----"
    set in_fh [open $src r]
    set src_data [read $in_fh]
    close $in_fh
    if {[file tail $src] eq "${top_name}.sv"} {
      set src_data [string map [list \
        "`include \"rvv_lsu_axi_bridge_unit_stride_e32.sv\"\r\n" "" \
        "`include \"rvv_lsu_axi_bridge_unit_stride_e32.sv\"\n" "" \
        "`include \"coralnpu_stage3b_tensor_engine.sv\"\r\n" "" \
        "`include \"coralnpu_stage3b_tensor_engine.sv\"\n" "" \
        "`include \"coralnpu_stage3b_axi_dma.sv\"\r\n" "" \
        "`include \"coralnpu_stage3b_axi_dma.sv\"\n" "" \
      ] $src_data]
    }
    puts -nonewline $out_fh $src_data
    puts $out_fh ""
    puts $out_fh "// ----- PROJECT_LOCAL_MOD SOURCE [file tail $src] END -----"
    puts $out_fh ""
  }

  close $out_fh
  return $combined_path
}

proc package_rvv_accel_combined_ip {rtl_dir project_root log_dir top_name} {
  set ip_repo_root [file join $project_root "ip_repo"]
  set ip_root [file join $ip_repo_root "coralnpu_rvv_accel_lane1_1.0"]
  set pack_proj_dir [file join $project_root ".tmp_rvv_accel_pack"]
  set bundle_dir [file join $log_dir "rvv_accel_board_bundle"]
  set part_name "xc7z020clg400-2"

  if {[file exists $ip_root]} {
    file delete -force $ip_root
  }
  if {[file exists $pack_proj_dir]} {
    file delete -force $pack_proj_dir
  }
  file mkdir $ip_repo_root

  set combined_rtl [generate_combined_rtl $rtl_dir $bundle_dir $top_name]

  create_project -force coralnpu_rvv_accel_pack $pack_proj_dir -part $part_name
  add_files -norecurse $combined_rtl
  set_property file_type SystemVerilog [get_files $combined_rtl]
  set_property top $top_name [current_fileset]
  update_compile_order -fileset sources_1

  ipx::package_project -root_dir $ip_root -vendor user.org -library user -taxonomy /UserIP -import_files -force
  set core [ipx::current_core]
  set_property name coralnpu_rvv_accel_lane1 $core
  set_property display_name {CoralNPU RVV Accelerator Lane1 AXI} $core
  set_property description {Project-local packaged accelerator-only RVV/CoralNPU wrapper for Zynq-7020 bring-up, based on the proven combined OOC RTL.} $core
  set clk_if [ipx::get_bus_interfaces aclk -of_objects $core]
  if {[llength $clk_if]} {
    set assoc_busif [ipx::get_bus_parameters -quiet ASSOCIATED_BUSIF -of_objects $clk_if]
    if {![llength $assoc_busif]} {
      set assoc_busif [ipx::add_bus_parameter ASSOCIATED_BUSIF $clk_if]
    }
    set_property value {S_AXI:M_AXI} $assoc_busif

    set assoc_reset [ipx::get_bus_parameters -quiet ASSOCIATED_RESET -of_objects $clk_if]
    if {![llength $assoc_reset]} {
      set assoc_reset [ipx::add_bus_parameter ASSOCIATED_RESET $clk_if]
    }
    set_property value {aresetn} $assoc_reset
  }
  ipx::save_core $core
  close_project
  file delete -force $pack_proj_dir
  return $ip_repo_root
}

set script_dir [file dirname [file normalize [info script]]]
set project_root [file dirname $script_dir]
set proj_xpr [file join $project_root "axi_gpio.xpr"]
set rtl_dir [file join $script_dir "rvv_accel_lane1"]
set log_dir [file normalize "E:/coralnpu_vivado/logs"]
set top_name "coralnpu_rvv_accel_lane1_axil_wrapper"
set ip_repo_root [package_rvv_accel_combined_ip $rtl_dir $project_root $log_dir $top_name]

open_project $proj_xpr
set nav_xdc [file join $project_root "axi_gpio.srcs" "constrs_1" "new" "Navigator.xdc"]
set nav_file_objs [get_files -quiet */Navigator.xdc]
if {[llength $nav_file_objs]} {
  remove_files $nav_file_objs
}
if {[file exists $nav_xdc]} {
  file delete -force $nav_xdc
}
upgrade_ip [get_ips *]
set_property ip_repo_paths $ip_repo_root [current_project]
update_ip_catalog

open_bd_design [get_files */system.bd]

if {[llength [get_bd_intf_ports AXI_GPIO_KEY -quiet]]} {
  delete_bd_objs [get_bd_intf_ports AXI_GPIO_KEY]
}
if {[llength [get_bd_cells axi_gpio_0 -quiet]]} {
  delete_bd_objs [get_bd_cells axi_gpio_0]
}
foreach cell_name {coralnpu_coremini_axi_0 crvv_axi_0 crvvflat_0 crvvmod_0 crvvaccel_0 axi_smc} {
  if {[llength [get_bd_cells $cell_name -quiet]]} {
    delete_bd_objs [get_bd_cells $cell_name]
  }
}

create_bd_cell -type ip -vlnv user.org:user:coralnpu_rvv_accel_lane1:1.0 crvvaccel_0
set_property -dict [list \
  CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {25} \
  CONFIG.PCW_USE_S_AXI_HP0 {1} \
  CONFIG.PCW_S_AXI_HP0_DATA_WIDTH {64} \
  CONFIG.PCW_S_AXI_HP0_ID_WIDTH {6} \
] [get_bd_cells processing_system7_0]
create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 axi_smc
set_property -dict [list CONFIG.NUM_SI {1} CONFIG.NUM_MI {1}] [get_bd_cells axi_smc]

catch {set_property CONFIG.FREQ_HZ 25000000 [get_bd_intf_pins crvvaccel_0/S_AXI]}
catch {set_property CONFIG.FREQ_HZ 25000000 [get_bd_intf_pins crvvaccel_0/M_AXI]}
catch {set_property CONFIG.FREQ_HZ 25000000 [get_bd_pins crvvaccel_0/aclk]}
catch {set_property CONFIG.FREQ_HZ 25000000 [get_bd_pins axi_smc/aclk]}

ensure_bd_pin_connection [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins crvvaccel_0/aclk]
ensure_bd_pin_connection [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins processing_system7_0/S_AXI_HP0_ACLK]
ensure_bd_pin_connection [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins axi_smc/aclk]
set periph_rst_pin [lindex [get_bd_pins -quiet */peripheral_aresetn] 0]
ensure_bd_pin_connection $periph_rst_pin [get_bd_pins crvvaccel_0/aresetn]
ensure_bd_pin_connection $periph_rst_pin [get_bd_pins axi_smc/aresetn]
ensure_bd_intf_connection [get_bd_intf_pins ps7_0_axi_periph/M00_AXI] [get_bd_intf_pins crvvaccel_0/S_AXI]
ensure_bd_intf_connection [get_bd_intf_pins crvvaccel_0/M_AXI] [get_bd_intf_pins axi_smc/S00_AXI]
ensure_bd_intf_connection [get_bd_intf_pins axi_smc/M00_AXI] [get_bd_intf_pins processing_system7_0/S_AXI_HP0]

set coral_addr_seg [lindex [get_bd_addr_segs -quiet crvvaccel_0/S_AXI/*] 0]
assign_bd_address -offset 0x43C00000 -range 0x00100000 \
  -target_address_space [get_bd_addr_spaces processing_system7_0/Data] \
  $coral_addr_seg

set accel_ddr_space [lindex [get_bd_addr_spaces -quiet crvvaccel_0/M_AXI] 0]
set hp0_ddr_seg [lindex [get_bd_addr_segs -quiet processing_system7_0/S_AXI_HP0/HP0_DDR_LOWOCM] 0]
if {$accel_ddr_space ne "" && $hp0_ddr_seg ne ""} {
  catch {assign_bd_address -target_address_space $accel_ddr_space $hp0_ddr_seg}
}
catch {assign_bd_address}

set irq_nets [get_bd_nets -quiet axi_gpio_0_ip2intc_irpt]
if {[llength $irq_nets]} {
  catch {disconnect_bd_net $irq_nets [get_bd_pins processing_system7_0/IRQ_F2P]}
}
set_property CONFIG.PCW_USE_FABRIC_INTERRUPT {0} [get_bd_cells processing_system7_0]

regenerate_bd_layout
validate_bd_design
save_bd_design
generate_target all [get_files */system.bd]
make_wrapper -files [get_files */system.bd] -top -import
update_compile_order -fileset sources_1

set synth_run [get_runs synth_1]
set impl_run  [get_runs impl_1]
reset_run $synth_run
reset_run $impl_run
launch_runs $impl_run -to_step write_bitstream -jobs 8
wait_on_run $impl_run

open_run $impl_run
report_utilization -hierarchical -file [file join $log_dir "coralnpu_rvv_accel_lane1_7020_utilization_hier_impl.rpt"]
report_utilization -file [file join $log_dir "coralnpu_rvv_accel_lane1_7020_utilization_impl.rpt"]
report_timing_summary -file [file join $log_dir "coralnpu_rvv_accel_lane1_7020_timing_impl.rpt"]
write_hw_platform -fixed -include_bit -force -file [file join $log_dir "coralnpu_rvv_accel_lane1_7020.xsa"]

close_project
