set rtl_dir "E:/coralnpu_vivado/projects/rvv_accel_only_7020_lane1_ooc/rtl"
set out_dir "E:/coralnpu_vivado/logs/rvv_accel_only_lane1_ooc_20260805"
set top_name "coralnpu_rvv_accel_lane1_axil_wrapper"
set part_name "xc7z020clg484-1"

proc read_list_file {path} {
  set fp [open $path r]
  set data [split [read $fp] "\n"]
  close $fp
  return $data
}

proc append_unique {var_name value} {
  upvar 1 $var_name items
  if {[lsearch -exact $items $value] < 0} {
    lappend items $value
  }
}

proc should_skip_source {rel} {
  set rel [string trimleft [string trim $rel] "./"]
  set base [file tail $rel]

  if {$rel eq ""} {
    return 1
  }
  if {[string match "verification/*" $rel]} {
    return 1
  }

  foreach exact_name {
    "SCore.sv"
    "DebugModule.sv"
    "CoreCSR.sv"
    "Queue1_DebugModuleReqIO.sv"
    "Queue1_DebugModuleRspIO.sv"
    "RvvCoreMini7020Lane1Rb4NoFloat.sv"
    "RvvCoreMini7020Lane1Rb4NoFloatAxi.sv"
    "RvvCoreMini7020Lane1Rb4NoFloatAxi.zip"
  } {
    if {$base eq $exact_name} {
      return 1
    }
  }

  # PROJECT_LOCAL_MOD: accelerator-only first pass keeps integer RVV execution
  # and removes the vector floating-point / scalar-core-only source baggage.
  foreach pattern {
    "fpnew*"
    "rvv_backend_falu*"
    "rvv_backend_fdiv*"
    "rvv_backend_freduction*"
    "rvv_backend_sqrt7_rec7.sv"
    "ct_vfdsu*"
    "pa_f*"
    "div_sqrt_*"
    "*_mvp.sv"
    "control_mvp.sv"
    "preprocess_mvp.sv"
    "norm_div_sqrt_mvp.sv"
    "iteration_div_sqrt_mvp.sv"
    "nrbd_nrsc_mvp.sv"
    "defs_div_sqrt_mvp.sv"
    "compressor_3to2.sv"
    "compressor_4to2.sv"
  } {
    if {[string match $pattern $base]} {
      return 1
    }
  }

  return 0
}

proc resolve_flat_source {rtl_dir rel} {
  set rel [string trimleft [string trim $rel] "./"]
  set candidates [list \
    [file join $rtl_dir $rel] \
    [file join $rtl_dir [file tail $rel]] \
  ]
  foreach path $candidates {
    if {[file exists $path]} {
      return $path
    }
  }
  error "Missing source for $rel under $rtl_dir"
}

proc collect_rtl_files {rtl_dir top_name} {
  set rtl_files {}
  set filelists [list \
    [file join $rtl_dir "filelist.f"] \
    [file join $rtl_dir "firrtl_black_box_resource_files.f"] \
  ]

  foreach list_path $filelists {
    if {![file exists $list_path]} {
      error "Missing list file: $list_path"
    }
    foreach rel [read_list_file $list_path] {
      set rel [string trim $rel]
      if {[should_skip_source $rel]} {
        continue
      }
      append_unique rtl_files [resolve_flat_source $rtl_dir $rel]
    }
  }

  append_unique rtl_files [file join $rtl_dir "${top_name}.sv"]
  return $rtl_files
}

proc generate_combined_rtl {rtl_dir out_dir top_name} {
  set combined_path [file join $out_dir "${top_name}_combined.sv"]
  set rtl_files [collect_rtl_files $rtl_dir $top_name]
  set prelude_files [list \
    [file join $rtl_dir "cf_math_pkg.sv"] \
    [file join $rtl_dir "registers.svh"] \
    [file join $rtl_dir "rvv_backend_define.svh"] \
    [file join $rtl_dir "rvv_backend_opcode.svh"] \
    [file join $rtl_dir "rvv_backend.svh"] \
    [file join $rtl_dir "rvv_backend_config.svh"] \
    [file join $rtl_dir "rvv_backend_alu.svh"] \
    [file join $rtl_dir "rvv_backend_dispatch.svh"] \
    [file join $rtl_dir "rvv_backend_div.svh"] \
    [file join $rtl_dir "rvv_backend_falu.svh"] \
    [file join $rtl_dir "rvv_backend_pmtrdt.svh"] \
    [file join $rtl_dir "rvv_backend_sva.svh"] \
  ]

  set out_fh [open $combined_path w]
  puts $out_fh "// PROJECT_LOCAL_MOD: accelerator-only bundled RTL for Vivado OOC synthesis."
  puts $out_fh "// Auto-generated by synth_rvv_accel_lane1_ooc_7020.tcl."
  puts $out_fh "`ifndef RVV_PROJECT_LOCAL_CFG_SVH"
  puts $out_fh "`define RVV_PROJECT_LOCAL_CFG_SVH"
  puts $out_fh "`define USE_GENERIC"
  puts $out_fh "`define ARBITER_ON"
  puts $out_fh "`define VLEN_64"
  puts $out_fh "`endif"
  puts $out_fh ""

  foreach prelude $prelude_files {
    if {![file exists $prelude]} {
      error "Missing bundled prelude: $prelude"
    }
    puts $out_fh "// ----- PROJECT_LOCAL_MOD PRELUDE [file tail $prelude] BEGIN -----"
    set in_fh [open $prelude r]
    fcopy $in_fh $out_fh
    close $in_fh
    puts $out_fh ""
    puts $out_fh "// ----- PROJECT_LOCAL_MOD PRELUDE [file tail $prelude] END -----"
    puts $out_fh ""
  }

  foreach src $rtl_files {
    if {[lsearch -exact $prelude_files $src] >= 0} {
      continue
    }
    puts $out_fh "// ----- PROJECT_LOCAL_MOD SOURCE [file tail $src] BEGIN -----"
    set in_fh [open $src r]
    fcopy $in_fh $out_fh
    close $in_fh
    puts $out_fh ""
    puts $out_fh "// ----- PROJECT_LOCAL_MOD SOURCE [file tail $src] END -----"
    puts $out_fh ""
  }

  close $out_fh
  return $combined_path
}

file mkdir $out_dir

create_project -in_memory rvv_accel_only_7020_lane1 -part $part_name

set combined_rtl [generate_combined_rtl $rtl_dir $out_dir $top_name]
set_property include_dirs [list $rtl_dir] [current_fileset]
read_verilog -sv $combined_rtl

update_compile_order -fileset sources_1
synth_design -top $top_name -part $part_name -mode out_of_context

report_utilization -file [file join $out_dir "rvv_accel_only_lane1_util.rpt"]
report_utilization -hierarchical -file [file join $out_dir "rvv_accel_only_lane1_util_hier.rpt"]
report_timing_summary -file [file join $out_dir "rvv_accel_only_lane1_timing.rpt"]

exit
