#!/usr/bin/env bash
set -euo pipefail
# PROJECT_LOCAL_SELF_RESEARCH_NOT_GOOGLE_OFFICIAL
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="$root/board_7020/software/gestureflow_layer_chain_hp0_main.c"
body_src="$root/board_7020/software/gestureflow_chain_body_data.c"
full_header="$root/board_7020/software/gestureflow_real_conv4x4_full_layer.h"
body_header="$root/board_7020/software/gestureflow_real_conv4x4_body2_layer.h"
body_data_header="$root/board_7020/software/gestureflow_chain_body_data.h"
pool_header="$root/board_7020/software/gestureflow_real_maxpool2d.h"
pool2_header="$root/board_7020/software/gestureflow_real_maxpool2d_pool2.h"
conv2a_header="$root/board_7020/software/gestureflow_real_conv4x4_conv2a_layer.h"
conv2b_header="$root/board_7020/software/gestureflow_real_conv4x4_conv2b_layer.h"
conv3a_header="$root/board_7020/software/gestureflow_real_conv4x4_conv3a_layer.h"
conv3b_header="$root/board_7020/software/gestureflow_real_conv4x4_conv3b_layer.h"
pool3_header="$root/board_7020/software/gestureflow_real_maxpool2d_pool3.h"
dst=/mnt/e/coralnpu_vivado/projects/gestureflow_layer_chain_hp0_7020_v1
app="$dst/vitis/axi_gpio"
include_win='E:\coralnpu_vivado\projects\gestureflow_layer_chain_hp0_7020_v1\vitis\system_wrapper\export\system_wrapper\sw\system_wrapper\standalone_ps7_cortexa9_0\bspinclude\include'
lib_win='E:\coralnpu_vivado\projects\gestureflow_layer_chain_hp0_7020_v1\vitis\system_wrapper\export\system_wrapper\sw\system_wrapper\standalone_ps7_cortexa9_0\bsplib\lib'
mkdir -p "$app/src" "$app/Debug"
cp -f "$src" "$app/src/gestureflow_layer_chain_hp0_main.c"
cp -f "$body_src" "$app/src/gestureflow_chain_body_data.c"
cp -f "$full_header" "$app/src/gestureflow_real_conv4x4_full_layer.h"
cp -f "$body_header" "$app/src/gestureflow_real_conv4x4_body2_layer.h"
cp -f "$body_data_header" "$app/src/gestureflow_chain_body_data.h"
cp -f "$pool_header" "$app/src/gestureflow_real_maxpool2d.h"
cp -f "$pool2_header" "$app/src/gestureflow_real_maxpool2d_pool2.h"
cp -f "$conv2a_header" "$app/src/gestureflow_real_conv4x4_conv2a_layer.h"
cp -f "$conv2b_header" "$app/src/gestureflow_real_conv4x4_conv2b_layer.h"
cp -f "$conv3a_header" "$app/src/gestureflow_real_conv4x4_conv3a_layer.h"
cp -f "$conv3b_header" "$app/src/gestureflow_real_conv4x4_conv3b_layer.h"
cp -f "$pool3_header" "$app/src/gestureflow_real_maxpool2d_pool3.h"
cp -f "$app/src/lscript.ld" "$app/src/gestureflow_layer_chain_hp0.ld"
cmd.exe /d /s /c "set PATH=E:\Xilinx\Vitis\2023.2\gnu\aarch32\nt\gcc-arm-none-eabi\bin;E:\Xilinx\Vitis\2023.2\gnuwin\bin;%PATH% && pushd E:\coralnpu_vivado\projects\gestureflow_layer_chain_hp0_7020_v1\vitis\axi_gpio\Debug && arm-none-eabi-gcc -Wall -O2 -g3 -c -mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -I${include_win} -o gestureflow_layer_chain_hp0_main.o ..\src\gestureflow_layer_chain_hp0_main.c && arm-none-eabi-gcc -Wall -O2 -g3 -c -mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -I${include_win} -o gestureflow_chain_body_data.o ..\src\gestureflow_chain_body_data.c && arm-none-eabi-gcc -mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -Wl,-build-id=none -specs=Xilinx.spec -Wl,-T -Wl,..\src\gestureflow_layer_chain_hp0.ld -L${lib_win} -o gestureflow_layer_chain_hp0.elf gestureflow_layer_chain_hp0_main.o gestureflow_chain_body_data.o -Wl,--start-group -lxil -lgcc -lc -Wl,--end-group && arm-none-eabi-size gestureflow_layer_chain_hp0.elf"
