`ifndef SYNTHESIS // Added by Core.scala Verification Wrapper

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module DispatchV2_Verification_Assert(
  input decodedInsts_0_sub,
        _GEN,
        _GEN_0,
        _GEN_1,
        _GEN_2,
        _GEN_3,
        _GEN_4,
        _GEN_5,
        _GEN_6,
        _GEN_7,
        decodedInsts_0_orn,
        decodedInsts_0_xnor,
        decodedInsts_0_lui,
        decodedInsts_0_andn,
        decodedInsts_0_ctz,
        decodedInsts_0_cpop,
        decodedInsts_0_clz,
        decodedInsts_0_min,
        decodedInsts_0_minu,
        decodedInsts_0_max,
        decodedInsts_0_maxu,
        decodedInsts_0_rol,
        decodedInsts_0_ror,
        decodedInsts_0_sextb,
        decodedInsts_0_sexth,
        decodedInsts_0_zexth,
        decodedInsts_0_rori,
        decodedInsts_0_orcb,
        decodedInsts_0_rev8,
        reset,
        _GEN_8,
        decodedInsts_0_jalr,
        decodedInsts_0_beq,
        decodedInsts_0_jal,
        decodedInsts_0_blt,
        decodedInsts_0_bge,
        decodedInsts_0_bne,
        decodedInsts_0_bgeu,
        decodedInsts_0_ebreak,
        decodedInsts_0_bltu,
        decodedInsts_0_mret,
        decodedInsts_0_wfi,
        decodedInsts_0_ecall,
        decodedInsts_0_mpause,
        decodedInsts_0_mulhsu,
        decodedInsts_0_mulhu,
        decodedInsts_0_mul,
        decodedInsts_0_mulh,
        decodedInsts_0_rem,
        decodedInsts_0_remu,
        decodedInsts_0_div,
        decodedInsts_0_divu,
        decodedInsts_0_lbu,
        decodedInsts_0_lhu,
        decodedInsts_0_lw,
        decodedInsts_0_lb,
        decodedInsts_0_lh,
        decodedInsts_0_fencei,
        decodedInsts_0_sw,
        decodedInsts_0_sb,
        decodedInsts_0_sh,
        _GEN_9,
        _GEN_10,
        decodedInsts_0_flushat,
        decodedInsts_0_flushall,
        _GEN_11,
        _GEN_12,
        _GEN_13,
        _GEN_14,
        _GEN_15,
        _GEN_16,
        decodedInsts_0_csrrs,
        decodedInsts_0_csrrc,
        decodedInsts_0_csrrw,
        clock
);

  `ifndef SYNTHESIS
    wire [1:0] _alu_bitsUInt_T_31 = {1'h0, decodedInsts_0_sub} + {1'h0, _GEN};
    wire [1:0] _GEN_17 = {1'h0, _GEN_0};
    wire [2:0] _GEN_18 = {1'h0, {1'h0, _GEN_3} + {1'h0, _GEN_4}};
    wire [2:0] _GEN_19 = {1'h0, {1'h0, _GEN_1} + {1'h0, _GEN_2}};
    wire [1:0] _alu_bitsUInt_T_43 = {1'h0, _GEN_5} + {1'h0, _GEN_6};
    wire [1:0] _GEN_20 = {1'h0, _GEN_7};
    wire [2:0] _GEN_21 = {1'h0, {1'h0, decodedInsts_0_lui} + {1'h0, decodedInsts_0_andn}};
    wire [2:0] _GEN_22 = {1'h0, {1'h0, decodedInsts_0_orn} + {1'h0, decodedInsts_0_xnor}};
    wire [1:0] _alu_bitsUInt_T_57 =
      {1'h0, decodedInsts_0_ctz} + {1'h0, decodedInsts_0_cpop};
    wire [1:0] _GEN_23 = {1'h0, decodedInsts_0_clz};
    wire [2:0] _GEN_24 = {1'h0, {1'h0, decodedInsts_0_max} + {1'h0, decodedInsts_0_maxu}};
    wire [2:0] _GEN_25 = {1'h0, {1'h0, decodedInsts_0_min} + {1'h0, decodedInsts_0_minu}};
    wire [2:0] _GEN_26 =
      {1'h0, {1'h0, decodedInsts_0_orcb} + {1'h0, decodedInsts_0_rev8}};
    wire [2:0] _GEN_27 =
      {1'h0, {1'h0, decodedInsts_0_zexth} + {1'h0, decodedInsts_0_rori}};
    wire [2:0] _GEN_28 =
      {1'h0, {1'h0, decodedInsts_0_sextb} + {1'h0, decodedInsts_0_sexth}};
    wire [2:0] _GEN_29 = {1'h0, {1'h0, decodedInsts_0_rol} + {1'h0, decodedInsts_0_ror}};
    wire [4:0] _GEN_30 = {4'h0, _GEN_8};
    wire [1:0] _bru_bitsUInt_T_15 =
      {1'h0, decodedInsts_0_jalr} + {1'h0, decodedInsts_0_beq};
    wire [1:0] _GEN_31 = {1'h0, decodedInsts_0_jal};
    wire [1:0] _bru_bitsUInt_T_19 =
      {1'h0, decodedInsts_0_blt} + {1'h0, decodedInsts_0_bge};
    wire [1:0] _GEN_32 = {1'h0, decodedInsts_0_bne};
    wire [1:0] _bru_bitsUInt_T_25 =
      {1'h0, decodedInsts_0_bgeu} + {1'h0, decodedInsts_0_ebreak};
    wire [1:0] _GEN_33 = {1'h0, decodedInsts_0_bltu};
    wire [1:0] _GEN_34 = {1'h0, decodedInsts_0_wfi};
    wire [2:0] _GEN_35 =
      {1'h0, {1'h0, decodedInsts_0_ecall} + {1'h0, decodedInsts_0_mpause}};
    wire [2:0] _GEN_36 = {1'h0, {1'h0, decodedInsts_0_mret} + _GEN_34};
    wire [3:0] _GEN_37 = {3'h0, _GEN_8};
    wire [2:0] _GEN_38 = {1'h0, {1'h0, decodedInsts_0_mul} + {1'h0, decodedInsts_0_mulh}};
    wire [2:0] _GEN_39 =
      {1'h0, {1'h0, decodedInsts_0_mulhsu} + {1'h0, decodedInsts_0_mulhu}};
    wire [2:0] _GEN_40 = {2'h0, _GEN_8};
    wire [2:0] _GEN_41 = {1'h0, {1'h0, decodedInsts_0_div} + {1'h0, decodedInsts_0_divu}};
    wire [2:0] _GEN_42 = {1'h0, {1'h0, decodedInsts_0_rem} + {1'h0, decodedInsts_0_remu}};
    wire [1:0] _lsu_bitsUInt_T_25 =
      {1'h0, decodedInsts_0_lbu} + {1'h0, decodedInsts_0_lhu};
    wire [1:0] _GEN_43 = {1'h0, decodedInsts_0_lw};
    wire [1:0] _lsu_bitsUInt_T_33 = _GEN_34 + {1'h0, decodedInsts_0_fencei};
    wire [1:0] _GEN_44 = {1'h0, decodedInsts_0_sw};
    wire [2:0] _GEN_45 = {1'h0, {1'h0, decodedInsts_0_sb} + {1'h0, decodedInsts_0_sh}};
    wire [2:0] _GEN_46 = {1'h0, {1'h0, decodedInsts_0_lb} + {1'h0, decodedInsts_0_lh}};
    wire [1:0] _lsu_bitsUInt_T_49 = {1'h0, _GEN_11} + {1'h0, _GEN_12};
    wire [1:0] _GEN_47 = {1'h0, _GEN_13};
    wire [1:0] _lsu_bitsUInt_T_53 = {1'h0, _GEN_14} + {1'h0, _GEN_15};
    wire [1:0] _GEN_48 = {1'h0, _GEN_16};
    wire [2:0] _GEN_49 =
      {1'h0, {1'h0, decodedInsts_0_flushat} + {1'h0, decodedInsts_0_flushall}};
    wire [2:0] _GEN_50 = {1'h0, {1'h0, _GEN_9} + {1'h0, _GEN_10}};
    wire [1:0] _csr_bitsUInt_T_5 =
      {1'h0, decodedInsts_0_csrrs} + {1'h0, decodedInsts_0_csrrc};
    wire [1:0] _GEN_51 = {1'h0, decodedInsts_0_csrrw};
    wire [1:0] _GEN_52 = {1'h0, _GEN_8};
    always @(posedge clock) begin
      if (~reset
          & {1'h0,
             {1'h0, {1'h0, _GEN_17 + _alu_bitsUInt_T_31} + _GEN_18 + _GEN_19}
               + {1'h0, {1'h0, _GEN_20 + _alu_bitsUInt_T_43} + _GEN_21 + _GEN_22}}
          + {1'h0,
             {1'h0, {1'h0, _GEN_23 + _alu_bitsUInt_T_57} + _GEN_24 + _GEN_25}
               + {1'h0, _GEN_28 + _GEN_29} + {1'h0, _GEN_26 + _GEN_27}} > _GEN_30) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, {1'h0, _GEN_17 + _alu_bitsUInt_T_31} + _GEN_18 + _GEN_19}
               + {1'h0, {1'h0, _GEN_20 + _alu_bitsUInt_T_43} + _GEN_21 + _GEN_22}}
          + {1'h0,
             {1'h0, {1'h0, _GEN_23 + _alu_bitsUInt_T_57} + _GEN_24 + _GEN_25}
               + {1'h0, _GEN_28 + _GEN_29} + {1'h0, _GEN_26 + _GEN_27}} > _GEN_30) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_31 + _bru_bitsUInt_T_15} + {1'h0, _GEN_32 + _bru_bitsUInt_T_19}}
          + {1'h0,
             {1'h0, _GEN_33 + _bru_bitsUInt_T_25} + _GEN_35 + _GEN_36} > _GEN_37) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_31 + _bru_bitsUInt_T_15} + {1'h0, _GEN_32 + _bru_bitsUInt_T_19}}
          + {1'h0,
             {1'h0, _GEN_33 + _bru_bitsUInt_T_25} + _GEN_35 + _GEN_36} > _GEN_37) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_38 + _GEN_39 > _GEN_40) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_38 + _GEN_39 > _GEN_40) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_41 + _GEN_42 > _GEN_40) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_41 + _GEN_42 > _GEN_40) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_46 + {1'h0, _GEN_43 + _lsu_bitsUInt_T_25}}
               + {1'h0, _GEN_45 + {1'h0, _GEN_44 + _lsu_bitsUInt_T_33}}}
          + {1'h0,
             {1'h0, _GEN_49 + _GEN_50}
               + {1'h0,
                  {1'h0, _GEN_47 + _lsu_bitsUInt_T_49}
                    + {1'h0, _GEN_48 + _lsu_bitsUInt_T_53}}} > _GEN_30) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_46 + {1'h0, _GEN_43 + _lsu_bitsUInt_T_25}}
               + {1'h0, _GEN_45 + {1'h0, _GEN_44 + _lsu_bitsUInt_T_33}}}
          + {1'h0,
             {1'h0, _GEN_49 + _GEN_50}
               + {1'h0,
                  {1'h0, _GEN_47 + _lsu_bitsUInt_T_49}
                    + {1'h0, _GEN_48 + _lsu_bitsUInt_T_53}}} > _GEN_30) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_51 + _csr_bitsUInt_T_5 > _GEN_52) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_51 + _csr_bitsUInt_T_5 > _GEN_52) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule


`endif // Added by Core.scala Verification Wrapper
