`ifndef SYNTHESIS // Added by Core.scala Verification Wrapper

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module Regfile_Verification_Assert(
  input _GEN,
        _GEN_0,
        _GEN_1,
        reset,
        _GEN_2,
        _GEN_3,
        _GEN_4,
        _GEN_5,
        _GEN_6,
        _GEN_7,
        _GEN_8,
        _GEN_9,
        _GEN_10,
        _GEN_11,
        _GEN_12,
        _GEN_13,
        _GEN_14,
        _GEN_15,
        _GEN_16,
        _GEN_17,
        _GEN_18,
        _GEN_19,
        _GEN_20,
        _GEN_21,
        _GEN_22,
        _GEN_23,
        _GEN_24,
        _GEN_25,
        _GEN_26,
        _GEN_27,
        _GEN_28,
        _GEN_29,
        _GEN_30,
        _GEN_31,
        _GEN_32,
        _GEN_33,
        _GEN_34,
        _GEN_35,
        _GEN_36,
        _GEN_37,
        _GEN_38,
        _GEN_39,
        _GEN_40,
        _GEN_41,
        _GEN_42,
        _GEN_43,
        _GEN_44,
        _GEN_45,
        _GEN_46,
        _GEN_47,
        _GEN_48,
        _GEN_49,
        _GEN_50,
        _GEN_51,
        _GEN_52,
        _GEN_53,
        _GEN_54,
        _GEN_55,
        _GEN_56,
        _GEN_57,
        _GEN_58,
        _GEN_59,
        _GEN_60,
        _GEN_61,
        _GEN_62,
        _GEN_63,
        _GEN_64,
        _GEN_65,
        _GEN_66,
        _GEN_67,
        _GEN_68,
        _GEN_69,
        _GEN_70,
        _GEN_71,
        _GEN_72,
        _GEN_73,
        _GEN_74,
        _GEN_75,
        _GEN_76,
        _GEN_77,
        _GEN_78,
        _GEN_79,
        _GEN_80,
        _GEN_81,
        _GEN_82,
        _GEN_83,
        _GEN_84,
        _GEN_85,
        _GEN_86,
        _GEN_87,
        _GEN_88,
        _GEN_89,
        _GEN_90,
        _GEN_91,
        _GEN_92,
        write_fail,
        write_fail_1,
        write_fail_2,
        scoreboard_error,
        clock
);

  `ifndef SYNTHESIS
    wire [1:0] _GEN_93 = {1'h0, _GEN_2};
    always @(posedge clock) begin
      if (~reset & {1'h0, _GEN_1} + {1'h0, _GEN} + {1'h0, _GEN_0} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_5} + {1'h0, _GEN_3} + {1'h0, _GEN_4} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_8} + {1'h0, _GEN_6} + {1'h0, _GEN_7} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_11} + {1'h0, _GEN_9} + {1'h0, _GEN_10} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_14} + {1'h0, _GEN_12} + {1'h0, _GEN_13} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_17} + {1'h0, _GEN_15} + {1'h0, _GEN_16} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_20} + {1'h0, _GEN_18} + {1'h0, _GEN_19} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_23} + {1'h0, _GEN_21} + {1'h0, _GEN_22} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_26} + {1'h0, _GEN_24} + {1'h0, _GEN_25} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_29} + {1'h0, _GEN_27} + {1'h0, _GEN_28} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_32} + {1'h0, _GEN_30} + {1'h0, _GEN_31} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_35} + {1'h0, _GEN_33} + {1'h0, _GEN_34} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_38} + {1'h0, _GEN_36} + {1'h0, _GEN_37} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_41} + {1'h0, _GEN_39} + {1'h0, _GEN_40} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_44} + {1'h0, _GEN_42} + {1'h0, _GEN_43} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_47} + {1'h0, _GEN_45} + {1'h0, _GEN_46} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_50} + {1'h0, _GEN_48} + {1'h0, _GEN_49} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_53} + {1'h0, _GEN_51} + {1'h0, _GEN_52} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_56} + {1'h0, _GEN_54} + {1'h0, _GEN_55} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_59} + {1'h0, _GEN_57} + {1'h0, _GEN_58} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_62} + {1'h0, _GEN_60} + {1'h0, _GEN_61} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_65} + {1'h0, _GEN_63} + {1'h0, _GEN_64} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_68} + {1'h0, _GEN_66} + {1'h0, _GEN_67} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_71} + {1'h0, _GEN_69} + {1'h0, _GEN_70} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_74} + {1'h0, _GEN_72} + {1'h0, _GEN_73} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_77} + {1'h0, _GEN_75} + {1'h0, _GEN_76} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_80} + {1'h0, _GEN_78} + {1'h0, _GEN_79} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_83} + {1'h0, _GEN_81} + {1'h0, _GEN_82} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_86} + {1'h0, _GEN_84} + {1'h0, _GEN_85} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_89} + {1'h0, _GEN_87} + {1'h0, _GEN_88} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_92} + {1'h0, _GEN_90} + {1'h0, _GEN_91} > _GEN_93) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_1) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_2) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & scoreboard_error) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:242\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule


`endif // Added by Core.scala Verification Wrapper
