`ifndef SYNTHESIS // Added by Core.scala Verification Wrapper

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_RvvCoreMini7020Lane1Rb4NoFloatAxi_Verification_Assume
`define layers_RvvCoreMini7020Lane1Rb4NoFloatAxi_Verification_Assume
`endif // layers_RvvCoreMini7020Lane1Rb4NoFloatAxi_Verification_Assume

`endif // Added by Core.scala Verification Wrapper
