# PROJECT_LOCAL_SELF_RESEARCH_NOT_GOOGLE_OFFICIAL
# ZCU104 / Zynq UltraScale+ timing constraints for the GestureFlow DMP
# full-network layer chain.  The PL clock is generated by the PS (pl_clk0) and
# is constrained automatically by the block design; only the same quasi-static
# AXI-Lite configuration relaxation as on the verified 7020 build is needed.
#
# layer_mode is written once per layer by the PS before the CONTROL launch word
# and stays constant for the whole layer execution.  Vivado nevertheless times
# it as a normal 1-cycle register, placing a long mostly-routed chain
# (layer_mode -> mode mux -> loader pixel_ready -> m_axi_rready -> SmartConnect
# command FIFO) on the critical path.  Its launch edge is therefore removed;
# dynamic handshake paths starting from pixel_valid/fifo_bytes/state are still
# timed normally.
set_false_path -from [get_cells -hierarchical -filter {NAME =~ "*layer_mode_reg*"}]
