// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
module Aligner_123_1(
  input logic in_0_valid,
  input logic [123-1:0] in_0_bits,
  output logic out_0_valid,
  output logic [123-1:0] out_0_bits);

  logic [1-1:0] valid_in;
  assign valid_in[0] = in_0_valid;
  logic [1-1:0][123-1:0] data_in;
  assign data_in[0] = in_0_bits;
  logic [1-1:0] valid_out;
  assign out_0_valid = valid_out[0];
  logic [1-1:0][123-1:0] data_out;
  assign out_0_bits = data_out[0];

  Aligner#(.T (logic [123-1:0]), .N(1)) aligner(
    valid_in,
    data_in,
    valid_out,
    data_out
  );
endmodule