// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
module Arbiter1_MluCmd(
  input        io_in_0_valid,
  input  [4:0] io_in_0_bits_addr,
  input  [2:0] io_in_0_bits_op,
  output       io_out_valid,
  output [4:0] io_out_bits_addr,
  output [2:0] io_out_bits_op
);

  assign io_out_valid = io_in_0_valid;
  assign io_out_bits_addr = io_in_0_bits_addr;
  assign io_out_bits_op = io_in_0_bits_op;
endmodule

