// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module CircularBufferMulti_1(
  input         clock,
                reset,
                io_enqValid,
                io_enqData_0_store,
  input  [4:0]  io_enqData_0_rd,
                io_enqData_0_op,
  input  [31:0] io_enqData_0_pc,
                io_enqData_0_addr,
                io_enqData_0_data,
  input  [2:0]  io_enqData_0_elemWidth,
                io_enqData_0_sew,
                io_enqData_0_emul_data,
                io_enqData_0_emul_data_orig,
                io_enqData_0_nfields,
  input         io_enqData_0_strict,
  output [2:0]  io_nEnqueued,
                io_nSpace,
  output        io_dataOut_0_store,
  output [4:0]  io_dataOut_0_rd,
                io_dataOut_0_op,
  output [31:0] io_dataOut_0_pc,
                io_dataOut_0_addr,
                io_dataOut_0_data,
  output [2:0]  io_dataOut_0_elemWidth,
                io_dataOut_0_sew,
                io_dataOut_0_emul_data,
                io_dataOut_0_emul_data_orig,
                io_dataOut_0_nfields,
  output        io_dataOut_0_strict,
  input         io_deqReady,
                io_flush
);

  reg              buffer_0_store;
  reg  [4:0]       buffer_0_rd;
  reg  [4:0]       buffer_0_op;
  reg  [31:0]      buffer_0_pc;
  reg  [31:0]      buffer_0_addr;
  reg  [31:0]      buffer_0_data;
  reg  [2:0]       buffer_0_elemWidth;
  reg  [2:0]       buffer_0_sew;
  reg  [2:0]       buffer_0_emul_data;
  reg  [2:0]       buffer_0_emul_data_orig;
  reg  [2:0]       buffer_0_nfields;
  reg              buffer_0_strict;
  reg              buffer_1_store;
  reg  [4:0]       buffer_1_rd;
  reg  [4:0]       buffer_1_op;
  reg  [31:0]      buffer_1_pc;
  reg  [31:0]      buffer_1_addr;
  reg  [31:0]      buffer_1_data;
  reg  [2:0]       buffer_1_elemWidth;
  reg  [2:0]       buffer_1_sew;
  reg  [2:0]       buffer_1_emul_data;
  reg  [2:0]       buffer_1_emul_data_orig;
  reg  [2:0]       buffer_1_nfields;
  reg              buffer_1_strict;
  reg              buffer_2_store;
  reg  [4:0]       buffer_2_rd;
  reg  [4:0]       buffer_2_op;
  reg  [31:0]      buffer_2_pc;
  reg  [31:0]      buffer_2_addr;
  reg  [31:0]      buffer_2_data;
  reg  [2:0]       buffer_2_elemWidth;
  reg  [2:0]       buffer_2_sew;
  reg  [2:0]       buffer_2_emul_data;
  reg  [2:0]       buffer_2_emul_data_orig;
  reg  [2:0]       buffer_2_nfields;
  reg              buffer_2_strict;
  reg              buffer_3_store;
  reg  [4:0]       buffer_3_rd;
  reg  [4:0]       buffer_3_op;
  reg  [31:0]      buffer_3_pc;
  reg  [31:0]      buffer_3_addr;
  reg  [31:0]      buffer_3_data;
  reg  [2:0]       buffer_3_elemWidth;
  reg  [2:0]       buffer_3_sew;
  reg  [2:0]       buffer_3_emul_data;
  reg  [2:0]       buffer_3_emul_data_orig;
  reg  [2:0]       buffer_3_nfields;
  reg              buffer_3_strict;
  reg  [1:0]       enqPtr;
  reg  [1:0]       deqPtr;
  reg  [2:0]       nEnqueued;
  wire [3:0]       _GEN =
    {{buffer_3_store}, {buffer_2_store}, {buffer_1_store}, {buffer_0_store}};
  wire [3:0][4:0]  _GEN_0 = {{buffer_3_rd}, {buffer_2_rd}, {buffer_1_rd}, {buffer_0_rd}};
  wire [3:0][4:0]  _GEN_1 = {{buffer_3_op}, {buffer_2_op}, {buffer_1_op}, {buffer_0_op}};
  wire [3:0][31:0] _GEN_2 = {{buffer_3_pc}, {buffer_2_pc}, {buffer_1_pc}, {buffer_0_pc}};
  wire [3:0][31:0] _GEN_3 =
    {{buffer_3_addr}, {buffer_2_addr}, {buffer_1_addr}, {buffer_0_addr}};
  wire [3:0][31:0] _GEN_4 =
    {{buffer_3_data}, {buffer_2_data}, {buffer_1_data}, {buffer_0_data}};
  wire [3:0][2:0]  _GEN_5 =
    {{buffer_3_elemWidth},
     {buffer_2_elemWidth},
     {buffer_1_elemWidth},
     {buffer_0_elemWidth}};
  wire [3:0][2:0]  _GEN_6 =
    {{buffer_3_sew}, {buffer_2_sew}, {buffer_1_sew}, {buffer_0_sew}};
  wire [3:0][2:0]  _GEN_7 =
    {{buffer_3_emul_data},
     {buffer_2_emul_data},
     {buffer_1_emul_data},
     {buffer_0_emul_data}};
  wire [3:0][2:0]  _GEN_8 =
    {{buffer_3_emul_data_orig},
     {buffer_2_emul_data_orig},
     {buffer_1_emul_data_orig},
     {buffer_0_emul_data_orig}};
  wire [3:0][2:0]  _GEN_9 =
    {{buffer_3_nfields}, {buffer_2_nfields}, {buffer_1_nfields}, {buffer_0_nfields}};
  wire [3:0]       _GEN_10 =
    {{buffer_3_strict}, {buffer_2_strict}, {buffer_1_strict}, {buffer_0_strict}};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      buffer_0_store <= 1'h0;
      buffer_0_rd <= 5'h0;
      buffer_0_op <= 5'h0;
      buffer_0_pc <= 32'h0;
      buffer_0_addr <= 32'h0;
      buffer_0_data <= 32'h0;
      buffer_0_elemWidth <= 3'h0;
      buffer_0_sew <= 3'h0;
      buffer_0_emul_data <= 3'h0;
      buffer_0_emul_data_orig <= 3'h0;
      buffer_0_nfields <= 3'h0;
      buffer_0_strict <= 1'h0;
      buffer_1_store <= 1'h0;
      buffer_1_rd <= 5'h0;
      buffer_1_op <= 5'h0;
      buffer_1_pc <= 32'h0;
      buffer_1_addr <= 32'h0;
      buffer_1_data <= 32'h0;
      buffer_1_elemWidth <= 3'h0;
      buffer_1_sew <= 3'h0;
      buffer_1_emul_data <= 3'h0;
      buffer_1_emul_data_orig <= 3'h0;
      buffer_1_nfields <= 3'h0;
      buffer_1_strict <= 1'h0;
      buffer_2_store <= 1'h0;
      buffer_2_rd <= 5'h0;
      buffer_2_op <= 5'h0;
      buffer_2_pc <= 32'h0;
      buffer_2_addr <= 32'h0;
      buffer_2_data <= 32'h0;
      buffer_2_elemWidth <= 3'h0;
      buffer_2_sew <= 3'h0;
      buffer_2_emul_data <= 3'h0;
      buffer_2_emul_data_orig <= 3'h0;
      buffer_2_nfields <= 3'h0;
      buffer_2_strict <= 1'h0;
      buffer_3_store <= 1'h0;
      buffer_3_rd <= 5'h0;
      buffer_3_op <= 5'h0;
      buffer_3_pc <= 32'h0;
      buffer_3_addr <= 32'h0;
      buffer_3_data <= 32'h0;
      buffer_3_elemWidth <= 3'h0;
      buffer_3_sew <= 3'h0;
      buffer_3_emul_data <= 3'h0;
      buffer_3_emul_data_orig <= 3'h0;
      buffer_3_nfields <= 3'h0;
      buffer_3_strict <= 1'h0;
      enqPtr <= 2'h0;
      deqPtr <= 2'h0;
      nEnqueued <= 3'h0;
    end
    else begin
      if (io_enqValid & enqPtr == 2'h0) begin
        buffer_0_store <= io_enqData_0_store;
        buffer_0_rd <= io_enqData_0_rd;
        buffer_0_op <= io_enqData_0_op;
        buffer_0_pc <= io_enqData_0_pc;
        buffer_0_addr <= io_enqData_0_addr;
        buffer_0_data <= io_enqData_0_data;
        buffer_0_elemWidth <= io_enqData_0_elemWidth;
        buffer_0_sew <= io_enqData_0_sew;
        buffer_0_emul_data <= io_enqData_0_emul_data;
        buffer_0_emul_data_orig <= io_enqData_0_emul_data_orig;
        buffer_0_nfields <= io_enqData_0_nfields;
        buffer_0_strict <= io_enqData_0_strict;
      end
      if (io_enqValid & enqPtr == 2'h1) begin
        buffer_1_store <= io_enqData_0_store;
        buffer_1_rd <= io_enqData_0_rd;
        buffer_1_op <= io_enqData_0_op;
        buffer_1_pc <= io_enqData_0_pc;
        buffer_1_addr <= io_enqData_0_addr;
        buffer_1_data <= io_enqData_0_data;
        buffer_1_elemWidth <= io_enqData_0_elemWidth;
        buffer_1_sew <= io_enqData_0_sew;
        buffer_1_emul_data <= io_enqData_0_emul_data;
        buffer_1_emul_data_orig <= io_enqData_0_emul_data_orig;
        buffer_1_nfields <= io_enqData_0_nfields;
        buffer_1_strict <= io_enqData_0_strict;
      end
      if (io_enqValid & enqPtr == 2'h2) begin
        buffer_2_store <= io_enqData_0_store;
        buffer_2_rd <= io_enqData_0_rd;
        buffer_2_op <= io_enqData_0_op;
        buffer_2_pc <= io_enqData_0_pc;
        buffer_2_addr <= io_enqData_0_addr;
        buffer_2_data <= io_enqData_0_data;
        buffer_2_elemWidth <= io_enqData_0_elemWidth;
        buffer_2_sew <= io_enqData_0_sew;
        buffer_2_emul_data <= io_enqData_0_emul_data;
        buffer_2_emul_data_orig <= io_enqData_0_emul_data_orig;
        buffer_2_nfields <= io_enqData_0_nfields;
        buffer_2_strict <= io_enqData_0_strict;
      end
      if (io_enqValid & (&enqPtr)) begin
        buffer_3_store <= io_enqData_0_store;
        buffer_3_rd <= io_enqData_0_rd;
        buffer_3_op <= io_enqData_0_op;
        buffer_3_pc <= io_enqData_0_pc;
        buffer_3_addr <= io_enqData_0_addr;
        buffer_3_data <= io_enqData_0_data;
        buffer_3_elemWidth <= io_enqData_0_elemWidth;
        buffer_3_sew <= io_enqData_0_sew;
        buffer_3_emul_data <= io_enqData_0_emul_data;
        buffer_3_emul_data_orig <= io_enqData_0_emul_data_orig;
        buffer_3_nfields <= io_enqData_0_nfields;
        buffer_3_strict <= io_enqData_0_strict;
      end
      enqPtr <= io_flush ? 2'h0 : enqPtr + {1'h0, io_enqValid};
      deqPtr <= io_flush ? 2'h0 : deqPtr + {1'h0, io_deqReady};
      nEnqueued <=
        io_flush ? 3'h0 : nEnqueued + {2'h0, io_enqValid} - {2'h0, io_deqReady};
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:15];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h10; i += 5'h1) begin
          _RANDOM[i[3:0]] = `RANDOM;
        end
        buffer_0_store = _RANDOM[4'h0][0];
        buffer_0_rd = _RANDOM[4'h0][5:1];
        buffer_0_op = _RANDOM[4'h0][10:6];
        buffer_0_pc = {_RANDOM[4'h0][31:11], _RANDOM[4'h1][10:0]};
        buffer_0_addr = {_RANDOM[4'h1][31:11], _RANDOM[4'h2][10:0]};
        buffer_0_data = {_RANDOM[4'h2][31:11], _RANDOM[4'h3][10:0]};
        buffer_0_elemWidth = _RANDOM[4'h3][13:11];
        buffer_0_sew = _RANDOM[4'h3][16:14];
        buffer_0_emul_data = _RANDOM[4'h3][19:17];
        buffer_0_emul_data_orig = _RANDOM[4'h3][22:20];
        buffer_0_nfields = _RANDOM[4'h3][25:23];
        buffer_0_strict = _RANDOM[4'h3][26];
        buffer_1_store = _RANDOM[4'h3][27];
        buffer_1_rd = {_RANDOM[4'h3][31:28], _RANDOM[4'h4][0]};
        buffer_1_op = _RANDOM[4'h4][5:1];
        buffer_1_pc = {_RANDOM[4'h4][31:6], _RANDOM[4'h5][5:0]};
        buffer_1_addr = {_RANDOM[4'h5][31:6], _RANDOM[4'h6][5:0]};
        buffer_1_data = {_RANDOM[4'h6][31:6], _RANDOM[4'h7][5:0]};
        buffer_1_elemWidth = _RANDOM[4'h7][8:6];
        buffer_1_sew = _RANDOM[4'h7][11:9];
        buffer_1_emul_data = _RANDOM[4'h7][14:12];
        buffer_1_emul_data_orig = _RANDOM[4'h7][17:15];
        buffer_1_nfields = _RANDOM[4'h7][20:18];
        buffer_1_strict = _RANDOM[4'h7][21];
        buffer_2_store = _RANDOM[4'h7][22];
        buffer_2_rd = _RANDOM[4'h7][27:23];
        buffer_2_op = {_RANDOM[4'h7][31:28], _RANDOM[4'h8][0]};
        buffer_2_pc = {_RANDOM[4'h8][31:1], _RANDOM[4'h9][0]};
        buffer_2_addr = {_RANDOM[4'h9][31:1], _RANDOM[4'hA][0]};
        buffer_2_data = {_RANDOM[4'hA][31:1], _RANDOM[4'hB][0]};
        buffer_2_elemWidth = _RANDOM[4'hB][3:1];
        buffer_2_sew = _RANDOM[4'hB][6:4];
        buffer_2_emul_data = _RANDOM[4'hB][9:7];
        buffer_2_emul_data_orig = _RANDOM[4'hB][12:10];
        buffer_2_nfields = _RANDOM[4'hB][15:13];
        buffer_2_strict = _RANDOM[4'hB][16];
        buffer_3_store = _RANDOM[4'hB][17];
        buffer_3_rd = _RANDOM[4'hB][22:18];
        buffer_3_op = _RANDOM[4'hB][27:23];
        buffer_3_pc = {_RANDOM[4'hB][31:28], _RANDOM[4'hC][27:0]};
        buffer_3_addr = {_RANDOM[4'hC][31:28], _RANDOM[4'hD][27:0]};
        buffer_3_data = {_RANDOM[4'hD][31:28], _RANDOM[4'hE][27:0]};
        buffer_3_elemWidth = _RANDOM[4'hE][30:28];
        buffer_3_sew = {_RANDOM[4'hE][31], _RANDOM[4'hF][1:0]};
        buffer_3_emul_data = _RANDOM[4'hF][4:2];
        buffer_3_emul_data_orig = _RANDOM[4'hF][7:5];
        buffer_3_nfields = _RANDOM[4'hF][10:8];
        buffer_3_strict = _RANDOM[4'hF][11];
        enqPtr = _RANDOM[4'hF][13:12];
        deqPtr = _RANDOM[4'hF][15:14];
        nEnqueued = _RANDOM[4'hF][18:16];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        buffer_0_store = 1'h0;
        buffer_0_rd = 5'h0;
        buffer_0_op = 5'h0;
        buffer_0_pc = 32'h0;
        buffer_0_addr = 32'h0;
        buffer_0_data = 32'h0;
        buffer_0_elemWidth = 3'h0;
        buffer_0_sew = 3'h0;
        buffer_0_emul_data = 3'h0;
        buffer_0_emul_data_orig = 3'h0;
        buffer_0_nfields = 3'h0;
        buffer_0_strict = 1'h0;
        buffer_1_store = 1'h0;
        buffer_1_rd = 5'h0;
        buffer_1_op = 5'h0;
        buffer_1_pc = 32'h0;
        buffer_1_addr = 32'h0;
        buffer_1_data = 32'h0;
        buffer_1_elemWidth = 3'h0;
        buffer_1_sew = 3'h0;
        buffer_1_emul_data = 3'h0;
        buffer_1_emul_data_orig = 3'h0;
        buffer_1_nfields = 3'h0;
        buffer_1_strict = 1'h0;
        buffer_2_store = 1'h0;
        buffer_2_rd = 5'h0;
        buffer_2_op = 5'h0;
        buffer_2_pc = 32'h0;
        buffer_2_addr = 32'h0;
        buffer_2_data = 32'h0;
        buffer_2_elemWidth = 3'h0;
        buffer_2_sew = 3'h0;
        buffer_2_emul_data = 3'h0;
        buffer_2_emul_data_orig = 3'h0;
        buffer_2_nfields = 3'h0;
        buffer_2_strict = 1'h0;
        buffer_3_store = 1'h0;
        buffer_3_rd = 5'h0;
        buffer_3_op = 5'h0;
        buffer_3_pc = 32'h0;
        buffer_3_addr = 32'h0;
        buffer_3_data = 32'h0;
        buffer_3_elemWidth = 3'h0;
        buffer_3_sew = 3'h0;
        buffer_3_emul_data = 3'h0;
        buffer_3_emul_data_orig = 3'h0;
        buffer_3_nfields = 3'h0;
        buffer_3_strict = 1'h0;
        enqPtr = 2'h0;
        deqPtr = 2'h0;
        nEnqueued = 3'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_nEnqueued = nEnqueued;
  assign io_nSpace = 3'h4 - nEnqueued;
  assign io_dataOut_0_store = _GEN[deqPtr];
  assign io_dataOut_0_rd = _GEN_0[deqPtr];
  assign io_dataOut_0_op = _GEN_1[deqPtr];
  assign io_dataOut_0_pc = _GEN_2[deqPtr];
  assign io_dataOut_0_addr = _GEN_3[deqPtr];
  assign io_dataOut_0_data = _GEN_4[deqPtr];
  assign io_dataOut_0_elemWidth = _GEN_5[deqPtr];
  assign io_dataOut_0_sew = _GEN_6[deqPtr];
  assign io_dataOut_0_emul_data = _GEN_7[deqPtr];
  assign io_dataOut_0_emul_data_orig = _GEN_8[deqPtr];
  assign io_dataOut_0_nfields = _GEN_9[deqPtr];
  assign io_dataOut_0_strict = _GEN_10[deqPtr];
endmodule

