// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module CircularBufferMulti_2(
  input         clock,
                reset,
  input  [2:0]  io_enqValid,
  input  [31:0] io_enqData_0_addr,
  input  [6:0]  io_enqData_0_idx,
  input         io_enqData_0_trap,
                io_enqData_0_isControlFlow,
                io_enqData_0_isBranch,
                io_enqData_0_isVector,
                io_enqData_0_linkOk,
                io_enqData_0_isEcall,
                io_enqData_0_isMpause,
  input  [31:0] io_enqData_1_addr,
  input  [6:0]  io_enqData_1_idx,
  input         io_enqData_1_trap,
                io_enqData_1_isControlFlow,
                io_enqData_1_isBranch,
                io_enqData_1_isVector,
                io_enqData_1_linkOk,
                io_enqData_1_isEcall,
                io_enqData_1_isMpause,
  input  [31:0] io_enqData_2_addr,
  input  [6:0]  io_enqData_2_idx,
  input         io_enqData_2_trap,
                io_enqData_2_isControlFlow,
                io_enqData_2_isBranch,
                io_enqData_2_isVector,
                io_enqData_2_linkOk,
                io_enqData_2_isEcall,
                io_enqData_2_isMpause,
  input  [31:0] io_enqData_3_addr,
  input  [6:0]  io_enqData_3_idx,
  input         io_enqData_3_trap,
                io_enqData_3_isControlFlow,
                io_enqData_3_isBranch,
                io_enqData_3_isVector,
                io_enqData_3_linkOk,
                io_enqData_3_isEcall,
                io_enqData_3_isMpause,
  output [2:0]  io_nEnqueued,
                io_nSpace,
  output [31:0] io_dataOut_0_addr,
  output [6:0]  io_dataOut_0_idx,
  output        io_dataOut_0_trap,
                io_dataOut_0_isControlFlow,
                io_dataOut_0_isBranch,
                io_dataOut_0_isVector,
                io_dataOut_0_linkOk,
                io_dataOut_0_isEcall,
                io_dataOut_0_isMpause,
  output [31:0] io_dataOut_1_addr,
  output [6:0]  io_dataOut_1_idx,
  output        io_dataOut_1_trap,
                io_dataOut_1_isControlFlow,
                io_dataOut_1_isBranch,
                io_dataOut_1_isVector,
                io_dataOut_1_linkOk,
                io_dataOut_1_isEcall,
                io_dataOut_1_isMpause,
  output [31:0] io_dataOut_2_addr,
  output [6:0]  io_dataOut_2_idx,
  output        io_dataOut_2_trap,
                io_dataOut_2_isControlFlow,
                io_dataOut_2_isBranch,
                io_dataOut_2_isVector,
                io_dataOut_2_linkOk,
                io_dataOut_2_isEcall,
                io_dataOut_2_isMpause,
  output [31:0] io_dataOut_3_addr,
  output [6:0]  io_dataOut_3_idx,
  output        io_dataOut_3_trap,
                io_dataOut_3_isControlFlow,
                io_dataOut_3_isBranch,
                io_dataOut_3_isVector,
                io_dataOut_3_linkOk,
                io_dataOut_3_isEcall,
                io_dataOut_3_isMpause,
  input  [2:0]  io_deqReady,
  input         io_flush
);

  reg  [31:0]      buffer_0_addr;
  reg  [6:0]       buffer_0_idx;
  reg              buffer_0_trap;
  reg              buffer_0_isControlFlow;
  reg              buffer_0_isBranch;
  reg              buffer_0_isVector;
  reg              buffer_0_linkOk;
  reg              buffer_0_isEcall;
  reg              buffer_0_isMpause;
  reg  [31:0]      buffer_1_addr;
  reg  [6:0]       buffer_1_idx;
  reg              buffer_1_trap;
  reg              buffer_1_isControlFlow;
  reg              buffer_1_isBranch;
  reg              buffer_1_isVector;
  reg              buffer_1_linkOk;
  reg              buffer_1_isEcall;
  reg              buffer_1_isMpause;
  reg  [31:0]      buffer_2_addr;
  reg  [6:0]       buffer_2_idx;
  reg              buffer_2_trap;
  reg              buffer_2_isControlFlow;
  reg              buffer_2_isBranch;
  reg              buffer_2_isVector;
  reg              buffer_2_linkOk;
  reg              buffer_2_isEcall;
  reg              buffer_2_isMpause;
  reg  [31:0]      buffer_3_addr;
  reg  [6:0]       buffer_3_idx;
  reg              buffer_3_trap;
  reg              buffer_3_isControlFlow;
  reg              buffer_3_isBranch;
  reg              buffer_3_isVector;
  reg              buffer_3_linkOk;
  reg              buffer_3_isEcall;
  reg              buffer_3_isMpause;
  reg  [1:0]       enqPtr;
  reg  [1:0]       deqPtr;
  reg  [2:0]       nEnqueued;
  wire [3:0][31:0] _GEN =
    {{buffer_3_addr}, {buffer_2_addr}, {buffer_1_addr}, {buffer_0_addr}};
  wire [3:0][6:0]  _GEN_0 =
    {{buffer_3_idx}, {buffer_2_idx}, {buffer_1_idx}, {buffer_0_idx}};
  wire [3:0]       _GEN_1 =
    {{buffer_3_trap}, {buffer_2_trap}, {buffer_1_trap}, {buffer_0_trap}};
  wire [3:0]       _GEN_2 =
    {{buffer_3_isControlFlow},
     {buffer_2_isControlFlow},
     {buffer_1_isControlFlow},
     {buffer_0_isControlFlow}};
  wire [3:0]       _GEN_3 =
    {{buffer_3_isBranch}, {buffer_2_isBranch}, {buffer_1_isBranch}, {buffer_0_isBranch}};
  wire [3:0]       _GEN_4 =
    {{buffer_3_isVector}, {buffer_2_isVector}, {buffer_1_isVector}, {buffer_0_isVector}};
  wire [3:0]       _GEN_5 =
    {{buffer_3_linkOk}, {buffer_2_linkOk}, {buffer_1_linkOk}, {buffer_0_linkOk}};
  wire [3:0]       _GEN_6 =
    {{buffer_3_isEcall}, {buffer_2_isEcall}, {buffer_1_isEcall}, {buffer_0_isEcall}};
  wire [3:0]       _GEN_7 =
    {{buffer_3_isMpause}, {buffer_2_isMpause}, {buffer_1_isMpause}, {buffer_0_isMpause}};
  wire [1:0]       _readIdx_T_2 = deqPtr + 2'h1;
  wire [1:0]       _readIdx_T_4 = deqPtr - 2'h2;
  wire [1:0]       _readIdx_T_6 = deqPtr - 2'h1;
  wire             matches_0 = (|io_enqValid) & enqPtr == 2'h0;
  wire [1:0]       _matches_slotIdx_T_26 = enqPtr + 2'h1;
  wire             matches_1 = (|(io_enqValid[2:1])) & _matches_slotIdx_T_26 == 2'h0;
  wire [1:0]       _matches_slotIdx_T_28 = enqPtr - 2'h2;
  wire             _matches_T_42 = io_enqValid > 3'h2;
  wire             matches_2 = _matches_T_42 & _matches_slotIdx_T_28 == 2'h0;
  wire [1:0]       _matches_slotIdx_T_30 = enqPtr - 2'h1;
  wire             matches_3 = io_enqValid[2] & _matches_slotIdx_T_30 == 2'h0;
  wire             matches_1_0 = (|io_enqValid) & enqPtr == 2'h1;
  wire             matches_1_1 = (|(io_enqValid[2:1])) & _matches_slotIdx_T_26 == 2'h1;
  wire             matches_1_2 = _matches_T_42 & _matches_slotIdx_T_28 == 2'h1;
  wire             matches_1_3 = io_enqValid[2] & _matches_slotIdx_T_30 == 2'h1;
  wire             matches_2_0 = (|io_enqValid) & enqPtr == 2'h2;
  wire             matches_2_1 = (|(io_enqValid[2:1])) & _matches_slotIdx_T_26 == 2'h2;
  wire             matches_2_2 = _matches_T_42 & _matches_slotIdx_T_28 == 2'h2;
  wire             matches_2_3 = io_enqValid[2] & _matches_slotIdx_T_30 == 2'h2;
  wire             matches_3_0 = (|io_enqValid) & (&enqPtr);
  wire             matches_3_1 = (|(io_enqValid[2:1])) & (&_matches_slotIdx_T_26);
  wire             matches_3_2 = _matches_T_42 & (&_matches_slotIdx_T_28);
  wire             matches_3_3 = io_enqValid[2] & (&_matches_slotIdx_T_30);
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      buffer_0_addr <= 32'h0;
      buffer_0_idx <= 7'h0;
      buffer_0_trap <= 1'h0;
      buffer_0_isControlFlow <= 1'h0;
      buffer_0_isBranch <= 1'h0;
      buffer_0_isVector <= 1'h0;
      buffer_0_linkOk <= 1'h0;
      buffer_0_isEcall <= 1'h0;
      buffer_0_isMpause <= 1'h0;
      buffer_1_addr <= 32'h0;
      buffer_1_idx <= 7'h0;
      buffer_1_trap <= 1'h0;
      buffer_1_isControlFlow <= 1'h0;
      buffer_1_isBranch <= 1'h0;
      buffer_1_isVector <= 1'h0;
      buffer_1_linkOk <= 1'h0;
      buffer_1_isEcall <= 1'h0;
      buffer_1_isMpause <= 1'h0;
      buffer_2_addr <= 32'h0;
      buffer_2_idx <= 7'h0;
      buffer_2_trap <= 1'h0;
      buffer_2_isControlFlow <= 1'h0;
      buffer_2_isBranch <= 1'h0;
      buffer_2_isVector <= 1'h0;
      buffer_2_linkOk <= 1'h0;
      buffer_2_isEcall <= 1'h0;
      buffer_2_isMpause <= 1'h0;
      buffer_3_addr <= 32'h0;
      buffer_3_idx <= 7'h0;
      buffer_3_trap <= 1'h0;
      buffer_3_isControlFlow <= 1'h0;
      buffer_3_isBranch <= 1'h0;
      buffer_3_isVector <= 1'h0;
      buffer_3_linkOk <= 1'h0;
      buffer_3_isEcall <= 1'h0;
      buffer_3_isMpause <= 1'h0;
      enqPtr <= 2'h0;
      deqPtr <= 2'h0;
      nEnqueued <= 3'h0;
    end
    else begin
      if (|{matches_3, matches_2, matches_1, matches_0}) begin
        buffer_0_addr <=
          (matches_0 ? io_enqData_0_addr : 32'h0)
          | (matches_1 ? io_enqData_1_addr : 32'h0)
          | (matches_2 ? io_enqData_2_addr : 32'h0)
          | (matches_3 ? io_enqData_3_addr : 32'h0);
        buffer_0_idx <=
          (matches_0 ? io_enqData_0_idx : 7'h0) | (matches_1 ? io_enqData_1_idx : 7'h0)
          | (matches_2 ? io_enqData_2_idx : 7'h0) | (matches_3 ? io_enqData_3_idx : 7'h0);
        buffer_0_trap <=
          matches_0 & io_enqData_0_trap | matches_1 & io_enqData_1_trap | matches_2
          & io_enqData_2_trap | matches_3 & io_enqData_3_trap;
        buffer_0_isControlFlow <=
          matches_0 & io_enqData_0_isControlFlow | matches_1 & io_enqData_1_isControlFlow
          | matches_2 & io_enqData_2_isControlFlow | matches_3
          & io_enqData_3_isControlFlow;
        buffer_0_isBranch <=
          matches_0 & io_enqData_0_isBranch | matches_1 & io_enqData_1_isBranch
          | matches_2 & io_enqData_2_isBranch | matches_3 & io_enqData_3_isBranch;
        buffer_0_isVector <=
          matches_0 & io_enqData_0_isVector | matches_1 & io_enqData_1_isVector
          | matches_2 & io_enqData_2_isVector | matches_3 & io_enqData_3_isVector;
        buffer_0_linkOk <=
          matches_0 & io_enqData_0_linkOk | matches_1 & io_enqData_1_linkOk | matches_2
          & io_enqData_2_linkOk | matches_3 & io_enqData_3_linkOk;
        buffer_0_isEcall <=
          matches_0 & io_enqData_0_isEcall | matches_1 & io_enqData_1_isEcall | matches_2
          & io_enqData_2_isEcall | matches_3 & io_enqData_3_isEcall;
        buffer_0_isMpause <=
          matches_0 & io_enqData_0_isMpause | matches_1 & io_enqData_1_isMpause
          | matches_2 & io_enqData_2_isMpause | matches_3 & io_enqData_3_isMpause;
      end
      if (|{matches_1_3, matches_1_2, matches_1_1, matches_1_0}) begin
        buffer_1_addr <=
          (matches_1_0 ? io_enqData_0_addr : 32'h0)
          | (matches_1_1 ? io_enqData_1_addr : 32'h0)
          | (matches_1_2 ? io_enqData_2_addr : 32'h0)
          | (matches_1_3 ? io_enqData_3_addr : 32'h0);
        buffer_1_idx <=
          (matches_1_0 ? io_enqData_0_idx : 7'h0)
          | (matches_1_1 ? io_enqData_1_idx : 7'h0)
          | (matches_1_2 ? io_enqData_2_idx : 7'h0)
          | (matches_1_3 ? io_enqData_3_idx : 7'h0);
        buffer_1_trap <=
          matches_1_0 & io_enqData_0_trap | matches_1_1 & io_enqData_1_trap | matches_1_2
          & io_enqData_2_trap | matches_1_3 & io_enqData_3_trap;
        buffer_1_isControlFlow <=
          matches_1_0 & io_enqData_0_isControlFlow | matches_1_1
          & io_enqData_1_isControlFlow | matches_1_2 & io_enqData_2_isControlFlow
          | matches_1_3 & io_enqData_3_isControlFlow;
        buffer_1_isBranch <=
          matches_1_0 & io_enqData_0_isBranch | matches_1_1 & io_enqData_1_isBranch
          | matches_1_2 & io_enqData_2_isBranch | matches_1_3 & io_enqData_3_isBranch;
        buffer_1_isVector <=
          matches_1_0 & io_enqData_0_isVector | matches_1_1 & io_enqData_1_isVector
          | matches_1_2 & io_enqData_2_isVector | matches_1_3 & io_enqData_3_isVector;
        buffer_1_linkOk <=
          matches_1_0 & io_enqData_0_linkOk | matches_1_1 & io_enqData_1_linkOk
          | matches_1_2 & io_enqData_2_linkOk | matches_1_3 & io_enqData_3_linkOk;
        buffer_1_isEcall <=
          matches_1_0 & io_enqData_0_isEcall | matches_1_1 & io_enqData_1_isEcall
          | matches_1_2 & io_enqData_2_isEcall | matches_1_3 & io_enqData_3_isEcall;
        buffer_1_isMpause <=
          matches_1_0 & io_enqData_0_isMpause | matches_1_1 & io_enqData_1_isMpause
          | matches_1_2 & io_enqData_2_isMpause | matches_1_3 & io_enqData_3_isMpause;
      end
      if (|{matches_2_3, matches_2_2, matches_2_1, matches_2_0}) begin
        buffer_2_addr <=
          (matches_2_0 ? io_enqData_0_addr : 32'h0)
          | (matches_2_1 ? io_enqData_1_addr : 32'h0)
          | (matches_2_2 ? io_enqData_2_addr : 32'h0)
          | (matches_2_3 ? io_enqData_3_addr : 32'h0);
        buffer_2_idx <=
          (matches_2_0 ? io_enqData_0_idx : 7'h0)
          | (matches_2_1 ? io_enqData_1_idx : 7'h0)
          | (matches_2_2 ? io_enqData_2_idx : 7'h0)
          | (matches_2_3 ? io_enqData_3_idx : 7'h0);
        buffer_2_trap <=
          matches_2_0 & io_enqData_0_trap | matches_2_1 & io_enqData_1_trap | matches_2_2
          & io_enqData_2_trap | matches_2_3 & io_enqData_3_trap;
        buffer_2_isControlFlow <=
          matches_2_0 & io_enqData_0_isControlFlow | matches_2_1
          & io_enqData_1_isControlFlow | matches_2_2 & io_enqData_2_isControlFlow
          | matches_2_3 & io_enqData_3_isControlFlow;
        buffer_2_isBranch <=
          matches_2_0 & io_enqData_0_isBranch | matches_2_1 & io_enqData_1_isBranch
          | matches_2_2 & io_enqData_2_isBranch | matches_2_3 & io_enqData_3_isBranch;
        buffer_2_isVector <=
          matches_2_0 & io_enqData_0_isVector | matches_2_1 & io_enqData_1_isVector
          | matches_2_2 & io_enqData_2_isVector | matches_2_3 & io_enqData_3_isVector;
        buffer_2_linkOk <=
          matches_2_0 & io_enqData_0_linkOk | matches_2_1 & io_enqData_1_linkOk
          | matches_2_2 & io_enqData_2_linkOk | matches_2_3 & io_enqData_3_linkOk;
        buffer_2_isEcall <=
          matches_2_0 & io_enqData_0_isEcall | matches_2_1 & io_enqData_1_isEcall
          | matches_2_2 & io_enqData_2_isEcall | matches_2_3 & io_enqData_3_isEcall;
        buffer_2_isMpause <=
          matches_2_0 & io_enqData_0_isMpause | matches_2_1 & io_enqData_1_isMpause
          | matches_2_2 & io_enqData_2_isMpause | matches_2_3 & io_enqData_3_isMpause;
      end
      if (|{matches_3_3, matches_3_2, matches_3_1, matches_3_0}) begin
        buffer_3_addr <=
          (matches_3_0 ? io_enqData_0_addr : 32'h0)
          | (matches_3_1 ? io_enqData_1_addr : 32'h0)
          | (matches_3_2 ? io_enqData_2_addr : 32'h0)
          | (matches_3_3 ? io_enqData_3_addr : 32'h0);
        buffer_3_idx <=
          (matches_3_0 ? io_enqData_0_idx : 7'h0)
          | (matches_3_1 ? io_enqData_1_idx : 7'h0)
          | (matches_3_2 ? io_enqData_2_idx : 7'h0)
          | (matches_3_3 ? io_enqData_3_idx : 7'h0);
        buffer_3_trap <=
          matches_3_0 & io_enqData_0_trap | matches_3_1 & io_enqData_1_trap | matches_3_2
          & io_enqData_2_trap | matches_3_3 & io_enqData_3_trap;
        buffer_3_isControlFlow <=
          matches_3_0 & io_enqData_0_isControlFlow | matches_3_1
          & io_enqData_1_isControlFlow | matches_3_2 & io_enqData_2_isControlFlow
          | matches_3_3 & io_enqData_3_isControlFlow;
        buffer_3_isBranch <=
          matches_3_0 & io_enqData_0_isBranch | matches_3_1 & io_enqData_1_isBranch
          | matches_3_2 & io_enqData_2_isBranch | matches_3_3 & io_enqData_3_isBranch;
        buffer_3_isVector <=
          matches_3_0 & io_enqData_0_isVector | matches_3_1 & io_enqData_1_isVector
          | matches_3_2 & io_enqData_2_isVector | matches_3_3 & io_enqData_3_isVector;
        buffer_3_linkOk <=
          matches_3_0 & io_enqData_0_linkOk | matches_3_1 & io_enqData_1_linkOk
          | matches_3_2 & io_enqData_2_linkOk | matches_3_3 & io_enqData_3_linkOk;
        buffer_3_isEcall <=
          matches_3_0 & io_enqData_0_isEcall | matches_3_1 & io_enqData_1_isEcall
          | matches_3_2 & io_enqData_2_isEcall | matches_3_3 & io_enqData_3_isEcall;
        buffer_3_isMpause <=
          matches_3_0 & io_enqData_0_isMpause | matches_3_1 & io_enqData_1_isMpause
          | matches_3_2 & io_enqData_2_isMpause | matches_3_3 & io_enqData_3_isMpause;
      end
      enqPtr <= io_flush ? 2'h0 : enqPtr + io_enqValid[1:0];
      deqPtr <= io_flush ? 2'h0 : deqPtr + io_deqReady[1:0];
      nEnqueued <= io_flush ? 3'h0 : nEnqueued + io_enqValid - io_deqReady;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:5];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        buffer_0_addr = _RANDOM[3'h0];
        buffer_0_idx = _RANDOM[3'h1][6:0];
        buffer_0_trap = _RANDOM[3'h1][7];
        buffer_0_isControlFlow = _RANDOM[3'h1][8];
        buffer_0_isBranch = _RANDOM[3'h1][9];
        buffer_0_isVector = _RANDOM[3'h1][10];
        buffer_0_linkOk = _RANDOM[3'h1][11];
        buffer_0_isEcall = _RANDOM[3'h1][12];
        buffer_0_isMpause = _RANDOM[3'h1][13];
        buffer_1_addr = {_RANDOM[3'h1][31:14], _RANDOM[3'h2][13:0]};
        buffer_1_idx = _RANDOM[3'h2][20:14];
        buffer_1_trap = _RANDOM[3'h2][21];
        buffer_1_isControlFlow = _RANDOM[3'h2][22];
        buffer_1_isBranch = _RANDOM[3'h2][23];
        buffer_1_isVector = _RANDOM[3'h2][24];
        buffer_1_linkOk = _RANDOM[3'h2][25];
        buffer_1_isEcall = _RANDOM[3'h2][26];
        buffer_1_isMpause = _RANDOM[3'h2][27];
        buffer_2_addr = {_RANDOM[3'h2][31:28], _RANDOM[3'h3][27:0]};
        buffer_2_idx = {_RANDOM[3'h3][31:28], _RANDOM[3'h4][2:0]};
        buffer_2_trap = _RANDOM[3'h4][3];
        buffer_2_isControlFlow = _RANDOM[3'h4][4];
        buffer_2_isBranch = _RANDOM[3'h4][5];
        buffer_2_isVector = _RANDOM[3'h4][6];
        buffer_2_linkOk = _RANDOM[3'h4][7];
        buffer_2_isEcall = _RANDOM[3'h4][8];
        buffer_2_isMpause = _RANDOM[3'h4][9];
        buffer_3_addr = {_RANDOM[3'h4][31:10], _RANDOM[3'h5][9:0]};
        buffer_3_idx = _RANDOM[3'h5][16:10];
        buffer_3_trap = _RANDOM[3'h5][17];
        buffer_3_isControlFlow = _RANDOM[3'h5][18];
        buffer_3_isBranch = _RANDOM[3'h5][19];
        buffer_3_isVector = _RANDOM[3'h5][20];
        buffer_3_linkOk = _RANDOM[3'h5][21];
        buffer_3_isEcall = _RANDOM[3'h5][22];
        buffer_3_isMpause = _RANDOM[3'h5][23];
        enqPtr = _RANDOM[3'h5][25:24];
        deqPtr = _RANDOM[3'h5][27:26];
        nEnqueued = _RANDOM[3'h5][30:28];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        buffer_0_addr = 32'h0;
        buffer_0_idx = 7'h0;
        buffer_0_trap = 1'h0;
        buffer_0_isControlFlow = 1'h0;
        buffer_0_isBranch = 1'h0;
        buffer_0_isVector = 1'h0;
        buffer_0_linkOk = 1'h0;
        buffer_0_isEcall = 1'h0;
        buffer_0_isMpause = 1'h0;
        buffer_1_addr = 32'h0;
        buffer_1_idx = 7'h0;
        buffer_1_trap = 1'h0;
        buffer_1_isControlFlow = 1'h0;
        buffer_1_isBranch = 1'h0;
        buffer_1_isVector = 1'h0;
        buffer_1_linkOk = 1'h0;
        buffer_1_isEcall = 1'h0;
        buffer_1_isMpause = 1'h0;
        buffer_2_addr = 32'h0;
        buffer_2_idx = 7'h0;
        buffer_2_trap = 1'h0;
        buffer_2_isControlFlow = 1'h0;
        buffer_2_isBranch = 1'h0;
        buffer_2_isVector = 1'h0;
        buffer_2_linkOk = 1'h0;
        buffer_2_isEcall = 1'h0;
        buffer_2_isMpause = 1'h0;
        buffer_3_addr = 32'h0;
        buffer_3_idx = 7'h0;
        buffer_3_trap = 1'h0;
        buffer_3_isControlFlow = 1'h0;
        buffer_3_isBranch = 1'h0;
        buffer_3_isVector = 1'h0;
        buffer_3_linkOk = 1'h0;
        buffer_3_isEcall = 1'h0;
        buffer_3_isMpause = 1'h0;
        enqPtr = 2'h0;
        deqPtr = 2'h0;
        nEnqueued = 3'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_nEnqueued = nEnqueued;
  assign io_nSpace = 3'h4 - nEnqueued;
  assign io_dataOut_0_addr = _GEN[deqPtr];
  assign io_dataOut_0_idx = _GEN_0[deqPtr];
  assign io_dataOut_0_trap = _GEN_1[deqPtr];
  assign io_dataOut_0_isControlFlow = _GEN_2[deqPtr];
  assign io_dataOut_0_isBranch = _GEN_3[deqPtr];
  assign io_dataOut_0_isVector = _GEN_4[deqPtr];
  assign io_dataOut_0_linkOk = _GEN_5[deqPtr];
  assign io_dataOut_0_isEcall = _GEN_6[deqPtr];
  assign io_dataOut_0_isMpause = _GEN_7[deqPtr];
  assign io_dataOut_1_addr = _GEN[_readIdx_T_2];
  assign io_dataOut_1_idx = _GEN_0[_readIdx_T_2];
  assign io_dataOut_1_trap = _GEN_1[_readIdx_T_2];
  assign io_dataOut_1_isControlFlow = _GEN_2[_readIdx_T_2];
  assign io_dataOut_1_isBranch = _GEN_3[_readIdx_T_2];
  assign io_dataOut_1_isVector = _GEN_4[_readIdx_T_2];
  assign io_dataOut_1_linkOk = _GEN_5[_readIdx_T_2];
  assign io_dataOut_1_isEcall = _GEN_6[_readIdx_T_2];
  assign io_dataOut_1_isMpause = _GEN_7[_readIdx_T_2];
  assign io_dataOut_2_addr = _GEN[_readIdx_T_4];
  assign io_dataOut_2_idx = _GEN_0[_readIdx_T_4];
  assign io_dataOut_2_trap = _GEN_1[_readIdx_T_4];
  assign io_dataOut_2_isControlFlow = _GEN_2[_readIdx_T_4];
  assign io_dataOut_2_isBranch = _GEN_3[_readIdx_T_4];
  assign io_dataOut_2_isVector = _GEN_4[_readIdx_T_4];
  assign io_dataOut_2_linkOk = _GEN_5[_readIdx_T_4];
  assign io_dataOut_2_isEcall = _GEN_6[_readIdx_T_4];
  assign io_dataOut_2_isMpause = _GEN_7[_readIdx_T_4];
  assign io_dataOut_3_addr = _GEN[_readIdx_T_6];
  assign io_dataOut_3_idx = _GEN_0[_readIdx_T_6];
  assign io_dataOut_3_trap = _GEN_1[_readIdx_T_6];
  assign io_dataOut_3_isControlFlow = _GEN_2[_readIdx_T_6];
  assign io_dataOut_3_isBranch = _GEN_3[_readIdx_T_6];
  assign io_dataOut_3_isVector = _GEN_4[_readIdx_T_6];
  assign io_dataOut_3_linkOk = _GEN_5[_readIdx_T_6];
  assign io_dataOut_3_isEcall = _GEN_6[_readIdx_T_6];
  assign io_dataOut_3_isMpause = _GEN_7[_readIdx_T_6];
endmodule

