// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
module DispatchV2(
  input         clock,
                reset,
                io_halted,
                io_lsuActive,
  input  [31:0] io_scoreboard_regd,
                io_scoreboard_comb,
  input         io_branchTaken,
  output        io_csrFault_0,
                io_jalFault_0,
                io_jalrFault_0,
                io_bxxFault_0,
                io_undefFault_0,
                io_rvvFault_0,
  output [31:0] io_bruTarget_0,
  input  [31:0] io_jalrTarget_0_data,
  input         io_interlock,
  output        io_inst_0_ready,
  input         io_inst_0_valid,
  input  [31:0] io_inst_0_bits_addr,
                io_inst_0_bits_inst,
  input         io_inst_0_bits_brchFwd,
  output        io_rs1Read_0_valid,
  output [4:0]  io_rs1Read_0_addr,
  output        io_rs1Set_0_valid,
  output [31:0] io_rs1Set_0_value,
  output        io_rs2Read_0_valid,
  output [4:0]  io_rs2Read_0_addr,
  output        io_rs2Set_0_valid,
  output [31:0] io_rs2Set_0_value,
  output        io_rdMark_0_valid,
  output [4:0]  io_rdMark_0_addr,
  output        io_busRead_0_immen,
  output [31:0] io_busRead_0_immed,
  output        io_rvvRdMark_0_valid,
  output [4:0]  io_rvvRdMark_0_addr,
  output        io_alu_0_valid,
  output [4:0]  io_alu_0_bits_addr,
                io_alu_0_bits_op,
  output        io_bru_0_valid,
                io_bru_0_bits_fwd,
  output [3:0]  io_bru_0_bits_op,
  output [31:0] io_bru_0_bits_pc,
                io_bru_0_bits_target,
  output [4:0]  io_bru_0_bits_link,
  output        io_csr_valid,
  output [4:0]  io_csr_bits_addr,
  output [11:0] io_csr_bits_index,
  output [4:0]  io_csr_bits_rs1,
  output [1:0]  io_csr_bits_op,
  input         io_lsu_0_ready,
  output        io_lsu_0_valid,
                io_lsu_0_bits_store,
  output [4:0]  io_lsu_0_bits_addr,
                io_lsu_0_bits_op,
  output [31:0] io_lsu_0_bits_pc,
  output [2:0]  io_lsu_0_bits_elemWidth,
                io_lsu_0_bits_nfields,
  output [4:0]  io_lsu_0_bits_bit24To20,
  input  [2:0]  io_lsuQueueCapacity,
  output        io_mlu_0_valid,
  output [4:0]  io_mlu_0_bits_addr,
  output [2:0]  io_mlu_0_bits_op,
  input         io_dvu_0_ready,
  output        io_dvu_0_valid,
  output [4:0]  io_dvu_0_bits_addr,
  output [1:0]  io_dvu_0_bits_op,
  input         io_rvv_0_ready,
  output        io_rvv_0_valid,
  output [31:0] io_rvv_0_bits_pc,
  output [1:0]  io_rvv_0_bits_opcode,
  output [24:0] io_rvv_0_bits_bits,
  input         io_rvvState_valid,
  input  [6:0]  io_rvvState_bits_vstart,
  input         io_rvvIdle,
  input  [3:0]  io_rvvQueueCapacity,
  input  [2:0]  io_retirement_buffer_nSpace,
  input         io_retirement_buffer_empty,
                io_retirement_buffer_trap_pending,
                io_single_step,
  output        io_branch_0,
                io_jump_0
);

  wire [19:0] _decodedInsts_d_imm12_T_1 = {20{io_inst_0_bits_inst[31]}};
  wire [31:0] decodedInsts_0_immcsr = {27'h0, io_inst_0_bits_inst[19:15]};
  wire        decodedInsts_0_lui = io_inst_0_bits_inst[6:0] == 7'h37;
  wire        decodedInsts_0_auipc = io_inst_0_bits_inst[6:0] == 7'h17;
  wire        decodedInsts_0_jal = io_inst_0_bits_inst[6:0] == 7'h6F;
  wire [9:0]  _GEN = {io_inst_0_bits_inst[14:12], io_inst_0_bits_inst[6:0]};
  wire        decodedInsts_0_jalr = _GEN == 10'h67;
  wire        decodedInsts_0_beq = _GEN == 10'h63;
  wire        decodedInsts_0_bne = _GEN == 10'hE3;
  wire        decodedInsts_0_blt = _GEN == 10'h263;
  wire        decodedInsts_0_bge = _GEN == 10'h2E3;
  wire        decodedInsts_0_bltu = _GEN == 10'h363;
  wire        decodedInsts_0_bgeu = _GEN == 10'h3E3;
  wire [8:0]  _GEN_0 = {io_inst_0_bits_inst[13:12], io_inst_0_bits_inst[6:0]};
  wire        decodedInsts_0_csrrw = _GEN_0 == 9'hF3;
  wire        decodedInsts_0_csrrs = _GEN_0 == 9'h173;
  wire        decodedInsts_0_csrrc = _GEN_0 == 9'h1F3;
  wire        decodedInsts_0_lb = _GEN == 10'h3;
  wire        decodedInsts_0_lh = _GEN == 10'h83;
  wire        decodedInsts_0_lw = _GEN == 10'h103;
  wire        decodedInsts_0_lbu = _GEN == 10'h203;
  wire        decodedInsts_0_lhu = _GEN == 10'h283;
  wire        decodedInsts_0_sb = _GEN == 10'h23;
  wire        decodedInsts_0_sh = _GEN == 10'hA3;
  wire        decodedInsts_0_sw = _GEN == 10'h123;
  wire        decodedInsts_0_fence =
    {io_inst_0_bits_inst[31:28], io_inst_0_bits_inst[19:0]} == 24'hF;
  wire        decodedInsts_0_addi = _GEN == 10'h13;
  wire        decodedInsts_0_slti = _GEN == 10'h113;
  wire        decodedInsts_0_sltiu = _GEN == 10'h193;
  wire        decodedInsts_0_xori = _GEN == 10'h213;
  wire        decodedInsts_0_ori = _GEN == 10'h313;
  wire        decodedInsts_0_andi = _GEN == 10'h393;
  wire [16:0] _GEN_1 =
    {io_inst_0_bits_inst[31:25], io_inst_0_bits_inst[14:12], io_inst_0_bits_inst[6:0]};
  wire        decodedInsts_0_slli = _GEN_1 == 17'h93;
  wire        decodedInsts_0_srli = _GEN_1 == 17'h293;
  wire        decodedInsts_0_srai = _GEN_1 == 17'h8293;
  wire        decodedInsts_0_add = _GEN_1 == 17'h33;
  wire        decodedInsts_0_sub = _GEN_1 == 17'h8033;
  wire        decodedInsts_0_slt = _GEN_1 == 17'h133;
  wire        decodedInsts_0_sltu = _GEN_1 == 17'h1B3;
  wire        decodedInsts_0_xor = _GEN_1 == 17'h233;
  wire        decodedInsts_0_or = _GEN_1 == 17'h333;
  wire        decodedInsts_0_and = _GEN_1 == 17'h3B3;
  wire        decodedInsts_0_sll = _GEN_1 == 17'hB3;
  wire        decodedInsts_0_srl = _GEN_1 == 17'h2B3;
  wire        decodedInsts_0_sra = _GEN_1 == 17'h82B3;
  wire        decodedInsts_0_mul = _GEN_1 == 17'h433;
  wire        decodedInsts_0_mulh = _GEN_1 == 17'h4B3;
  wire        decodedInsts_0_mulhsu = _GEN_1 == 17'h533;
  wire        decodedInsts_0_mulhu = _GEN_1 == 17'h5B3;
  wire        decodedInsts_0_div = _GEN_1 == 17'h633;
  wire        decodedInsts_0_divu = _GEN_1 == 17'h6B3;
  wire        decodedInsts_0_rem = _GEN_1 == 17'h733;
  wire        decodedInsts_0_remu = _GEN_1 == 17'h7B3;
  wire        decodedInsts_0_andn = _GEN_1 == 17'h83B3;
  wire        decodedInsts_0_orn = _GEN_1 == 17'h8333;
  wire        decodedInsts_0_xnor = _GEN_1 == 17'h8233;
  wire [21:0] _GEN_2 =
    {io_inst_0_bits_inst[31:20], io_inst_0_bits_inst[14:12], io_inst_0_bits_inst[6:0]};
  wire        decodedInsts_0_clz = _GEN_2 == 22'h180093;
  wire        decodedInsts_0_ctz = _GEN_2 == 22'h180493;
  wire        decodedInsts_0_cpop = _GEN_2 == 22'h180893;
  wire        decodedInsts_0_max = _GEN_1 == 17'h1733;
  wire        decodedInsts_0_maxu = _GEN_1 == 17'h17B3;
  wire        decodedInsts_0_min = _GEN_1 == 17'h1633;
  wire        decodedInsts_0_minu = _GEN_1 == 17'h16B3;
  wire        decodedInsts_0_sextb = _GEN_2 == 22'h181093;
  wire        decodedInsts_0_sexth = _GEN_2 == 22'h181493;
  wire        decodedInsts_0_rol = _GEN_1 == 17'hC0B3;
  wire        decodedInsts_0_ror = _GEN_1 == 17'hC2B3;
  wire        decodedInsts_0_orcb = _GEN_2 == 22'hA1E93;
  wire        decodedInsts_0_rev8 = _GEN_2 == 22'h1A6293;
  wire        decodedInsts_0_zexth = _GEN_2 == 22'h20233;
  wire        decodedInsts_0_rori = _GEN_1 == 17'hC293;
  wire        decodedInsts_0_ebreak = io_inst_0_bits_inst == 32'h100073;
  wire        decodedInsts_0_ecall = io_inst_0_bits_inst == 32'h73;
  wire        decodedInsts_0_mpause = io_inst_0_bits_inst == 32'h8000073;
  wire        decodedInsts_0_mret = io_inst_0_bits_inst == 32'h30200073;
  wire        decodedInsts_0_wfi = io_inst_0_bits_inst == 32'h10500073;
  wire        decodedInsts_0_fencei = io_inst_0_bits_inst == 32'h100F;
  wire        decodedInsts_0_flushat =
    {io_inst_0_bits_inst[31:28],
     io_inst_0_bits_inst[24:20],
     io_inst_0_bits_inst[14:0]} == 24'h200077 & (|(io_inst_0_bits_inst[19:15]));
  wire        decodedInsts_0_flushall =
    {io_inst_0_bits_inst[31:28], io_inst_0_bits_inst[24:0]} == 29'h4000077;
  wire        _decodedInsts_d_rvv_new_opcode_T_2 = io_inst_0_bits_inst[6:0] == 7'h27;
  wire        _decodedInsts_d_rvv_new_opcode_T_4 = io_inst_0_bits_inst[6:0] == 7'h57;
  wire        decodedInsts_d_rvv_ret_valid =
    _decodedInsts_d_rvv_new_opcode_T_4
    | (_decodedInsts_d_rvv_new_opcode_T_2 | io_inst_0_bits_inst[6:0] == 7'h7)
    & ~(io_inst_0_bits_inst[28])
    & (io_inst_0_bits_inst[14:12] == 3'h6 | io_inst_0_bits_inst[14:12] == 3'h5
       | io_inst_0_bits_inst[14:12] == 3'h0);
  wire [1:0]  decodedInsts_d_rvv_ret_bits_opcode =
    _decodedInsts_d_rvv_new_opcode_T_4
      ? 2'h2
      : {1'h0, _decodedInsts_d_rvv_new_opcode_T_2};
  wire        _io_rs2Read_0_valid_T_1 = decodedInsts_0_beq | decodedInsts_0_bne;
  wire        _io_rs2Read_0_valid_T_25 = decodedInsts_0_sb | decodedInsts_0_sh;
  wire        _rvvRdMark_valid_T_17 = decodedInsts_d_rvv_ret_bits_opcode == 2'h2;
  wire        _rdMark_valid_T_5 = decodedInsts_0_lb | decodedInsts_0_lh;
  wire        _rvvRdMark_valid_T_1 = decodedInsts_d_rvv_ret_bits_opcode == 2'h0;
  wire        _io_rs2Read_0_valid_T_43 = decodedInsts_d_rvv_ret_bits_opcode == 2'h1;
  wire [31:0] _GEN_3 = {27'h0, io_inst_0_bits_inst[24:20]};
  wire        _io_rs2Read_0_valid_T_6 = decodedInsts_0_add | decodedInsts_0_sub;
  wire        _io_rs2Set_0_valid_T_6 = decodedInsts_0_addi | decodedInsts_0_slti;
  wire        _io_rs2Set_0_valid_T_16 = decodedInsts_0_clz | decodedInsts_0_ctz;
  wire        _io_rs2Read_0_valid_T_19 = decodedInsts_0_min | decodedInsts_0_minu;
  wire        _io_rs2Set_0_valid_T_1 = decodedInsts_0_csrrw | decodedInsts_0_csrrs;
  wire        _io_rs2Read_0_valid_T_34 = decodedInsts_0_mul | decodedInsts_0_mulh;
  wire        _io_rs2Read_0_valid_T_38 = decodedInsts_0_div | decodedInsts_0_divu;
  wire        coreIdle = io_scoreboard_regd == 32'h0 & io_rvvIdle & ~io_lsuActive;
  wire        tryDispatch =
    ~io_halted & ~io_interlock & io_inst_0_valid
    & {((decodedInsts_0_jalr | _rdMark_valid_T_5 | decodedInsts_0_lw | decodedInsts_0_lbu
         | decodedInsts_0_lhu | _io_rs2Read_0_valid_T_25 | decodedInsts_0_sw
         | decodedInsts_0_flushat | decodedInsts_0_flushall | decodedInsts_d_rvv_ret_valid
         & (|{_io_rs2Read_0_valid_T_43, _rvvRdMark_valid_T_1})
           ? 32'h1 << decodedInsts_0_immcsr
           : 32'h0)
        | (_io_rs2Read_0_valid_T_25 | decodedInsts_0_sw ? 32'h1 << _GEN_3 : 32'h0))
         & io_scoreboard_regd,
       ((_io_rs2Read_0_valid_T_1 | decodedInsts_0_blt | decodedInsts_0_bge
         | decodedInsts_0_bltu | decodedInsts_0_bgeu | _io_rs2Read_0_valid_T_6
         | decodedInsts_0_slt | decodedInsts_0_sltu | decodedInsts_0_xor
         | decodedInsts_0_or | decodedInsts_0_and | decodedInsts_0_xnor
         | decodedInsts_0_orn | decodedInsts_0_andn | decodedInsts_0_sll
         | decodedInsts_0_srl | decodedInsts_0_sra | _io_rs2Set_0_valid_T_6
         | decodedInsts_0_sltiu | decodedInsts_0_xori | decodedInsts_0_ori
         | decodedInsts_0_andi | decodedInsts_0_slli | decodedInsts_0_srli
         | decodedInsts_0_srai | decodedInsts_0_rori | _io_rs2Set_0_valid_T_16
         | decodedInsts_0_cpop | decodedInsts_0_sextb | decodedInsts_0_sexth
         | decodedInsts_0_zexth | decodedInsts_0_orcb | decodedInsts_0_rev8
         | _io_rs2Read_0_valid_T_19 | decodedInsts_0_max | decodedInsts_0_maxu
         | decodedInsts_0_rol | decodedInsts_0_ror | _io_rs2Set_0_valid_T_1
         | decodedInsts_0_csrrc | _io_rs2Read_0_valid_T_34 | decodedInsts_0_mulhsu
         | decodedInsts_0_mulhu | _io_rs2Read_0_valid_T_38 | decodedInsts_0_rem
         | decodedInsts_0_remu | decodedInsts_0_jalr | decodedInsts_d_rvv_ret_valid
         & ((|{_io_rs2Read_0_valid_T_43, _rvvRdMark_valid_T_1})
            | io_inst_0_bits_inst[14:12] == 3'h4 | io_inst_0_bits_inst[14:12] == 3'h6
            | (&(io_inst_0_bits_inst[14:12])) & ~(&(io_inst_0_bits_inst[31:30]))
            | _rvvRdMark_valid_T_17 & (&(io_inst_0_bits_inst[14:12]))
            & io_inst_0_bits_inst[31:25] == 7'h41 | _rvvRdMark_valid_T_17
            & (&(io_inst_0_bits_inst[14:12])) & io_inst_0_bits_inst[31:25] == 7'h42
            & ~(|(io_inst_0_bits_inst[22:20])) | _rvvRdMark_valid_T_17
            & (&(io_inst_0_bits_inst[14:12])) & io_inst_0_bits_inst[31:25] == 7'h42
            & io_inst_0_bits_inst[22:20] == 3'h1 | _rvvRdMark_valid_T_17
            & (&(io_inst_0_bits_inst[14:12])) & io_inst_0_bits_inst[31:25] == 7'h42
            & io_inst_0_bits_inst[22:20] == 3'h2)
           ? 32'h1 << decodedInsts_0_immcsr
           : 32'h0)
        | (_io_rs2Read_0_valid_T_1 | decodedInsts_0_blt | decodedInsts_0_bge
           | decodedInsts_0_bltu | decodedInsts_0_bgeu | _io_rs2Read_0_valid_T_6
           | decodedInsts_0_slt | decodedInsts_0_sltu | decodedInsts_0_xor
           | decodedInsts_0_or | decodedInsts_0_and | decodedInsts_0_xnor
           | decodedInsts_0_orn | decodedInsts_0_andn | decodedInsts_0_sll
           | decodedInsts_0_srl | decodedInsts_0_sra | _io_rs2Read_0_valid_T_19
           | decodedInsts_0_max | decodedInsts_0_maxu | decodedInsts_0_rol
           | decodedInsts_0_ror | _io_rs2Read_0_valid_T_25 | decodedInsts_0_sw
           | (_io_rs2Set_0_valid_T_1 | decodedInsts_0_csrrc) & ~(io_inst_0_bits_inst[14])
           | _io_rs2Read_0_valid_T_34 | decodedInsts_0_mulhsu | decodedInsts_0_mulhu
           | _io_rs2Read_0_valid_T_38 | decodedInsts_0_rem | decodedInsts_0_remu
           | decodedInsts_d_rvv_ret_valid
           & ((|{_io_rs2Read_0_valid_T_43, _rvvRdMark_valid_T_1})
              & io_inst_0_bits_inst[27:26] == 2'h2 | (&(io_inst_0_bits_inst[14:12]))
              & io_inst_0_bits_inst[31:25] == 7'h40 | _rvvRdMark_valid_T_17
              & (&(io_inst_0_bits_inst[14:12])) & io_inst_0_bits_inst[31:25] == 7'h41)
             ? 32'h1 << _GEN_3
             : 32'h0)) & io_scoreboard_comb} == 64'h0
    & ((~(_io_rs2Read_0_valid_T_25 | decodedInsts_0_sw)
        & ~(_io_rs2Read_0_valid_T_1 | decodedInsts_0_blt | decodedInsts_0_bge
            | decodedInsts_0_bltu | decodedInsts_0_bgeu) | decodedInsts_d_rvv_ret_valid
        & (_rvvRdMark_valid_T_17 & (&(io_inst_0_bits_inst[14:12])) | _rvvRdMark_valid_T_17
           & io_inst_0_bits_inst[14:12] == 3'h2 & io_inst_0_bits_inst[31:26] == 6'h10)
          ? 32'h1 << io_inst_0_bits_inst[11:7]
          : 32'h0) & io_scoreboard_comb) == 32'h0
    & ~((decodedInsts_0_fencei | decodedInsts_0_ebreak | decodedInsts_0_wfi
         | decodedInsts_0_mpause | decodedInsts_0_flushat | decodedInsts_0_flushall)
        & io_lsuActive)
    & (~decodedInsts_d_rvv_ret_valid
       | {_io_rs2Read_0_valid_T_43, _rvvRdMark_valid_T_1} == 2'h0 | io_rvvState_valid)
    & ~(decodedInsts_d_rvv_ret_valid & _rvvRdMark_valid_T_17
        & (io_inst_0_bits_inst[14:12] == 3'h2
           & (io_inst_0_bits_inst[31:26] == 6'h31 | io_inst_0_bits_inst[31:26] == 6'h30
              | io_inst_0_bits_inst[31:26] == 6'h17
              | (io_inst_0_bits_inst[31:26] == 6'h14
                   ? io_inst_0_bits_inst[19:15] == 5'h10
                     | io_inst_0_bits_inst[19:15] == 5'h3
                     | io_inst_0_bits_inst[19:15] == 5'h2
                     | io_inst_0_bits_inst[19:15] == 5'h1
                   : io_inst_0_bits_inst[31:26] == 6'h10
                       ? io_inst_0_bits_inst[19:15] == 5'h11
                         | io_inst_0_bits_inst[19:15] == 5'h10
                       : io_inst_0_bits_inst[31:26] == 6'h7
                         | io_inst_0_bits_inst[31:26] == 6'h6
                         | io_inst_0_bits_inst[31:26] == 6'h5
                         | io_inst_0_bits_inst[31:26] == 6'h4
                         | io_inst_0_bits_inst[31:26] == 6'h3
                         | io_inst_0_bits_inst[31:26] == 6'h2
                         | io_inst_0_bits_inst[31:26] == 6'h1
                         | ~(|(io_inst_0_bits_inst[31:26]))))
           | io_inst_0_bits_inst[14:12] == 3'h1
           & (io_inst_0_bits_inst[31:26] == 6'h7 | io_inst_0_bits_inst[31:26] == 6'h5
              | io_inst_0_bits_inst[31:26] == 6'h3 | io_inst_0_bits_inst[31:26] == 6'h1))
        & (|{~io_rvvState_valid, io_rvvState_bits_vstart})) & (|io_lsuQueueCapacity)
    & (|io_rvvQueueCapacity) & (|io_retirement_buffer_nSpace)
    & ~io_retirement_buffer_trap_pending
    & (~(_io_rs2Set_0_valid_T_1 | decodedInsts_0_csrrc) | io_retirement_buffer_empty)
    & (~io_single_step | coreIdle) & (~decodedInsts_0_mpause | coreIdle);
  wire        _alu_valid_T_59 =
    decodedInsts_0_auipc | decodedInsts_0_addi | decodedInsts_0_add;
  wire        _alu_valid_T_61 = decodedInsts_0_slti | decodedInsts_0_slt;
  wire        _alu_valid_T_62 = decodedInsts_0_sltiu | decodedInsts_0_sltu;
  wire        _alu_valid_T_63 = decodedInsts_0_xori | decodedInsts_0_xor;
  wire        _alu_valid_T_64 = decodedInsts_0_ori | decodedInsts_0_or;
  wire        _alu_valid_T_65 = decodedInsts_0_andi | decodedInsts_0_and;
  wire        _alu_valid_T_66 = decodedInsts_0_slli | decodedInsts_0_sll;
  wire        _alu_valid_T_67 = decodedInsts_0_srli | decodedInsts_0_srl;
  wire        _alu_valid_T_68 = decodedInsts_0_srai | decodedInsts_0_sra;
  wire        io_alu_0_valid_0 =
    tryDispatch
    & (_alu_valid_T_59 | decodedInsts_0_sub | _alu_valid_T_61 | _alu_valid_T_62
       | _alu_valid_T_63 | _alu_valid_T_64 | _alu_valid_T_65 | _alu_valid_T_66
       | _alu_valid_T_67 | _alu_valid_T_68 | decodedInsts_0_lui | decodedInsts_0_andn
       | decodedInsts_0_orn | decodedInsts_0_xnor | decodedInsts_0_clz
       | decodedInsts_0_ctz | decodedInsts_0_cpop | decodedInsts_0_max
       | decodedInsts_0_maxu | decodedInsts_0_min | decodedInsts_0_minu
       | decodedInsts_0_sextb | decodedInsts_0_sexth | decodedInsts_0_rol
       | decodedInsts_0_ror | decodedInsts_0_orcb | decodedInsts_0_rev8
       | decodedInsts_0_zexth | decodedInsts_0_rori);
  wire [3:0]  bru_bits =
    {3'h0, decodedInsts_0_jalr} | {2'h0, decodedInsts_0_beq, 1'h0}
    | (decodedInsts_0_bne ? 4'h3 : 4'h0) | {1'h0, decodedInsts_0_blt, 2'h0}
    | (decodedInsts_0_bge ? 4'h5 : 4'h0) | (decodedInsts_0_bltu ? 4'h6 : 4'h0)
    | (decodedInsts_0_bgeu ? 4'h7 : 4'h0) | {decodedInsts_0_ebreak, 3'h0}
    | (decodedInsts_0_ecall ? 4'h9 : 4'h0) | (decodedInsts_0_mpause ? 4'hA : 4'h0)
    | (decodedInsts_0_mret ? 4'hB : 4'h0) | (decodedInsts_0_wfi ? 4'hC : 4'h0);
  wire [31:0] _bru_target_T_2 =
    io_inst_0_bits_addr
    + {{12{io_inst_0_bits_inst[31]}},
       io_inst_0_bits_inst[2]
         ? {io_inst_0_bits_inst[19:12],
            io_inst_0_bits_inst[20],
            io_inst_0_bits_inst[30:21]}
         : {{8{io_inst_0_bits_inst[31]}},
            io_inst_0_bits_inst[7],
            io_inst_0_bits_inst[30:25],
            io_inst_0_bits_inst[11:8]},
       1'h0};
  wire        _io_bru_0_valid_T =
    tryDispatch
    & (decodedInsts_0_jal | decodedInsts_0_jalr | decodedInsts_0_beq | decodedInsts_0_bne
       | decodedInsts_0_blt | decodedInsts_0_bge | decodedInsts_0_bltu
       | decodedInsts_0_bgeu | decodedInsts_0_ebreak | decodedInsts_0_ecall
       | decodedInsts_0_mpause | decodedInsts_0_mret | decodedInsts_0_wfi);
  wire        jalFault =
    _io_bru_0_valid_T & bru_bits == 4'h0 & (|(_bru_target_T_2[1:0])) & ~io_branchTaken;
  wire        jalrFault =
    _io_bru_0_valid_T & bru_bits == 4'h1 & io_jalrTarget_0_data[1] & ~io_branchTaken;
  wire        bxxFault =
    _io_bru_0_valid_T
    & (|{bru_bits == 4'h7,
         bru_bits == 4'h6,
         bru_bits == 4'h5,
         bru_bits == 4'h4,
         bru_bits == 4'h3,
         bru_bits == 4'h2}) & (|(_bru_target_T_2[1:0])) & ~io_branchTaken;
  wire        io_bru_0_valid_0 = _io_bru_0_valid_T & ~(jalFault | jalrFault | bxxFault);
  wire        io_mlu_0_valid_0 =
    tryDispatch
    & (decodedInsts_0_mul | decodedInsts_0_mulh | decodedInsts_0_mulhsu
       | decodedInsts_0_mulhu);
  wire        io_dvu_0_valid_0 =
    tryDispatch
    & (decodedInsts_0_div | decodedInsts_0_divu | decodedInsts_0_rem
       | decodedInsts_0_remu);
  wire        lsu_isRvvLoad = decodedInsts_d_rvv_ret_valid & _rvvRdMark_valid_T_1;
  wire        lsu_isRvvStore = decodedInsts_d_rvv_ret_valid & _io_rs2Read_0_valid_T_43;
  wire        _lsu_T_9 = io_inst_0_bits_inst[27:26] == 2'h0;
  wire        _lsu_valid_T_56 = lsu_isRvvLoad & _lsu_T_9;
  wire        _lsu_T_11 = io_inst_0_bits_inst[27:26] == 2'h1;
  wire        _lsu_valid_T_57 = lsu_isRvvLoad & _lsu_T_11;
  wire        _lsu_T_13 = io_inst_0_bits_inst[27:26] == 2'h2;
  wire        _lsu_valid_T_58 = lsu_isRvvLoad & _lsu_T_13;
  wire        _lsu_valid_T_59 = lsu_isRvvLoad & (&(io_inst_0_bits_inst[27:26]));
  wire        _lsu_valid_T_60 = lsu_isRvvStore & _lsu_T_9;
  wire        _lsu_valid_T_61 = lsu_isRvvStore & _lsu_T_11;
  wire        _lsu_valid_T_62 = lsu_isRvvStore & _lsu_T_13;
  wire        _lsu_valid_T_63 = lsu_isRvvStore & (&(io_inst_0_bits_inst[27:26]));
  wire        io_lsu_0_valid_0 =
    tryDispatch
    & (decodedInsts_0_lb | decodedInsts_0_lh | decodedInsts_0_lw | decodedInsts_0_lbu
       | decodedInsts_0_lhu | decodedInsts_0_sb | decodedInsts_0_sh | decodedInsts_0_sw
       | decodedInsts_0_wfi | decodedInsts_0_fencei | decodedInsts_0_flushat
       | decodedInsts_0_flushall | _lsu_valid_T_56 | _lsu_valid_T_57 | _lsu_valid_T_58
       | _lsu_valid_T_59 | _lsu_valid_T_60 | _lsu_valid_T_61 | _lsu_valid_T_62
       | _lsu_valid_T_63);
  wire        csr_valid =
    decodedInsts_0_csrrw | decodedInsts_0_csrrs | decodedInsts_0_csrrc;
  wire        csr_address_valid =
    io_inst_0_bits_inst[31:20] == 12'h0 | io_inst_0_bits_inst[31:20] == 12'h1
    | io_inst_0_bits_inst[31:20] == 12'h2 | io_inst_0_bits_inst[31:20] == 12'h3
    | io_inst_0_bits_inst[31:20] == 12'h8 | io_inst_0_bits_inst[31:20] == 12'h9
    | io_inst_0_bits_inst[31:20] == 12'hA | io_inst_0_bits_inst[31:20] == 12'h300
    | io_inst_0_bits_inst[31:20] == 12'h301 | io_inst_0_bits_inst[31:20] == 12'h304
    | io_inst_0_bits_inst[31:20] == 12'h305 | io_inst_0_bits_inst[31:20] == 12'h310
    | io_inst_0_bits_inst[31:20] == 12'h340 | io_inst_0_bits_inst[31:20] == 12'h341
    | io_inst_0_bits_inst[31:20] == 12'h342 | io_inst_0_bits_inst[31:20] == 12'h343
    | io_inst_0_bits_inst[31:20] == 12'h344 | io_inst_0_bits_inst[31:20] == 12'h7A0
    | io_inst_0_bits_inst[31:20] == 12'h7A1 | io_inst_0_bits_inst[31:20] == 12'h7A2
    | io_inst_0_bits_inst[31:20] == 12'h7A4 | io_inst_0_bits_inst[31:20] == 12'h7B0
    | io_inst_0_bits_inst[31:20] == 12'h7B1 | io_inst_0_bits_inst[31:20] == 12'h7B2
    | io_inst_0_bits_inst[31:20] == 12'h7B3 | io_inst_0_bits_inst[31:20] == 12'h7C0
    | io_inst_0_bits_inst[31:20] == 12'h7C1 | io_inst_0_bits_inst[31:20] == 12'h7C2
    | io_inst_0_bits_inst[31:20] == 12'h7C3 | io_inst_0_bits_inst[31:20] == 12'h7C4
    | io_inst_0_bits_inst[31:20] == 12'h7C5 | io_inst_0_bits_inst[31:20] == 12'h7C6
    | io_inst_0_bits_inst[31:20] == 12'h7C7 | io_inst_0_bits_inst[31:20] == 12'h7E0
    | io_inst_0_bits_inst[31:20] == 12'h7E1 | io_inst_0_bits_inst[31:20] == 12'hB00
    | io_inst_0_bits_inst[31:20] == 12'hB02 | io_inst_0_bits_inst[31:20] == 12'hB80
    | io_inst_0_bits_inst[31:20] == 12'hB82 | io_inst_0_bits_inst[31:20] == 12'hC20
    | io_inst_0_bits_inst[31:20] == 12'hC21 | io_inst_0_bits_inst[31:20] == 12'hC22
    | io_inst_0_bits_inst[31:20] == 12'hC23 | io_inst_0_bits_inst[31:20] == 12'hF11
    | io_inst_0_bits_inst[31:20] == 12'hF12 | io_inst_0_bits_inst[31:20] == 12'hF13
    | io_inst_0_bits_inst[31:20] == 12'hF14 | io_inst_0_bits_inst[31:20] == 12'hFC0
    | io_inst_0_bits_inst[31:20] == 12'hFC4 | io_inst_0_bits_inst[31:20] == 12'hFC8
    | io_inst_0_bits_inst[31:20] == 12'hFCC | io_inst_0_bits_inst[31:20] == 12'hFD0
    | io_inst_0_bits_inst[31:20] == 12'hFD4;
  wire        io_csr_valid_0 =
    tryDispatch & csr_valid & csr_address_valid
    & (io_rvvIdle
       | ~(io_inst_0_bits_inst[31:20] == 12'h9 | io_inst_0_bits_inst[31:20] == 12'hF));
  wire        io_rvv_0_valid_0 = tryDispatch & decodedInsts_d_rvv_ret_valid;
  wire        dispatched_3 = io_dvu_0_ready & io_dvu_0_valid_0;
  wire        dispatched_4 = io_lsu_0_ready & io_lsu_0_valid_0;
  wire        dispatched_7 = io_rvv_0_ready & io_rvv_0_valid_0;
  wire        lastReady_1 =
    io_alu_0_valid_0 | io_bru_0_valid_0 | io_mlu_0_valid_0 | dispatched_3 | dispatched_4
    | io_csr_valid_0 | tryDispatch & decodedInsts_0_fence | dispatched_7;
  wire        _io_rs2Set_0_valid_T = lastReady_1 & io_inst_0_valid;
  wire        _rdMark_valid_T_17 = decodedInsts_d_rvv_ret_bits_opcode == 2'h2;
  assign io_csrFault_0 = csr_valid & ~csr_address_valid & tryDispatch;
  assign io_jalFault_0 = jalFault;
  assign io_jalrFault_0 = jalrFault;
  assign io_bxxFault_0 = bxxFault;
  assign io_undefFault_0 =
    io_inst_0_valid
    & {decodedInsts_0_lui,
       decodedInsts_0_auipc,
       decodedInsts_0_jal,
       decodedInsts_0_jalr,
       decodedInsts_0_beq,
       decodedInsts_0_bne,
       decodedInsts_0_blt,
       decodedInsts_0_bge,
       decodedInsts_0_bltu,
       decodedInsts_0_bgeu,
       decodedInsts_0_csrrw,
       decodedInsts_0_csrrs,
       decodedInsts_0_csrrc,
       decodedInsts_0_lb,
       decodedInsts_0_lh,
       decodedInsts_0_lw,
       decodedInsts_0_lbu,
       decodedInsts_0_lhu,
       decodedInsts_0_sb,
       decodedInsts_0_sh,
       decodedInsts_0_sw,
       decodedInsts_0_fence,
       decodedInsts_0_addi,
       decodedInsts_0_slti,
       decodedInsts_0_sltiu,
       decodedInsts_0_xori,
       decodedInsts_0_ori,
       decodedInsts_0_andi,
       decodedInsts_0_add,
       decodedInsts_0_sub,
       decodedInsts_0_slt,
       decodedInsts_0_sltu,
       decodedInsts_0_xor,
       decodedInsts_0_or,
       decodedInsts_0_and,
       decodedInsts_0_xnor,
       decodedInsts_0_orn,
       decodedInsts_0_andn,
       decodedInsts_0_slli,
       decodedInsts_0_srli,
       decodedInsts_0_srai,
       decodedInsts_0_sll,
       decodedInsts_0_srl,
       decodedInsts_0_sra,
       decodedInsts_0_mul,
       decodedInsts_0_mulh,
       decodedInsts_0_mulhsu,
       decodedInsts_0_mulhu,
       decodedInsts_0_div,
       decodedInsts_0_divu,
       decodedInsts_0_rem,
       decodedInsts_0_remu,
       decodedInsts_0_clz,
       decodedInsts_0_ctz,
       decodedInsts_0_cpop,
       decodedInsts_0_min,
       decodedInsts_0_minu,
       decodedInsts_0_max,
       decodedInsts_0_maxu,
       decodedInsts_0_sextb,
       decodedInsts_0_sexth,
       decodedInsts_0_zexth,
       decodedInsts_0_rol,
       decodedInsts_0_ror,
       decodedInsts_0_orcb,
       decodedInsts_0_rev8,
       decodedInsts_0_rori,
       decodedInsts_0_ebreak,
       decodedInsts_0_ecall,
       decodedInsts_0_wfi,
       decodedInsts_0_mpause,
       decodedInsts_0_mret,
       decodedInsts_0_fencei,
       decodedInsts_0_flushat,
       decodedInsts_0_flushall,
       decodedInsts_d_rvv_ret_valid} == 76'h0;
  assign io_rvvFault_0 =
    io_inst_0_valid & decodedInsts_d_rvv_ret_valid & _rvvRdMark_valid_T_17
    & (io_inst_0_bits_inst[14:12] == 3'h2
       & (io_inst_0_bits_inst[31:26] == 6'h31 | io_inst_0_bits_inst[31:26] == 6'h30
          | io_inst_0_bits_inst[31:26] == 6'h17
          | (io_inst_0_bits_inst[31:26] == 6'h14
               ? io_inst_0_bits_inst[19:15] == 5'h10 | io_inst_0_bits_inst[19:15] == 5'h3
                 | io_inst_0_bits_inst[19:15] == 5'h2 | io_inst_0_bits_inst[19:15] == 5'h1
               : io_inst_0_bits_inst[31:26] == 6'h10
                   ? io_inst_0_bits_inst[19:15] == 5'h11
                     | io_inst_0_bits_inst[19:15] == 5'h10
                   : io_inst_0_bits_inst[31:26] == 6'h7
                     | io_inst_0_bits_inst[31:26] == 6'h6
                     | io_inst_0_bits_inst[31:26] == 6'h5
                     | io_inst_0_bits_inst[31:26] == 6'h4
                     | io_inst_0_bits_inst[31:26] == 6'h3
                     | io_inst_0_bits_inst[31:26] == 6'h2
                     | io_inst_0_bits_inst[31:26] == 6'h1
                     | ~(|(io_inst_0_bits_inst[31:26]))))
       | io_inst_0_bits_inst[14:12] == 3'h1
       & (io_inst_0_bits_inst[31:26] == 6'h7 | io_inst_0_bits_inst[31:26] == 6'h5
          | io_inst_0_bits_inst[31:26] == 6'h3 | io_inst_0_bits_inst[31:26] == 6'h1))
    & io_rvvState_valid & (|io_rvvState_bits_vstart);
  assign io_bruTarget_0 = _bru_target_T_2;
  assign io_inst_0_ready = lastReady_1;
  assign io_rs1Read_0_valid =
    _io_rs2Set_0_valid_T
    & (_io_rs2Read_0_valid_T_1 | decodedInsts_0_blt | decodedInsts_0_bge
       | decodedInsts_0_bltu | decodedInsts_0_bgeu | _io_rs2Read_0_valid_T_6
       | decodedInsts_0_slt | decodedInsts_0_sltu | decodedInsts_0_xor | decodedInsts_0_or
       | decodedInsts_0_and | decodedInsts_0_xnor | decodedInsts_0_orn
       | decodedInsts_0_andn | decodedInsts_0_sll | decodedInsts_0_srl
       | decodedInsts_0_sra | _io_rs2Set_0_valid_T_6 | decodedInsts_0_sltiu
       | decodedInsts_0_xori | decodedInsts_0_ori | decodedInsts_0_andi
       | decodedInsts_0_slli | decodedInsts_0_srli | decodedInsts_0_srai
       | decodedInsts_0_rori | _io_rs2Set_0_valid_T_16 | decodedInsts_0_cpop
       | decodedInsts_0_sextb | decodedInsts_0_sexth | decodedInsts_0_zexth
       | decodedInsts_0_orcb | decodedInsts_0_rev8 | _io_rs2Read_0_valid_T_19
       | decodedInsts_0_max | decodedInsts_0_maxu | decodedInsts_0_rol
       | decodedInsts_0_ror | _io_rs2Set_0_valid_T_1 | decodedInsts_0_csrrc
       | _io_rs2Read_0_valid_T_34 | decodedInsts_0_mulhsu | decodedInsts_0_mulhu
       | _io_rs2Read_0_valid_T_38 | decodedInsts_0_rem | decodedInsts_0_remu
       | decodedInsts_0_jalr | decodedInsts_d_rvv_ret_valid
       & ((|{_io_rs2Read_0_valid_T_43, _rvvRdMark_valid_T_1})
          | io_inst_0_bits_inst[14:12] == 3'h4 | io_inst_0_bits_inst[14:12] == 3'h6
          | (&(io_inst_0_bits_inst[14:12])) & ~(&(io_inst_0_bits_inst[31:30]))
          | _rvvRdMark_valid_T_17 & (&(io_inst_0_bits_inst[14:12]))
          & io_inst_0_bits_inst[31:25] == 7'h41 | _rvvRdMark_valid_T_17
          & (&(io_inst_0_bits_inst[14:12])) & io_inst_0_bits_inst[31:25] == 7'h42
          & ~(|(io_inst_0_bits_inst[22:20])) | _rvvRdMark_valid_T_17
          & (&(io_inst_0_bits_inst[14:12])) & io_inst_0_bits_inst[31:25] == 7'h42
          & io_inst_0_bits_inst[22:20] == 3'h1 | _rvvRdMark_valid_T_17
          & (&(io_inst_0_bits_inst[14:12])) & io_inst_0_bits_inst[31:25] == 7'h42
          & io_inst_0_bits_inst[22:20] == 3'h2));
  assign io_rs1Read_0_addr =
    io_inst_0_bits_inst[0] ? io_inst_0_bits_inst[19:15] : {4'h0, io_inst_0_bits_inst[27]};
  assign io_rs1Set_0_valid =
    _io_rs2Set_0_valid_T
    & (decodedInsts_0_auipc | (_io_rs2Set_0_valid_T_1 | decodedInsts_0_csrrc)
       & io_inst_0_bits_inst[14]);
  assign io_rs1Set_0_value =
    _io_rs2Set_0_valid_T_1 | decodedInsts_0_csrrc
      ? decodedInsts_0_immcsr
      : io_inst_0_bits_addr;
  assign io_rs2Read_0_valid =
    _io_rs2Set_0_valid_T
    & (_io_rs2Read_0_valid_T_1 | decodedInsts_0_blt | decodedInsts_0_bge
       | decodedInsts_0_bltu | decodedInsts_0_bgeu | _io_rs2Read_0_valid_T_6
       | decodedInsts_0_slt | decodedInsts_0_sltu | decodedInsts_0_xor | decodedInsts_0_or
       | decodedInsts_0_and | decodedInsts_0_xnor | decodedInsts_0_orn
       | decodedInsts_0_andn | decodedInsts_0_sll | decodedInsts_0_srl
       | decodedInsts_0_sra | _io_rs2Read_0_valid_T_19 | decodedInsts_0_max
       | decodedInsts_0_maxu | decodedInsts_0_rol | decodedInsts_0_ror
       | _io_rs2Read_0_valid_T_25 | decodedInsts_0_sw
       | (_io_rs2Set_0_valid_T_1 | decodedInsts_0_csrrc) & ~(io_inst_0_bits_inst[14])
       | _io_rs2Read_0_valid_T_34 | decodedInsts_0_mulhsu | decodedInsts_0_mulhu
       | _io_rs2Read_0_valid_T_38 | decodedInsts_0_rem | decodedInsts_0_remu
       | decodedInsts_d_rvv_ret_valid
       & ((|{_io_rs2Read_0_valid_T_43, _rvvRdMark_valid_T_1})
          & io_inst_0_bits_inst[27:26] == 2'h2 | (&(io_inst_0_bits_inst[14:12]))
          & io_inst_0_bits_inst[31:25] == 7'h40 | _rvvRdMark_valid_T_17
          & (&(io_inst_0_bits_inst[14:12])) & io_inst_0_bits_inst[31:25] == 7'h41));
  assign io_rs2Read_0_addr = io_inst_0_bits_inst[24:20];
  assign io_rs2Set_0_valid =
    _io_rs2Set_0_valid_T
    & (decodedInsts_0_auipc | (_io_rs2Set_0_valid_T_1 | decodedInsts_0_csrrc)
       & io_inst_0_bits_inst[14] | _io_rs2Set_0_valid_T_6 | decodedInsts_0_sltiu
       | decodedInsts_0_xori | decodedInsts_0_ori | decodedInsts_0_andi
       | decodedInsts_0_slli | decodedInsts_0_srli | decodedInsts_0_srai
       | decodedInsts_0_rori | _io_rs2Set_0_valid_T_16 | decodedInsts_0_cpop
       | decodedInsts_0_sextb | decodedInsts_0_sexth | decodedInsts_0_zexth
       | decodedInsts_0_orcb | decodedInsts_0_rev8 | decodedInsts_0_lui);
  assign io_rs2Set_0_value =
    decodedInsts_0_auipc | decodedInsts_0_lui
      ? {io_inst_0_bits_inst[31:12], 12'h0}
      : {_decodedInsts_d_imm12_T_1, io_inst_0_bits_inst[31:20]};
  assign io_rdMark_0_valid =
    io_alu_0_valid_0 | io_mlu_0_valid_0 | dispatched_3 | dispatched_4
    & (_rdMark_valid_T_5 | decodedInsts_0_lw | decodedInsts_0_lbu | decodedInsts_0_lhu)
    | io_csr_valid_0 | dispatched_7
    & (_rdMark_valid_T_17 & (&(io_inst_0_bits_inst[14:12])) | _rdMark_valid_T_17
       & io_inst_0_bits_inst[14:12] == 3'h2 & io_inst_0_bits_inst[31:26] == 6'h10)
    | io_bru_0_valid_0 & (|{bru_bits == 4'h1, bru_bits == 4'h0})
    & (|(io_inst_0_bits_inst[11:7]));
  assign io_rdMark_0_addr = io_inst_0_bits_inst[11:7];
  assign io_busRead_0_immen = ~decodedInsts_0_flushat;
  assign io_busRead_0_immed =
    decodedInsts_d_rvv_ret_valid
      ? 32'h0
      : {_decodedInsts_d_imm12_T_1,
         io_inst_0_bits_inst[31:25],
         io_inst_0_bits_inst[6:3] == 4'h4 & (&(io_inst_0_bits_inst[1:0]))
           ? io_inst_0_bits_inst[11:7]
           : io_inst_0_bits_inst[24:20]};
  assign io_rvvRdMark_0_valid =
    dispatched_7
    & (_rvvRdMark_valid_T_1 | _rvvRdMark_valid_T_17
       & ~(_rvvRdMark_valid_T_17 & (&(io_inst_0_bits_inst[14:12])) | _rvvRdMark_valid_T_17
           & io_inst_0_bits_inst[14:12] == 3'h2 & io_inst_0_bits_inst[31:26] == 6'h10)
       & ~(_rvvRdMark_valid_T_17 & io_inst_0_bits_inst[14:12] == 3'h1
           & io_inst_0_bits_inst[31:26] == 6'h10));
  assign io_rvvRdMark_0_addr = io_inst_0_bits_inst[11:7];
  assign io_alu_0_valid = io_alu_0_valid_0;
  assign io_alu_0_bits_addr = io_inst_0_bits_inst[11:7];
  assign io_alu_0_bits_op =
    {4'h0, decodedInsts_0_sub} | {3'h0, _alu_valid_T_61, 1'h0}
    | (_alu_valid_T_62 ? 5'h3 : 5'h0) | {2'h0, _alu_valid_T_63, 2'h0}
    | (_alu_valid_T_64 ? 5'h5 : 5'h0) | (_alu_valid_T_65 ? 5'h6 : 5'h0)
    | (_alu_valid_T_66 ? 5'h7 : 5'h0) | {1'h0, _alu_valid_T_67, 3'h0}
    | (_alu_valid_T_68 ? 5'h9 : 5'h0) | (decodedInsts_0_lui ? 5'hA : 5'h0)
    | (decodedInsts_0_andn ? 5'hB : 5'h0) | (decodedInsts_0_orn ? 5'hC : 5'h0)
    | (decodedInsts_0_xnor ? 5'hD : 5'h0) | (decodedInsts_0_clz ? 5'hE : 5'h0)
    | (decodedInsts_0_ctz ? 5'hF : 5'h0) | {decodedInsts_0_cpop, 4'h0}
    | (decodedInsts_0_max ? 5'h11 : 5'h0) | (decodedInsts_0_maxu ? 5'h12 : 5'h0)
    | (decodedInsts_0_min ? 5'h13 : 5'h0) | (decodedInsts_0_minu ? 5'h14 : 5'h0)
    | (decodedInsts_0_sextb ? 5'h15 : 5'h0) | (decodedInsts_0_sexth ? 5'h16 : 5'h0)
    | (decodedInsts_0_rol ? 5'h17 : 5'h0) | (decodedInsts_0_ror ? 5'h18 : 5'h0)
    | (decodedInsts_0_orcb ? 5'h19 : 5'h0) | (decodedInsts_0_rev8 ? 5'h1A : 5'h0)
    | (decodedInsts_0_zexth ? 5'h1B : 5'h0) | (decodedInsts_0_rori ? 5'h18 : 5'h0);
  assign io_bru_0_valid = io_bru_0_valid_0;
  assign io_bru_0_bits_fwd = io_inst_0_bits_brchFwd;
  assign io_bru_0_bits_op = bru_bits;
  assign io_bru_0_bits_pc = io_inst_0_bits_addr;
  assign io_bru_0_bits_target = _bru_target_T_2;
  assign io_bru_0_bits_link = io_inst_0_bits_inst[11:7];
  assign io_csr_valid = io_csr_valid_0;
  assign io_csr_bits_addr = io_inst_0_bits_inst[11:7];
  assign io_csr_bits_index = io_inst_0_bits_inst[31:20];
  assign io_csr_bits_rs1 = io_inst_0_bits_inst[19:15];
  assign io_csr_bits_op = {1'h0, decodedInsts_0_csrrs} | {decodedInsts_0_csrrc, 1'h0};
  assign io_lsu_0_valid = io_lsu_0_valid_0;
  assign io_lsu_0_bits_store = io_inst_0_bits_inst[5];
  assign io_lsu_0_bits_addr = io_inst_0_bits_inst[11:7];
  assign io_lsu_0_bits_op =
    {4'h0, decodedInsts_0_lh} | {3'h0, decodedInsts_0_lw, 1'h0}
    | (decodedInsts_0_lbu ? 5'h3 : 5'h0) | {2'h0, decodedInsts_0_lhu, 2'h0}
    | (decodedInsts_0_sb ? 5'h5 : 5'h0) | (decodedInsts_0_sh ? 5'h6 : 5'h0)
    | (decodedInsts_0_sw ? 5'h7 : 5'h0) | {1'h0, decodedInsts_0_wfi, 3'h0}
    | {1'h0, decodedInsts_0_fencei, 3'h0} | (decodedInsts_0_flushat ? 5'h9 : 5'h0)
    | (decodedInsts_0_flushall ? 5'hA : 5'h0) | (_lsu_valid_T_56 ? 5'hD : 5'h0)
    | {_lsu_valid_T_57, 4'h0} | (_lsu_valid_T_58 ? 5'hE : 5'h0)
    | (_lsu_valid_T_59 ? 5'hF : 5'h0) | (_lsu_valid_T_60 ? 5'h11 : 5'h0)
    | (_lsu_valid_T_61 ? 5'h14 : 5'h0) | (_lsu_valid_T_62 ? 5'h12 : 5'h0)
    | (_lsu_valid_T_63 ? 5'h13 : 5'h0);
  assign io_lsu_0_bits_pc = io_inst_0_bits_addr;
  assign io_lsu_0_bits_elemWidth = io_inst_0_bits_inst[14:12];
  assign io_lsu_0_bits_nfields = io_inst_0_bits_inst[31:29];
  assign io_lsu_0_bits_bit24To20 = io_inst_0_bits_inst[24:20];
  assign io_mlu_0_valid = io_mlu_0_valid_0;
  assign io_mlu_0_bits_addr = io_inst_0_bits_inst[11:7];
  assign io_mlu_0_bits_op =
    {2'h0, decodedInsts_0_mulh} | {1'h0, decodedInsts_0_mulhsu, 1'h0}
    | (decodedInsts_0_mulhu ? 3'h3 : 3'h0);
  assign io_dvu_0_valid = io_dvu_0_valid_0;
  assign io_dvu_0_bits_addr = io_inst_0_bits_inst[11:7];
  assign io_dvu_0_bits_op =
    {1'h0, decodedInsts_0_divu} | {decodedInsts_0_rem, 1'h0} | {2{decodedInsts_0_remu}};
  assign io_rvv_0_valid = io_rvv_0_valid_0;
  assign io_rvv_0_bits_pc = io_inst_0_bits_addr;
  assign io_rvv_0_bits_opcode = decodedInsts_d_rvv_ret_bits_opcode;
  assign io_rvv_0_bits_bits = io_inst_0_bits_inst[31:7];
  assign io_branch_0 =
    _io_rs2Read_0_valid_T_1 | decodedInsts_0_blt | decodedInsts_0_bge
    | decodedInsts_0_bltu | decodedInsts_0_bgeu;
  assign io_jump_0 =
    (decodedInsts_0_jal | decodedInsts_0_jalr | decodedInsts_0_ebreak
     | decodedInsts_0_ecall | decodedInsts_0_mpause | decodedInsts_0_mret)
    & ~decodedInsts_0_ecall & ~decodedInsts_0_mret;
endmodule

