// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
module FaultManager(
  input         io_in_fault_0_csr,
                io_in_fault_0_jal,
                io_in_fault_0_jalr,
                io_in_fault_0_bxx,
                io_in_fault_0_undef,
                io_in_fault_0_rvv,
  input  [31:0] io_in_pc_0_pc,
  input         io_in_memory_fault_valid,
                io_in_memory_fault_bits_write,
  input  [31:0] io_in_memory_fault_bits_addr,
                io_in_memory_fault_bits_epc,
  input         io_in_rvv_fault_valid,
  input  [31:0] io_in_rvv_fault_bits_mepc,
                io_in_rvv_fault_bits_mtval,
                io_in_undef_0_inst,
                io_in_jal_0_target,
                io_in_jalr_0_target,
  input         io_in_fetchFault_valid,
  input  [31:0] io_in_fetchFault_bits,
  output        io_out_valid,
  output [31:0] io_out_bits_mepc,
                io_out_bits_mtval,
                io_out_bits_mcause,
  output        io_out_bits_decode
);

  wire faults_0 =
    io_in_fault_0_csr | io_in_fault_0_jal | io_in_fault_0_jalr | io_in_fault_0_bxx
    | io_in_fault_0_undef | io_in_fault_0_rvv;
  wire load_fault = io_in_memory_fault_valid & ~io_in_memory_fault_bits_write;
  wire store_fault = io_in_memory_fault_valid & io_in_memory_fault_bits_write;
  wire _GEN = load_fault | store_fault;
  wire _GEN_0 = io_in_fault_0_undef | io_in_fault_0_rvv;
  assign io_out_valid =
    faults_0 | io_in_fetchFault_valid | load_fault | store_fault | io_in_rvv_fault_valid;
  assign io_out_bits_mepc =
    _GEN
      ? io_in_memory_fault_bits_epc
      : io_in_rvv_fault_valid
          ? io_in_rvv_fault_bits_mepc
          : faults_0
              ? io_in_pc_0_pc
              : io_in_fetchFault_valid ? io_in_fetchFault_bits : 32'h0;
  assign io_out_bits_mtval =
    _GEN
      ? io_in_memory_fault_bits_addr
      : io_in_rvv_fault_valid
          ? io_in_rvv_fault_bits_mtval
          : io_in_fault_0_csr
              ? 32'h0
              : io_in_fault_0_jal
                  ? io_in_jal_0_target
                  : io_in_fault_0_jalr
                      ? io_in_jalr_0_target & 32'hFFFFFFFE
                      : io_in_fault_0_bxx | ~_GEN_0 ? 32'h0 : io_in_undef_0_inst;
  assign io_out_bits_mcause =
    load_fault
      ? 32'h5
      : store_fault
          ? 32'h7
          : io_in_rvv_fault_valid | io_in_fault_0_csr
              ? 32'h2
              : io_in_fault_0_jal | io_in_fault_0_jalr | io_in_fault_0_bxx
                  ? 32'h0
                  : _GEN_0 ? 32'h2 : {31'h0, io_in_fetchFault_valid};
  assign io_out_bits_decode =
    io_in_fault_0_csr | io_in_fault_0_jal | io_in_fault_0_jalr | io_in_fault_0_bxx
    | io_in_fault_0_undef | io_in_fault_0_rvv;
endmodule

