// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LsuV3(
  input          clock,
                 reset,
  output         io_req_0_ready,
  input          io_req_0_valid,
                 io_req_0_bits_store,
  input  [4:0]   io_req_0_bits_addr,
                 io_req_0_bits_op,
  input  [31:0]  io_req_0_bits_pc,
  input  [2:0]   io_req_0_bits_elemWidth,
                 io_req_0_bits_nfields,
  input  [4:0]   io_req_0_bits_bit24To20,
  input  [31:0]  io_busPort_addr_0,
                 io_busPort_data_0,
  output         io_rd_valid,
  output [4:0]   io_rd_bits_addr,
  output [31:0]  io_rd_bits_data,
  output         io_ibus_valid,
  input          io_ibus_ready,
  output [31:0]  io_ibus_addr,
  input  [127:0] io_ibus_rdata,
  output         io_dbus_valid,
                 io_dbus_write,
  output [31:0]  io_dbus_addr,
  output [127:0] io_dbus_wdata,
  output [15:0]  io_dbus_wmask,
  input  [127:0] io_dbus_rdata,
  output         io_fault_valid,
                 io_fault_bits_write,
  output [31:0]  io_fault_bits_addr,
                 io_fault_bits_epc,
  output         io_ebus_dbus_valid,
  input          io_ebus_dbus_ready,
  output         io_ebus_dbus_write,
  output [31:0]  io_ebus_dbus_pc,
                 io_ebus_dbus_addr,
  output [4:0]   io_ebus_dbus_size,
  output [127:0] io_ebus_dbus_wdata,
  output [15:0]  io_ebus_dbus_wmask,
  input  [127:0] io_ebus_dbus_rdata,
  input          io_ebus_fault_valid,
                 io_ebus_fault_bits_write,
  input  [31:0]  io_ebus_fault_bits_addr,
                 io_ebus_fault_bits_epc,
  output         io_rvv2lsu_0_ready,
  input          io_rvv2lsu_0_valid,
                 io_rvv2lsu_0_bits_idx_valid,
  input  [127:0] io_rvv2lsu_0_bits_idx_bits_data,
  input          io_rvv2lsu_0_bits_vregfile_valid,
  input  [127:0] io_rvv2lsu_0_bits_vregfile_bits_data,
  input          io_rvv2lsu_0_bits_mask_valid,
  input  [15:0]  io_rvv2lsu_0_bits_mask_bits,
  input          io_lsu2rvv_0_ready,
  output         io_lsu2rvv_0_valid,
  output [4:0]   io_lsu2rvv_0_bits_addr,
  output [127:0] io_lsu2rvv_0_bits_data,
  output         io_lsu2rvv_0_bits_last,
  input  [2:0]   io_rvvState_bits_sew,
                 io_rvvState_bits_lmul,
                 io_rvvState_bits_lmul_orig,
  output [2:0]   io_queueCapacity,
  output         io_active,
                 io_storeComplete_valid,
  output [31:0]  io_storeComplete_bits
);

  wire         _slot_io_uop_ready;
  wire         _slot_io_busReq_valid;
  wire [27:0]  _slot_io_busReq_bits_rowAddr;
  wire         _slot_io_busReq_bits_write;
  wire [127:0] _slot_io_busReq_bits_wdata;
  wire [15:0]  _slot_io_busReq_bits_wmask;
  wire [31:0]  _slot_io_pc;
  wire         _slot_io_active;
  wire         _alignedOps_aligner_out_0_valid;
  wire [122:0] _alignedOps_aligner_out_0_bits;
  wire [2:0]   _rs_io_nEnqueued;
  wire [2:0]   _rs_io_nSpace;
  wire [4:0]   _rs_io_dataOut_0_rd;
  wire [4:0]   _rs_io_dataOut_0_op;
  wire [31:0]  _rs_io_dataOut_0_pc;
  wire [31:0]  _rs_io_dataOut_0_addr;
  wire [31:0]  _rs_io_dataOut_0_data;
  wire [2:0]   _rs_io_dataOut_0_elemWidth;
  wire [2:0]   _rs_io_dataOut_0_sew;
  wire [2:0]   _rs_io_dataOut_0_emul_data;
  wire [2:0]   _rs_io_dataOut_0_emul_data_orig;
  wire [2:0]   _rs_io_dataOut_0_nfields;
  wire         _rs_io_dataOut_0_strict;
  wire         _ops_result_emul_data_orig_emul_data_T_5 = io_req_0_bits_elemWidth == 3'h0;
  wire         _ops_result_emul_data_orig_emul_data_T_9 = io_rvvState_bits_sew == 3'h2;
  wire         _ops_result_emul_data_emul_data_T_2 =
    _ops_result_emul_data_orig_emul_data_T_5 & _ops_result_emul_data_orig_emul_data_T_9;
  wire         _ops_result_emul_data_orig_emul_data_T_18 = io_rvvState_bits_sew == 3'h1;
  wire         _ops_result_emul_data_orig_emul_data_T_14 =
    io_req_0_bits_elemWidth == 3'h5;
  wire         _ops_result_emul_data_emul_data_T_11 =
    _ops_result_emul_data_orig_emul_data_T_5 & _ops_result_emul_data_orig_emul_data_T_18
    | _ops_result_emul_data_orig_emul_data_T_14
    & _ops_result_emul_data_orig_emul_data_T_9;
  wire         _ops_result_emul_data_orig_emul_data_T_24 = io_rvvState_bits_sew == 3'h0;
  wire         _ops_result_emul_data_orig_emul_data_T_23 =
    io_req_0_bits_elemWidth == 3'h6;
  wire         _ops_result_emul_data_emul_data_T_20 =
    _ops_result_emul_data_orig_emul_data_T_14 & _ops_result_emul_data_orig_emul_data_T_24
    | _ops_result_emul_data_orig_emul_data_T_23
    & _ops_result_emul_data_orig_emul_data_T_18;
  wire         _ops_result_emul_data_emul_data_T_25 =
    _ops_result_emul_data_orig_emul_data_T_23 & _ops_result_emul_data_orig_emul_data_T_24;
  wire         _ops_result_nfields_T = io_req_0_bits_bit24To20 == 5'hB;
  wire         _ops_result_nfields_T_7 = io_req_0_bits_op == 5'hD;
  wire         _ops_result_nfields_T_8 = io_req_0_bits_op == 5'h11;
  wire         _ops_result_nfields_T_6 = io_req_0_bits_bit24To20 == 5'h8;
  wire         _ops_result_emul_data_orig_T_30 = io_req_0_bits_nfields == 3'h1;
  wire         _ops_result_emul_data_orig_T_14 = io_req_0_bits_nfields == 3'h3;
  wire [1:0]   _GEN = {1'h0, _ops_result_emul_data_orig_T_30};
  wire         _ops_result_strict_T = io_req_0_bits_op == 5'hE;
  wire         _ops_result_strict_T_1 = io_req_0_bits_op == 5'h12;
  wire         _ops_result_emul_data_orig_emul_data_T_2 =
    _ops_result_emul_data_orig_emul_data_T_5 & _ops_result_emul_data_orig_emul_data_T_9;
  wire         _ops_result_emul_data_orig_emul_data_T_11 =
    _ops_result_emul_data_orig_emul_data_T_5 & _ops_result_emul_data_orig_emul_data_T_18
    | _ops_result_emul_data_orig_emul_data_T_14
    & _ops_result_emul_data_orig_emul_data_T_9;
  wire         _ops_result_emul_data_orig_emul_data_T_20 =
    _ops_result_emul_data_orig_emul_data_T_14 & _ops_result_emul_data_orig_emul_data_T_24
    | _ops_result_emul_data_orig_emul_data_T_23
    & _ops_result_emul_data_orig_emul_data_T_18;
  wire         _ops_result_emul_data_orig_emul_data_T_25 =
    _ops_result_emul_data_orig_emul_data_T_23 & _ops_result_emul_data_orig_emul_data_T_24;
  wire         _ops_result_nfields_T_5 =
    _ops_result_nfields_T & (|{_ops_result_nfields_T_8, _ops_result_nfields_T_7});
  wire         _ops_result_nfields_T_11 =
    _ops_result_nfields_T_6 & (|{_ops_result_nfields_T_8, _ops_result_nfields_T_7});
  wire [31:0]  addr = {_slot_io_busReq_bits_rowAddr, 4'h0};
  wire         itcm = addr < 32'h2000;
  wire         dtcm = (|(_slot_io_busReq_bits_rowAddr[27:12])) & addr < 32'h18000;
  wire         ibusFault_y = _slot_io_busReq_valid & _slot_io_busReq_bits_write & itcm;
  reg          faultReg_valid;
  reg          faultReg_bits_write;
  reg  [31:0]  faultReg_bits_addr;
  reg  [31:0]  faultReg_bits_epc;
  wire         io_ibus_valid_0 =
    itcm & _slot_io_busReq_valid & ~_slot_io_busReq_bits_write;
  reg          ibusResp;
  wire         io_dbus_valid_0 = dtcm & _slot_io_busReq_valid;
  reg          dbusResp;
  wire         _slot_io_busReq_ready_defaultSel_T = itcm | dtcm;
  wire [3:0]   _ebus_offset_T_29 =
    _slot_io_busReq_bits_wmask[1]
      ? 4'h1
      : _slot_io_busReq_bits_wmask[2]
          ? 4'h2
          : _slot_io_busReq_bits_wmask[3]
              ? 4'h3
              : _slot_io_busReq_bits_wmask[4]
                  ? 4'h4
                  : _slot_io_busReq_bits_wmask[5]
                      ? 4'h5
                      : _slot_io_busReq_bits_wmask[6]
                          ? 4'h6
                          : _slot_io_busReq_bits_wmask[7]
                              ? 4'h7
                              : _slot_io_busReq_bits_wmask[8]
                                  ? 4'h8
                                  : _slot_io_busReq_bits_wmask[9]
                                      ? 4'h9
                                      : _slot_io_busReq_bits_wmask[10]
                                          ? 4'hA
                                          : _slot_io_busReq_bits_wmask[11]
                                              ? 4'hB
                                              : _slot_io_busReq_bits_wmask[12]
                                                  ? 4'hC
                                                  : _slot_io_busReq_bits_wmask[13]
                                                      ? 4'hD
                                                      : {3'h7,
                                                         ~(_slot_io_busReq_bits_wmask[14])};
  wire [3:0]   ebus_offset = _slot_io_busReq_bits_wmask[0] ? 4'h0 : _ebus_offset_T_29;
  wire [15:0]  _ebus_last_T_8 =
    {8'h0, _slot_io_busReq_bits_wmask[15:8]} | {_slot_io_busReq_bits_wmask[7:0], 8'h0};
  wire [15:0]  _ebus_last_T_18 =
    {4'h0, _ebus_last_T_8[15:4] & 12'hF0F} | {_ebus_last_T_8[11:0] & 12'hF0F, 4'h0};
  wire [15:0]  _ebus_last_T_28 =
    {2'h0, _ebus_last_T_18[15:2] & 14'h3333} | {_ebus_last_T_18[13:0] & 14'h3333, 2'h0};
  wire [14:0]  _ebus_last_T_38 =
    _ebus_last_T_28[15:1] & 15'h5555 | {1'h0, _ebus_last_T_28[12:0] & 13'h1555, 1'h0};
  wire [4:0]   _ebus_span_T_2 =
    5'h10
    - {1'h0,
       _ebus_last_T_38[0]
         ? 4'h0
         : _ebus_last_T_38[1]
             ? 4'h1
             : _ebus_last_T_38[2]
                 ? 4'h2
                 : _ebus_last_T_38[3]
                     ? 4'h3
                     : _ebus_last_T_38[4]
                         ? 4'h4
                         : _ebus_last_T_38[5]
                             ? 4'h5
                             : _ebus_last_T_38[6]
                                 ? 4'h6
                                 : _ebus_last_T_38[7]
                                     ? 4'h7
                                     : _ebus_last_T_38[8]
                                         ? 4'h8
                                         : _ebus_last_T_38[9]
                                             ? 4'h9
                                             : _ebus_last_T_38[10]
                                                 ? 4'hA
                                                 : _ebus_last_T_38[11]
                                                     ? 4'hB
                                                     : _ebus_last_T_38[12]
                                                         ? 4'hC
                                                         : _ebus_last_T_38[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_ebus_last_T_38[14])}}
    - {1'h0, ebus_offset};
  wire         _ebus_size_T_2 =
    _slot_io_busReq_bits_wmask == 16'h0 | _ebus_span_T_2 > 5'h4;
  wire         _ebus_size_T_6 = _ebus_span_T_2 == 5'h4 & (|(ebus_offset[1:0]));
  wire         _ebus_size_T_10 = _ebus_span_T_2 == 5'h3;
  wire         _ebus_size_T_9 = _ebus_size_T_10 & ebus_offset[1];
  wire         _ebus_size_T_13 = _ebus_size_T_10 & ~(ebus_offset[1]);
  wire         _ebus_size_T_16 = _ebus_span_T_2 == 5'h2 & ebus_offset[0];
  wire [4:0]   _ebus_size_T_35 =
    {_ebus_size_T_2, 4'h0} | {_ebus_size_T_6, 4'h0} | {_ebus_size_T_9, 4'h0};
  wire [4:0]   ebus_size =
    {_ebus_size_T_35[4:3],
     _ebus_size_T_35[2:0] | {_ebus_size_T_13, 2'h0} | {_ebus_size_T_16, 2'h0}}
    | (_ebus_size_T_2 | _ebus_size_T_6 | _ebus_size_T_9 | _ebus_size_T_13
       | _ebus_size_T_16
         ? 5'h0
         : _ebus_span_T_2);
  wire         io_ebus_dbus_valid_0 =
    ~_slot_io_busReq_ready_defaultSel_T & _slot_io_busReq_valid;
  reg          ebusResp;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      faultReg_valid <= 1'h0;
      faultReg_bits_write <= 1'h0;
      faultReg_bits_addr <= 32'h0;
      faultReg_bits_epc <= 32'h0;
      ibusResp <= 1'h0;
      dbusResp <= 1'h0;
      ebusResp <= 1'h0;
    end
    else begin
      faultReg_valid <= io_ebus_fault_valid ? io_ebus_fault_valid : ibusFault_y;
      faultReg_bits_write <= io_ebus_fault_valid ? io_ebus_fault_bits_write : ibusFault_y;
      faultReg_bits_addr <=
        io_ebus_fault_valid
          ? io_ebus_fault_bits_addr
          : ibusFault_y ? {4'h0, _slot_io_busReq_bits_rowAddr} : 32'h0;
      faultReg_bits_epc <=
        io_ebus_fault_valid ? io_ebus_fault_bits_epc : ibusFault_y ? _slot_io_pc : 32'h0;
      ibusResp <= io_ibus_valid_0 & io_ibus_ready | ibusFault_y;
      dbusResp <= io_dbus_valid_0;
      ebusResp <= io_ebus_dbus_valid_0 & io_ebus_dbus_ready;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        faultReg_valid = _RANDOM[2'h0][0];
        faultReg_bits_write = _RANDOM[2'h0][1];
        faultReg_bits_addr = {_RANDOM[2'h0][31:2], _RANDOM[2'h1][1:0]};
        faultReg_bits_epc = {_RANDOM[2'h1][31:2], _RANDOM[2'h2][1:0]};
        ibusResp = _RANDOM[2'h2][2];
        dbusResp = _RANDOM[2'h2][3];
        ebusResp = _RANDOM[2'h2][4];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        faultReg_valid = 1'h0;
        faultReg_bits_write = 1'h0;
        faultReg_bits_addr = 32'h0;
        faultReg_bits_epc = 32'h0;
        ibusResp = 1'h0;
        dbusResp = 1'h0;
        ebusResp = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CircularBufferMulti_1 rs (
    .clock                       (clock),
    .reset                       (reset),
    .io_enqValid                 (_alignedOps_aligner_out_0_valid),
    .io_enqData_0_store          (_alignedOps_aligner_out_0_bits[122]),
    .io_enqData_0_rd             (_alignedOps_aligner_out_0_bits[121:117]),
    .io_enqData_0_op             (_alignedOps_aligner_out_0_bits[116:112]),
    .io_enqData_0_pc             (_alignedOps_aligner_out_0_bits[111:80]),
    .io_enqData_0_addr           (_alignedOps_aligner_out_0_bits[79:48]),
    .io_enqData_0_data           (_alignedOps_aligner_out_0_bits[47:16]),
    .io_enqData_0_elemWidth      (_alignedOps_aligner_out_0_bits[15:13]),
    .io_enqData_0_sew            (_alignedOps_aligner_out_0_bits[12:10]),
    .io_enqData_0_emul_data      (_alignedOps_aligner_out_0_bits[9:7]),
    .io_enqData_0_emul_data_orig (_alignedOps_aligner_out_0_bits[6:4]),
    .io_enqData_0_nfields        (_alignedOps_aligner_out_0_bits[3:1]),
    .io_enqData_0_strict         (_alignedOps_aligner_out_0_bits[0]),
    .io_nEnqueued                (_rs_io_nEnqueued),
    .io_nSpace                   (_rs_io_nSpace),
    .io_dataOut_0_store          (/* unused */),
    .io_dataOut_0_rd             (_rs_io_dataOut_0_rd),
    .io_dataOut_0_op             (_rs_io_dataOut_0_op),
    .io_dataOut_0_pc             (_rs_io_dataOut_0_pc),
    .io_dataOut_0_addr           (_rs_io_dataOut_0_addr),
    .io_dataOut_0_data           (_rs_io_dataOut_0_data),
    .io_dataOut_0_elemWidth      (_rs_io_dataOut_0_elemWidth),
    .io_dataOut_0_sew            (_rs_io_dataOut_0_sew),
    .io_dataOut_0_emul_data      (_rs_io_dataOut_0_emul_data),
    .io_dataOut_0_emul_data_orig (_rs_io_dataOut_0_emul_data_orig),
    .io_dataOut_0_nfields        (_rs_io_dataOut_0_nfields),
    .io_dataOut_0_strict         (_rs_io_dataOut_0_strict),
    .io_deqReady                 (_slot_io_uop_ready & (|_rs_io_nEnqueued)),
    .io_flush                    (1'h0)
  );
  Aligner_123_1 alignedOps_aligner (
    .in_0_valid  ((|_rs_io_nSpace) & io_req_0_valid),
    .in_0_bits
      ({io_req_0_bits_store,
        io_req_0_bits_addr,
        io_req_0_bits_op,
        io_req_0_bits_pc,
        io_busPort_addr_0,
        io_busPort_data_0,
        io_req_0_bits_elemWidth,
        io_rvvState_bits_sew,
        _ops_result_nfields_T & (|{_ops_result_nfields_T_8, _ops_result_nfields_T_7})
          ? 3'h0
          : _ops_result_nfields_T_6
            & (|{_ops_result_nfields_T_8, _ops_result_nfields_T_7})
              ? {1'h0,
                 _GEN | {_ops_result_emul_data_orig_T_14, 1'h0}
                   | {2{&io_req_0_bits_nfields}}}
              : (|{_ops_result_strict_T_1,
                   _ops_result_nfields_T_8,
                   _ops_result_strict_T,
                   _ops_result_nfields_T_7})
                  ? (_ops_result_emul_data_emul_data_T_2
                       ? io_rvvState_bits_lmul - 3'h2
                       : 3'h0)
                    | (_ops_result_emul_data_emul_data_T_11
                         ? io_rvvState_bits_lmul - 3'h1
                         : 3'h0)
                    | (_ops_result_emul_data_emul_data_T_20
                         ? io_rvvState_bits_lmul + 3'h1
                         : 3'h0)
                    | (_ops_result_emul_data_emul_data_T_25
                         ? io_rvvState_bits_lmul + 3'h2
                         : 3'h0)
                    | (_ops_result_emul_data_emul_data_T_2
                       | _ops_result_emul_data_emul_data_T_11
                       | _ops_result_emul_data_emul_data_T_20
                       | _ops_result_emul_data_emul_data_T_25
                         ? 3'h0
                         : io_rvvState_bits_lmul)
                  : io_rvvState_bits_lmul,
        _ops_result_nfields_T & (|{_ops_result_nfields_T_8, _ops_result_nfields_T_7})
          ? 3'h0
          : _ops_result_nfields_T_6
            & (|{_ops_result_nfields_T_8, _ops_result_nfields_T_7})
              ? {1'h0,
                 _GEN | {_ops_result_emul_data_orig_T_14, 1'h0}
                   | {2{&io_req_0_bits_nfields}}}
              : (|{_ops_result_strict_T_1,
                   _ops_result_nfields_T_8,
                   _ops_result_strict_T,
                   _ops_result_nfields_T_7})
                  ? (_ops_result_emul_data_orig_emul_data_T_2
                       ? io_rvvState_bits_lmul_orig - 3'h2
                       : 3'h0)
                    | (_ops_result_emul_data_orig_emul_data_T_11
                         ? io_rvvState_bits_lmul_orig - 3'h1
                         : 3'h0)
                    | (_ops_result_emul_data_orig_emul_data_T_20
                         ? io_rvvState_bits_lmul_orig + 3'h1
                         : 3'h0)
                    | (_ops_result_emul_data_orig_emul_data_T_25
                         ? io_rvvState_bits_lmul_orig + 3'h2
                         : 3'h0)
                    | (_ops_result_emul_data_orig_emul_data_T_2
                       | _ops_result_emul_data_orig_emul_data_T_11
                       | _ops_result_emul_data_orig_emul_data_T_20
                       | _ops_result_emul_data_orig_emul_data_T_25
                         ? 3'h0
                         : io_rvvState_bits_lmul_orig)
                  : io_rvvState_bits_lmul_orig,
        _ops_result_nfields_T_5 | _ops_result_nfields_T_11 ? 3'h0 : io_req_0_bits_nfields,
        (|{_ops_result_strict_T_1, _ops_result_strict_T}) & (|io_req_0_bits_bit24To20)
          & io_busPort_data_0 == 32'h0}),
    .out_0_valid (_alignedOps_aligner_out_0_valid),
    .out_0_bits  (_alignedOps_aligner_out_0_bits)
  );
  LsuSuperSlot slot (
    .clock                                 (clock),
    .reset                                 (reset),
    .io_uop_ready                          (_slot_io_uop_ready),
    .io_uop_valid                          (|_rs_io_nEnqueued),
    .io_uop_bits_rd                        (_rs_io_dataOut_0_rd),
    .io_uop_bits_op                        (_rs_io_dataOut_0_op),
    .io_uop_bits_pc                        (_rs_io_dataOut_0_pc),
    .io_uop_bits_addr                      (_rs_io_dataOut_0_addr),
    .io_uop_bits_data                      (_rs_io_dataOut_0_data),
    .io_uop_bits_elemWidth                 (_rs_io_dataOut_0_elemWidth),
    .io_uop_bits_sew                       (_rs_io_dataOut_0_sew),
    .io_uop_bits_emul_data                 (_rs_io_dataOut_0_emul_data),
    .io_uop_bits_emul_data_orig            (_rs_io_dataOut_0_emul_data_orig),
    .io_uop_bits_nfields                   (_rs_io_dataOut_0_nfields),
    .io_uop_bits_strict                    (_rs_io_dataOut_0_strict),
    .io_vectorData_ready                   (io_rvv2lsu_0_ready),
    .io_vectorData_valid                   (io_rvv2lsu_0_valid),
    .io_vectorData_bits_idx_valid          (io_rvv2lsu_0_bits_idx_valid),
    .io_vectorData_bits_idx_bits_data      (io_rvv2lsu_0_bits_idx_bits_data),
    .io_vectorData_bits_vregfile_valid     (io_rvv2lsu_0_bits_vregfile_valid),
    .io_vectorData_bits_vregfile_bits_data (io_rvv2lsu_0_bits_vregfile_bits_data),
    .io_vectorData_bits_mask_valid         (io_rvv2lsu_0_bits_mask_valid),
    .io_vectorData_bits_mask_bits          (io_rvv2lsu_0_bits_mask_bits),
    .io_busReq_ready
      (itcm & (io_ibus_ready | ibusFault_y) | dtcm | ~_slot_io_busReq_ready_defaultSel_T
       & io_ebus_dbus_ready),
    .io_busReq_valid                       (_slot_io_busReq_valid),
    .io_busReq_bits_rowAddr                (_slot_io_busReq_bits_rowAddr),
    .io_busReq_bits_write                  (_slot_io_busReq_bits_write),
    .io_busReq_bits_wdata                  (_slot_io_busReq_bits_wdata),
    .io_busReq_bits_wmask                  (_slot_io_busReq_bits_wmask),
    .io_busResp_valid                      (ibusResp | dbusResp | ebusResp),
    .io_busResp_bits_rdata
      ((ibusResp ? io_ibus_rdata : 128'h0) | (dbusResp ? io_dbus_rdata : 128'h0)
       | (ebusResp ? io_ebus_dbus_rdata : 128'h0)),
    .io_busResp_bits_fault                 (faultReg_valid),
    .io_intWriteback_valid                 (io_rd_valid),
    .io_intWriteback_bits_addr             (io_rd_bits_addr),
    .io_intWriteback_bits_data             (io_rd_bits_data),
    .io_vectorWriteback_ready              (io_lsu2rvv_0_ready),
    .io_vectorWriteback_valid              (io_lsu2rvv_0_valid),
    .io_vectorWriteback_bits_addr          (io_lsu2rvv_0_bits_addr),
    .io_vectorWriteback_bits_data          (io_lsu2rvv_0_bits_data),
    .io_vectorWriteback_bits_last          (io_lsu2rvv_0_bits_last),
    .io_pc                                 (_slot_io_pc),
    .io_active                             (_slot_io_active),
    .io_storeComplete                      (io_storeComplete_valid)
  );
  assign io_req_0_ready = |_rs_io_nSpace;
  assign io_ibus_valid = io_ibus_valid_0;
  assign io_ibus_addr = addr;
  assign io_dbus_valid = io_dbus_valid_0;
  assign io_dbus_write = _slot_io_busReq_bits_write;
  assign io_dbus_addr = addr;
  assign io_dbus_wdata = _slot_io_busReq_bits_wdata;
  assign io_dbus_wmask = _slot_io_busReq_bits_wmask;
  assign io_fault_valid = faultReg_valid;
  assign io_fault_bits_write = faultReg_bits_write;
  assign io_fault_bits_addr = faultReg_bits_addr;
  assign io_fault_bits_epc = faultReg_bits_epc;
  assign io_ebus_dbus_valid = io_ebus_dbus_valid_0;
  assign io_ebus_dbus_write = _slot_io_busReq_bits_write;
  assign io_ebus_dbus_pc = _slot_io_pc;
  assign io_ebus_dbus_addr =
    {_slot_io_busReq_bits_rowAddr, 4'h0}
    + {28'h0,
       ebus_size == 5'h4
         ? ebus_offset & 4'hC
         : ebus_size == 5'h2
             ? ebus_offset & 4'hE
             : ebus_size != 5'h1 | _slot_io_busReq_bits_wmask[0]
                 ? 4'h0
                 : _ebus_offset_T_29};
  assign io_ebus_dbus_size = ebus_size;
  assign io_ebus_dbus_wdata = _slot_io_busReq_bits_wdata;
  assign io_ebus_dbus_wmask = _slot_io_busReq_bits_wmask;
  assign io_queueCapacity = _rs_io_nSpace;
  assign io_active = (|_rs_io_nEnqueued) | ~_slot_io_active;
  assign io_storeComplete_bits = _slot_io_pc;
endmodule

