// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
module Mlu(
  input         clock,
                reset,
                io_req_0_valid,
  input  [4:0]  io_req_0_bits_addr,
  input  [2:0]  io_req_0_bits_op,
  input         io_rs1_0_valid,
  input  [31:0] io_rs1_0_data,
  input         io_rs2_0_valid,
  input  [31:0] io_rs2_0_data,
  output        io_rd_valid,
  output [4:0]  io_rd_bits_addr,
  output [31:0] io_rd_bits_data
);

  wire [2:0]  _stage3Input_q_io_deq_bits_op;
  wire [65:0] _stage3Input_q_io_deq_bits_prod;
  wire        _stage2Input_q_io_deq_valid;
  wire [4:0]  _stage2Input_q_io_deq_bits_rd;
  wire [2:0]  _stage2Input_q_io_deq_bits_op;
  wire        _stage2Input_q_io_deq_bits_sel;
  wire        _arb_io_out_valid;
  wire [4:0]  _arb_io_out_bits_addr;
  wire [2:0]  _arb_io_out_bits_op;
  wire [31:0] rs1 =
    _stage2Input_q_io_deq_valid & _stage2Input_q_io_deq_bits_sel ? io_rs1_0_data : 32'h0;
  wire [31:0] rs2 =
    _stage2Input_q_io_deq_valid & _stage2Input_q_io_deq_bits_sel ? io_rs2_0_data : 32'h0;
  wire        rs2signed = _stage2Input_q_io_deq_bits_op == 3'h1;
  Arbiter1_MluCmd arb (
    .io_in_0_valid     (io_req_0_valid),
    .io_in_0_bits_addr (io_req_0_bits_addr),
    .io_in_0_bits_op   (io_req_0_bits_op),
    .io_out_valid      (_arb_io_out_valid),
    .io_out_bits_addr  (_arb_io_out_bits_addr),
    .io_out_bits_op    (_arb_io_out_bits_op)
  );
  Queue1_MluStage1 stage2Input_q (
    .clock           (clock),
    .reset           (reset),
    .io_enq_valid    (_arb_io_out_valid),
    .io_enq_bits_rd  (_arb_io_out_bits_addr),
    .io_enq_bits_op  (_arb_io_out_bits_op),
    .io_deq_valid    (_stage2Input_q_io_deq_valid),
    .io_deq_bits_rd  (_stage2Input_q_io_deq_bits_rd),
    .io_deq_bits_op  (_stage2Input_q_io_deq_bits_op),
    .io_deq_bits_sel (_stage2Input_q_io_deq_bits_sel)
  );
  Queue1_MluStage2 stage3Input_q (
    .clock            (clock),
    .reset            (reset),
    .io_enq_valid     (_stage2Input_q_io_deq_valid),
    .io_enq_bits_rd   (_stage2Input_q_io_deq_bits_rd),
    .io_enq_bits_op   (_stage2Input_q_io_deq_bits_op),
    .io_enq_bits_prod
      ({{34{(_stage2Input_q_io_deq_bits_op == 3'h2 | rs2signed) & rs1[31]}}, rs1}
       * {{34{rs2signed & rs2[31]}}, rs2}),
    .io_deq_valid     (io_rd_valid),
    .io_deq_bits_rd   (io_rd_bits_addr),
    .io_deq_bits_op   (_stage3Input_q_io_deq_bits_op),
    .io_deq_bits_prod (_stage3Input_q_io_deq_bits_prod)
  );
  assign io_rd_bits_data =
    _stage3Input_q_io_deq_bits_op == 3'h0
      ? _stage3Input_q_io_deq_bits_prod[31:0]
      : _stage3Input_q_io_deq_bits_prod[63:32];
endmodule

