// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Regfile(
  input         clock,
                reset,
                io_readAddr_0_valid,
  input  [4:0]  io_readAddr_0_addr,
  input         io_readAddr_1_valid,
  input  [4:0]  io_readAddr_1_addr,
  input         io_readSet_0_valid,
  input  [31:0] io_readSet_0_value,
  input         io_readSet_1_valid,
  input  [31:0] io_readSet_1_value,
  input         io_writeAddr_0_valid,
  input  [4:0]  io_writeAddr_0_addr,
  input         io_busAddr_0_immen,
  input  [31:0] io_busAddr_0_immed,
  output [31:0] io_target_0_data,
                io_busPort_addr_0,
                io_busPort_data_0,
  input  [4:0]  io_debugBusPort_idx,
  output [31:0] io_debugBusPort_data,
  input         io_debugWriteValid,
  output        io_readData_0_valid,
  output [31:0] io_readData_0_data,
  output        io_readData_1_valid,
  output [31:0] io_readData_1_data,
  input         io_writeData_0_valid,
  input  [4:0]  io_writeData_0_bits_addr,
  input  [31:0] io_writeData_0_bits_data,
  input         io_writeData_1_valid,
  input  [4:0]  io_writeData_1_bits_addr,
  input  [31:0] io_writeData_1_bits_data,
  input         io_writeData_2_valid,
  input  [4:0]  io_writeData_2_bits_addr,
  input  [31:0] io_writeData_2_bits_data,
  input         io_writeMask_2_valid,
  output [31:0] io_scoreboard_regd,
                io_scoreboard_comb
);

  reg  [31:0] regfile_1;
  reg  [31:0] regfile_2;
  reg  [31:0] regfile_3;
  reg  [31:0] regfile_4;
  reg  [31:0] regfile_5;
  reg  [31:0] regfile_6;
  reg  [31:0] regfile_7;
  reg  [31:0] regfile_8;
  reg  [31:0] regfile_9;
  reg  [31:0] regfile_10;
  reg  [31:0] regfile_11;
  reg  [31:0] regfile_12;
  reg  [31:0] regfile_13;
  reg  [31:0] regfile_14;
  reg  [31:0] regfile_15;
  reg  [31:0] regfile_16;
  reg  [31:0] regfile_17;
  reg  [31:0] regfile_18;
  reg  [31:0] regfile_19;
  reg  [31:0] regfile_20;
  reg  [31:0] regfile_21;
  reg  [31:0] regfile_22;
  reg  [31:0] regfile_23;
  reg  [31:0] regfile_24;
  reg  [31:0] regfile_25;
  reg  [31:0] regfile_26;
  reg  [31:0] regfile_27;
  reg  [31:0] regfile_28;
  reg  [31:0] regfile_29;
  reg  [31:0] regfile_30;
  reg  [31:0] regfile_31;
  reg  [31:0] scoreboard;
  wire [31:0] _scoreboard_clr0_T_1 = 32'h1 << io_writeData_0_bits_addr;
  wire [31:0] _scoreboard_clr0_T_4 = 32'h1 << io_writeData_1_bits_addr;
  wire [31:0] _scoreboard_clr0_T_7 = 32'h1 << io_writeData_2_bits_addr;
  wire [30:0] scoreboard_clr0 =
    (io_writeData_0_valid ? _scoreboard_clr0_T_1[31:1] : 31'h0)
    | (io_writeData_1_valid ? _scoreboard_clr0_T_4[31:1] : 31'h0)
    | (io_writeData_2_valid ? _scoreboard_clr0_T_7[31:1] : 31'h0);
  reg         readDataReady_0;
  reg         readDataReady_1;
  reg  [31:0] readDataBits_0;
  reg  [31:0] readDataBits_1;
  wire        _valid_T = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h1;
  wire        _valid_T_2 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h1;
  wire        valid_2 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h1 & ~io_writeMask_2_valid;
  wire [31:0] data =
    (_valid_T ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_2 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_1_T = {_valid_T, _valid_T_2, valid_2};
  wire        _valid_T_6 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h2;
  wire        _valid_T_8 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h2;
  wire        valid_2_1 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h2 & ~io_writeMask_2_valid;
  wire [31:0] data_1 =
    (_valid_T_6 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_8 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_1 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_2_T = {_valid_T_6, _valid_T_8, valid_2_1};
  wire        _valid_T_12 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h3;
  wire        _valid_T_14 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h3;
  wire        valid_2_2 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h3 & ~io_writeMask_2_valid;
  wire [31:0] data_2 =
    (_valid_T_12 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_14 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_2 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_3_T = {_valid_T_12, _valid_T_14, valid_2_2};
  wire        _valid_T_18 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h4;
  wire        _valid_T_20 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h4;
  wire        valid_2_3 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h4 & ~io_writeMask_2_valid;
  wire [31:0] data_3 =
    (_valid_T_18 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_20 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_3 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_4_T = {_valid_T_18, _valid_T_20, valid_2_3};
  wire        _valid_T_24 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h5;
  wire        _valid_T_26 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h5;
  wire        valid_2_4 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h5 & ~io_writeMask_2_valid;
  wire [31:0] data_4 =
    (_valid_T_24 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_26 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_4 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_5_T = {_valid_T_24, _valid_T_26, valid_2_4};
  wire        _valid_T_30 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h6;
  wire        _valid_T_32 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h6;
  wire        valid_2_5 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h6 & ~io_writeMask_2_valid;
  wire [31:0] data_5 =
    (_valid_T_30 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_32 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_5 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_6_T = {_valid_T_30, _valid_T_32, valid_2_5};
  wire        _valid_T_36 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h7;
  wire        _valid_T_38 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h7;
  wire        valid_2_6 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h7 & ~io_writeMask_2_valid;
  wire [31:0] data_6 =
    (_valid_T_36 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_38 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_6 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_7_T = {_valid_T_36, _valid_T_38, valid_2_6};
  wire        _valid_T_42 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h8;
  wire        _valid_T_44 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h8;
  wire        valid_2_7 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h8 & ~io_writeMask_2_valid;
  wire [31:0] data_7 =
    (_valid_T_42 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_44 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_7 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_8_T = {_valid_T_42, _valid_T_44, valid_2_7};
  wire        _valid_T_48 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h9;
  wire        _valid_T_50 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h9;
  wire        valid_2_8 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h9 & ~io_writeMask_2_valid;
  wire [31:0] data_8 =
    (_valid_T_48 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_50 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_8 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_9_T = {_valid_T_48, _valid_T_50, valid_2_8};
  wire        _valid_T_54 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'hA;
  wire        _valid_T_56 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'hA;
  wire        valid_2_9 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'hA & ~io_writeMask_2_valid;
  wire [31:0] data_9 =
    (_valid_T_54 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_56 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_9 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_10_T = {_valid_T_54, _valid_T_56, valid_2_9};
  wire        _valid_T_60 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'hB;
  wire        _valid_T_62 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'hB;
  wire        valid_2_10 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'hB & ~io_writeMask_2_valid;
  wire [31:0] data_10 =
    (_valid_T_60 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_62 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_10 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_11_T = {_valid_T_60, _valid_T_62, valid_2_10};
  wire        _valid_T_66 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'hC;
  wire        _valid_T_68 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'hC;
  wire        valid_2_11 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'hC & ~io_writeMask_2_valid;
  wire [31:0] data_11 =
    (_valid_T_66 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_68 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_11 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_12_T = {_valid_T_66, _valid_T_68, valid_2_11};
  wire        _valid_T_72 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'hD;
  wire        _valid_T_74 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'hD;
  wire        valid_2_12 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'hD & ~io_writeMask_2_valid;
  wire [31:0] data_12 =
    (_valid_T_72 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_74 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_12 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_13_T = {_valid_T_72, _valid_T_74, valid_2_12};
  wire        _valid_T_78 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'hE;
  wire        _valid_T_80 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'hE;
  wire        valid_2_13 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'hE & ~io_writeMask_2_valid;
  wire [31:0] data_13 =
    (_valid_T_78 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_80 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_13 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_14_T = {_valid_T_78, _valid_T_80, valid_2_13};
  wire        _valid_T_84 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'hF;
  wire        _valid_T_86 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'hF;
  wire        valid_2_14 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'hF & ~io_writeMask_2_valid;
  wire [31:0] data_14 =
    (_valid_T_84 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_86 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_14 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_15_T = {_valid_T_84, _valid_T_86, valid_2_14};
  wire        _valid_T_90 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h10;
  wire        _valid_T_92 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h10;
  wire        valid_2_15 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h10 & ~io_writeMask_2_valid;
  wire [31:0] data_15 =
    (_valid_T_90 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_92 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_15 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_16_T = {_valid_T_90, _valid_T_92, valid_2_15};
  wire        _valid_T_96 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h11;
  wire        _valid_T_98 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h11;
  wire        valid_2_16 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h11 & ~io_writeMask_2_valid;
  wire [31:0] data_16 =
    (_valid_T_96 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_98 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_16 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_17_T = {_valid_T_96, _valid_T_98, valid_2_16};
  wire        _valid_T_102 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h12;
  wire        _valid_T_104 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h12;
  wire        valid_2_17 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h12 & ~io_writeMask_2_valid;
  wire [31:0] data_17 =
    (_valid_T_102 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_104 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_17 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_18_T = {_valid_T_102, _valid_T_104, valid_2_17};
  wire        _valid_T_108 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h13;
  wire        _valid_T_110 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h13;
  wire        valid_2_18 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h13 & ~io_writeMask_2_valid;
  wire [31:0] data_18 =
    (_valid_T_108 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_110 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_18 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_19_T = {_valid_T_108, _valid_T_110, valid_2_18};
  wire        _valid_T_114 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h14;
  wire        _valid_T_116 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h14;
  wire        valid_2_19 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h14 & ~io_writeMask_2_valid;
  wire [31:0] data_19 =
    (_valid_T_114 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_116 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_19 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_20_T = {_valid_T_114, _valid_T_116, valid_2_19};
  wire        _valid_T_120 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h15;
  wire        _valid_T_122 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h15;
  wire        valid_2_20 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h15 & ~io_writeMask_2_valid;
  wire [31:0] data_20 =
    (_valid_T_120 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_122 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_20 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_21_T = {_valid_T_120, _valid_T_122, valid_2_20};
  wire        _valid_T_126 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h16;
  wire        _valid_T_128 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h16;
  wire        valid_2_21 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h16 & ~io_writeMask_2_valid;
  wire [31:0] data_21 =
    (_valid_T_126 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_128 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_21 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_22_T = {_valid_T_126, _valid_T_128, valid_2_21};
  wire        _valid_T_132 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h17;
  wire        _valid_T_134 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h17;
  wire        valid_2_22 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h17 & ~io_writeMask_2_valid;
  wire [31:0] data_22 =
    (_valid_T_132 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_134 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_22 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_23_T = {_valid_T_132, _valid_T_134, valid_2_22};
  wire        _valid_T_138 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h18;
  wire        _valid_T_140 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h18;
  wire        valid_2_23 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h18 & ~io_writeMask_2_valid;
  wire [31:0] data_23 =
    (_valid_T_138 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_140 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_23 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_24_T = {_valid_T_138, _valid_T_140, valid_2_23};
  wire        _valid_T_144 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h19;
  wire        _valid_T_146 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h19;
  wire        valid_2_24 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h19 & ~io_writeMask_2_valid;
  wire [31:0] data_24 =
    (_valid_T_144 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_146 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_24 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_25_T = {_valid_T_144, _valid_T_146, valid_2_24};
  wire        _valid_T_150 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h1A;
  wire        _valid_T_152 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h1A;
  wire        valid_2_25 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h1A & ~io_writeMask_2_valid;
  wire [31:0] data_25 =
    (_valid_T_150 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_152 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_25 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_26_T = {_valid_T_150, _valid_T_152, valid_2_25};
  wire        _valid_T_156 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h1B;
  wire        _valid_T_158 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h1B;
  wire        valid_2_26 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h1B & ~io_writeMask_2_valid;
  wire [31:0] data_26 =
    (_valid_T_156 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_158 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_26 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_27_T = {_valid_T_156, _valid_T_158, valid_2_26};
  wire        _valid_T_162 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h1C;
  wire        _valid_T_164 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h1C;
  wire        valid_2_27 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h1C & ~io_writeMask_2_valid;
  wire [31:0] data_27 =
    (_valid_T_162 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_164 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_27 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_28_T = {_valid_T_162, _valid_T_164, valid_2_27};
  wire        _valid_T_168 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h1D;
  wire        _valid_T_170 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h1D;
  wire        valid_2_28 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h1D & ~io_writeMask_2_valid;
  wire [31:0] data_28 =
    (_valid_T_168 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_170 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_28 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_29_T = {_valid_T_168, _valid_T_170, valid_2_28};
  wire        _valid_T_174 = io_writeData_0_valid & io_writeData_0_bits_addr == 5'h1E;
  wire        _valid_T_176 = io_writeData_1_valid & io_writeData_1_bits_addr == 5'h1E;
  wire        valid_2_29 =
    io_writeData_2_valid & io_writeData_2_bits_addr == 5'h1E & ~io_writeMask_2_valid;
  wire [31:0] data_29 =
    (_valid_T_174 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_176 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_29 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_30_T = {_valid_T_174, _valid_T_176, valid_2_29};
  wire        _valid_T_180 = io_writeData_0_valid & (&io_writeData_0_bits_addr);
  wire        _valid_T_182 = io_writeData_1_valid & (&io_writeData_1_bits_addr);
  wire        valid_2_30 =
    io_writeData_2_valid & (&io_writeData_2_bits_addr) & ~io_writeMask_2_valid;
  wire [31:0] data_30 =
    (_valid_T_180 ? io_writeData_0_bits_data : 32'h0)
    | (_valid_T_182 ? io_writeData_1_bits_data : 32'h0)
    | (valid_2_30 ? io_writeData_2_bits_data : 32'h0);
  wire [2:0]  _writeValid_31_T = {_valid_T_180, _valid_T_182, valid_2_30};
  wire        _wdata_0_value_1_T = io_readAddr_0_addr == 5'h1;
  wire        _wdata_0_value_2_T = io_readAddr_0_addr == 5'h2;
  wire        _wdata_0_value_3_T = io_readAddr_0_addr == 5'h3;
  wire        _wdata_0_value_4_T = io_readAddr_0_addr == 5'h4;
  wire        _wdata_0_value_5_T = io_readAddr_0_addr == 5'h5;
  wire        _wdata_0_value_6_T = io_readAddr_0_addr == 5'h6;
  wire        _wdata_0_value_7_T = io_readAddr_0_addr == 5'h7;
  wire        _wdata_0_value_8_T = io_readAddr_0_addr == 5'h8;
  wire        _wdata_0_value_9_T = io_readAddr_0_addr == 5'h9;
  wire        _wdata_0_value_10_T = io_readAddr_0_addr == 5'hA;
  wire        _wdata_0_value_11_T = io_readAddr_0_addr == 5'hB;
  wire        _wdata_0_value_12_T = io_readAddr_0_addr == 5'hC;
  wire        _wdata_0_value_13_T = io_readAddr_0_addr == 5'hD;
  wire        _wdata_0_value_14_T = io_readAddr_0_addr == 5'hE;
  wire        _wdata_0_value_15_T = io_readAddr_0_addr == 5'hF;
  wire        _wdata_0_value_16_T = io_readAddr_0_addr == 5'h10;
  wire        _wdata_0_value_17_T = io_readAddr_0_addr == 5'h11;
  wire        _wdata_0_value_18_T = io_readAddr_0_addr == 5'h12;
  wire        _wdata_0_value_19_T = io_readAddr_0_addr == 5'h13;
  wire        _wdata_0_value_20_T = io_readAddr_0_addr == 5'h14;
  wire        _wdata_0_value_21_T = io_readAddr_0_addr == 5'h15;
  wire        _wdata_0_value_22_T = io_readAddr_0_addr == 5'h16;
  wire        _wdata_0_value_23_T = io_readAddr_0_addr == 5'h17;
  wire        _wdata_0_value_24_T = io_readAddr_0_addr == 5'h18;
  wire        _wdata_0_value_25_T = io_readAddr_0_addr == 5'h19;
  wire        _wdata_0_value_26_T = io_readAddr_0_addr == 5'h1A;
  wire        _wdata_0_value_27_T = io_readAddr_0_addr == 5'h1B;
  wire        _wdata_0_value_28_T = io_readAddr_0_addr == 5'h1C;
  wire        _wdata_0_value_29_T = io_readAddr_0_addr == 5'h1D;
  wire        _wdata_0_value_30_T = io_readAddr_0_addr == 5'h1E;
  wire [31:0] rdata_0_value_5_0 =
    (_wdata_0_value_1_T ? regfile_1 : 32'h0) | (_wdata_0_value_2_T ? regfile_2 : 32'h0)
    | (_wdata_0_value_3_T ? regfile_3 : 32'h0) | (_wdata_0_value_4_T ? regfile_4 : 32'h0)
    | (_wdata_0_value_5_T ? regfile_5 : 32'h0) | (_wdata_0_value_6_T ? regfile_6 : 32'h0)
    | (_wdata_0_value_7_T ? regfile_7 : 32'h0) | (_wdata_0_value_8_T ? regfile_8 : 32'h0)
    | (_wdata_0_value_9_T ? regfile_9 : 32'h0)
    | (_wdata_0_value_10_T ? regfile_10 : 32'h0)
    | (_wdata_0_value_11_T ? regfile_11 : 32'h0)
    | (_wdata_0_value_12_T ? regfile_12 : 32'h0)
    | (_wdata_0_value_13_T ? regfile_13 : 32'h0)
    | (_wdata_0_value_14_T ? regfile_14 : 32'h0)
    | (_wdata_0_value_15_T ? regfile_15 : 32'h0)
    | (_wdata_0_value_16_T ? regfile_16 : 32'h0)
    | (_wdata_0_value_17_T ? regfile_17 : 32'h0)
    | (_wdata_0_value_18_T ? regfile_18 : 32'h0)
    | (_wdata_0_value_19_T ? regfile_19 : 32'h0)
    | (_wdata_0_value_20_T ? regfile_20 : 32'h0)
    | (_wdata_0_value_21_T ? regfile_21 : 32'h0)
    | (_wdata_0_value_22_T ? regfile_22 : 32'h0)
    | (_wdata_0_value_23_T ? regfile_23 : 32'h0)
    | (_wdata_0_value_24_T ? regfile_24 : 32'h0)
    | (_wdata_0_value_25_T ? regfile_25 : 32'h0)
    | (_wdata_0_value_26_T ? regfile_26 : 32'h0)
    | (_wdata_0_value_27_T ? regfile_27 : 32'h0)
    | (_wdata_0_value_28_T ? regfile_28 : 32'h0)
    | (_wdata_0_value_29_T ? regfile_29 : 32'h0)
    | (_wdata_0_value_30_T ? regfile_30 : 32'h0)
    | ((&io_readAddr_0_addr) ? regfile_31 : 32'h0);
  wire        _wdata_1_value_1_T = io_readAddr_1_addr == 5'h1;
  wire        _wdata_1_value_2_T = io_readAddr_1_addr == 5'h2;
  wire        _wdata_1_value_3_T = io_readAddr_1_addr == 5'h3;
  wire        _wdata_1_value_4_T = io_readAddr_1_addr == 5'h4;
  wire        _wdata_1_value_5_T = io_readAddr_1_addr == 5'h5;
  wire        _wdata_1_value_6_T = io_readAddr_1_addr == 5'h6;
  wire        _wdata_1_value_7_T = io_readAddr_1_addr == 5'h7;
  wire        _wdata_1_value_8_T = io_readAddr_1_addr == 5'h8;
  wire        _wdata_1_value_9_T = io_readAddr_1_addr == 5'h9;
  wire        _wdata_1_value_10_T = io_readAddr_1_addr == 5'hA;
  wire        _wdata_1_value_11_T = io_readAddr_1_addr == 5'hB;
  wire        _wdata_1_value_12_T = io_readAddr_1_addr == 5'hC;
  wire        _wdata_1_value_13_T = io_readAddr_1_addr == 5'hD;
  wire        _wdata_1_value_14_T = io_readAddr_1_addr == 5'hE;
  wire        _wdata_1_value_15_T = io_readAddr_1_addr == 5'hF;
  wire        _wdata_1_value_16_T = io_readAddr_1_addr == 5'h10;
  wire        _wdata_1_value_17_T = io_readAddr_1_addr == 5'h11;
  wire        _wdata_1_value_18_T = io_readAddr_1_addr == 5'h12;
  wire        _wdata_1_value_19_T = io_readAddr_1_addr == 5'h13;
  wire        _wdata_1_value_20_T = io_readAddr_1_addr == 5'h14;
  wire        _wdata_1_value_21_T = io_readAddr_1_addr == 5'h15;
  wire        _wdata_1_value_22_T = io_readAddr_1_addr == 5'h16;
  wire        _wdata_1_value_23_T = io_readAddr_1_addr == 5'h17;
  wire        _wdata_1_value_24_T = io_readAddr_1_addr == 5'h18;
  wire        _wdata_1_value_25_T = io_readAddr_1_addr == 5'h19;
  wire        _wdata_1_value_26_T = io_readAddr_1_addr == 5'h1A;
  wire        _wdata_1_value_27_T = io_readAddr_1_addr == 5'h1B;
  wire        _wdata_1_value_28_T = io_readAddr_1_addr == 5'h1C;
  wire        _wdata_1_value_29_T = io_readAddr_1_addr == 5'h1D;
  wire        _wdata_1_value_30_T = io_readAddr_1_addr == 5'h1E;
  wire [31:0] rwdata_1 =
    io_readAddr_1_addr == 5'h0 | _wdata_1_value_1_T & (|_writeValid_1_T)
    | _wdata_1_value_2_T & (|_writeValid_2_T) | _wdata_1_value_3_T & (|_writeValid_3_T)
    | _wdata_1_value_4_T & (|_writeValid_4_T) | _wdata_1_value_5_T & (|_writeValid_5_T)
    | _wdata_1_value_6_T & (|_writeValid_6_T) | _wdata_1_value_7_T & (|_writeValid_7_T)
    | _wdata_1_value_8_T & (|_writeValid_8_T) | _wdata_1_value_9_T & (|_writeValid_9_T)
    | _wdata_1_value_10_T & (|_writeValid_10_T) | _wdata_1_value_11_T
    & (|_writeValid_11_T) | _wdata_1_value_12_T & (|_writeValid_12_T)
    | _wdata_1_value_13_T & (|_writeValid_13_T) | _wdata_1_value_14_T
    & (|_writeValid_14_T) | _wdata_1_value_15_T & (|_writeValid_15_T)
    | _wdata_1_value_16_T & (|_writeValid_16_T) | _wdata_1_value_17_T
    & (|_writeValid_17_T) | _wdata_1_value_18_T & (|_writeValid_18_T)
    | _wdata_1_value_19_T & (|_writeValid_19_T) | _wdata_1_value_20_T
    & (|_writeValid_20_T) | _wdata_1_value_21_T & (|_writeValid_21_T)
    | _wdata_1_value_22_T & (|_writeValid_22_T) | _wdata_1_value_23_T
    & (|_writeValid_23_T) | _wdata_1_value_24_T & (|_writeValid_24_T)
    | _wdata_1_value_25_T & (|_writeValid_25_T) | _wdata_1_value_26_T
    & (|_writeValid_26_T) | _wdata_1_value_27_T & (|_writeValid_27_T)
    | _wdata_1_value_28_T & (|_writeValid_28_T) | _wdata_1_value_29_T
    & (|_writeValid_29_T) | _wdata_1_value_30_T & (|_writeValid_30_T)
    | (&io_readAddr_1_addr) & (|_writeValid_31_T)
      ? (_wdata_1_value_1_T ? data : 32'h0) | (_wdata_1_value_2_T ? data_1 : 32'h0)
        | (_wdata_1_value_3_T ? data_2 : 32'h0) | (_wdata_1_value_4_T ? data_3 : 32'h0)
        | (_wdata_1_value_5_T ? data_4 : 32'h0) | (_wdata_1_value_6_T ? data_5 : 32'h0)
        | (_wdata_1_value_7_T ? data_6 : 32'h0) | (_wdata_1_value_8_T ? data_7 : 32'h0)
        | (_wdata_1_value_9_T ? data_8 : 32'h0) | (_wdata_1_value_10_T ? data_9 : 32'h0)
        | (_wdata_1_value_11_T ? data_10 : 32'h0)
        | (_wdata_1_value_12_T ? data_11 : 32'h0)
        | (_wdata_1_value_13_T ? data_12 : 32'h0)
        | (_wdata_1_value_14_T ? data_13 : 32'h0)
        | (_wdata_1_value_15_T ? data_14 : 32'h0)
        | (_wdata_1_value_16_T ? data_15 : 32'h0)
        | (_wdata_1_value_17_T ? data_16 : 32'h0)
        | (_wdata_1_value_18_T ? data_17 : 32'h0)
        | (_wdata_1_value_19_T ? data_18 : 32'h0)
        | (_wdata_1_value_20_T ? data_19 : 32'h0)
        | (_wdata_1_value_21_T ? data_20 : 32'h0)
        | (_wdata_1_value_22_T ? data_21 : 32'h0)
        | (_wdata_1_value_23_T ? data_22 : 32'h0)
        | (_wdata_1_value_24_T ? data_23 : 32'h0)
        | (_wdata_1_value_25_T ? data_24 : 32'h0)
        | (_wdata_1_value_26_T ? data_25 : 32'h0)
        | (_wdata_1_value_27_T ? data_26 : 32'h0)
        | (_wdata_1_value_28_T ? data_27 : 32'h0)
        | (_wdata_1_value_29_T ? data_28 : 32'h0)
        | (_wdata_1_value_30_T ? data_29 : 32'h0)
        | ((&io_readAddr_1_addr) ? data_30 : 32'h0)
      : (_wdata_1_value_1_T ? regfile_1 : 32'h0)
        | (_wdata_1_value_2_T ? regfile_2 : 32'h0)
        | (_wdata_1_value_3_T ? regfile_3 : 32'h0)
        | (_wdata_1_value_4_T ? regfile_4 : 32'h0)
        | (_wdata_1_value_5_T ? regfile_5 : 32'h0)
        | (_wdata_1_value_6_T ? regfile_6 : 32'h0)
        | (_wdata_1_value_7_T ? regfile_7 : 32'h0)
        | (_wdata_1_value_8_T ? regfile_8 : 32'h0)
        | (_wdata_1_value_9_T ? regfile_9 : 32'h0)
        | (_wdata_1_value_10_T ? regfile_10 : 32'h0)
        | (_wdata_1_value_11_T ? regfile_11 : 32'h0)
        | (_wdata_1_value_12_T ? regfile_12 : 32'h0)
        | (_wdata_1_value_13_T ? regfile_13 : 32'h0)
        | (_wdata_1_value_14_T ? regfile_14 : 32'h0)
        | (_wdata_1_value_15_T ? regfile_15 : 32'h0)
        | (_wdata_1_value_16_T ? regfile_16 : 32'h0)
        | (_wdata_1_value_17_T ? regfile_17 : 32'h0)
        | (_wdata_1_value_18_T ? regfile_18 : 32'h0)
        | (_wdata_1_value_19_T ? regfile_19 : 32'h0)
        | (_wdata_1_value_20_T ? regfile_20 : 32'h0)
        | (_wdata_1_value_21_T ? regfile_21 : 32'h0)
        | (_wdata_1_value_22_T ? regfile_22 : 32'h0)
        | (_wdata_1_value_23_T ? regfile_23 : 32'h0)
        | (_wdata_1_value_24_T ? regfile_24 : 32'h0)
        | (_wdata_1_value_25_T ? regfile_25 : 32'h0)
        | (_wdata_1_value_26_T ? regfile_26 : 32'h0)
        | (_wdata_1_value_27_T ? regfile_27 : 32'h0)
        | (_wdata_1_value_28_T ? regfile_28 : 32'h0)
        | (_wdata_1_value_29_T ? regfile_29 : 32'h0)
        | (_wdata_1_value_30_T ? regfile_30 : 32'h0)
        | ((&io_readAddr_1_addr) ? regfile_31 : 32'h0);
  wire [31:0] busAddr_0 =
    io_busAddr_0_immen ? rdata_0_value_5_0 + io_busAddr_0_immed : rdata_0_value_5_0;
  reg         write_fail;
  reg         write_fail_1;
  reg         write_fail_2;
  reg         scoreboard_error;
  wire [31:0] scoreboard_set =
    io_writeAddr_0_valid ? 32'h1 << io_writeAddr_0_addr : 32'h0;
  wire [31:0] scoreboard_clr = {scoreboard_clr0, 1'h0};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      regfile_1 <= 32'h0;
      regfile_2 <= 32'h0;
      regfile_3 <= 32'h0;
      regfile_4 <= 32'h0;
      regfile_5 <= 32'h0;
      regfile_6 <= 32'h0;
      regfile_7 <= 32'h0;
      regfile_8 <= 32'h0;
      regfile_9 <= 32'h0;
      regfile_10 <= 32'h0;
      regfile_11 <= 32'h0;
      regfile_12 <= 32'h0;
      regfile_13 <= 32'h0;
      regfile_14 <= 32'h0;
      regfile_15 <= 32'h0;
      regfile_16 <= 32'h0;
      regfile_17 <= 32'h0;
      regfile_18 <= 32'h0;
      regfile_19 <= 32'h0;
      regfile_20 <= 32'h0;
      regfile_21 <= 32'h0;
      regfile_22 <= 32'h0;
      regfile_23 <= 32'h0;
      regfile_24 <= 32'h0;
      regfile_25 <= 32'h0;
      regfile_26 <= 32'h0;
      regfile_27 <= 32'h0;
      regfile_28 <= 32'h0;
      regfile_29 <= 32'h0;
      regfile_30 <= 32'h0;
      regfile_31 <= 32'h0;
      scoreboard <= 32'h0;
      readDataReady_0 <= 1'h0;
      readDataReady_1 <= 1'h0;
      readDataBits_0 <= 32'h0;
      readDataBits_1 <= 32'h0;
      write_fail <= 1'h0;
      write_fail_1 <= 1'h0;
      write_fail_2 <= 1'h0;
      scoreboard_error <= 1'h0;
    end
    else begin
      if (|_writeValid_1_T)
        regfile_1 <= data;
      if (|_writeValid_2_T)
        regfile_2 <= data_1;
      if (|_writeValid_3_T)
        regfile_3 <= data_2;
      if (|_writeValid_4_T)
        regfile_4 <= data_3;
      if (|_writeValid_5_T)
        regfile_5 <= data_4;
      if (|_writeValid_6_T)
        regfile_6 <= data_5;
      if (|_writeValid_7_T)
        regfile_7 <= data_6;
      if (|_writeValid_8_T)
        regfile_8 <= data_7;
      if (|_writeValid_9_T)
        regfile_9 <= data_8;
      if (|_writeValid_10_T)
        regfile_10 <= data_9;
      if (|_writeValid_11_T)
        regfile_11 <= data_10;
      if (|_writeValid_12_T)
        regfile_12 <= data_11;
      if (|_writeValid_13_T)
        regfile_13 <= data_12;
      if (|_writeValid_14_T)
        regfile_14 <= data_13;
      if (|_writeValid_15_T)
        regfile_15 <= data_14;
      if (|_writeValid_16_T)
        regfile_16 <= data_15;
      if (|_writeValid_17_T)
        regfile_17 <= data_16;
      if (|_writeValid_18_T)
        regfile_18 <= data_17;
      if (|_writeValid_19_T)
        regfile_19 <= data_18;
      if (|_writeValid_20_T)
        regfile_20 <= data_19;
      if (|_writeValid_21_T)
        regfile_21 <= data_20;
      if (|_writeValid_22_T)
        regfile_22 <= data_21;
      if (|_writeValid_23_T)
        regfile_23 <= data_22;
      if (|_writeValid_24_T)
        regfile_24 <= data_23;
      if (|_writeValid_25_T)
        regfile_25 <= data_24;
      if (|_writeValid_26_T)
        regfile_26 <= data_25;
      if (|_writeValid_27_T)
        regfile_27 <= data_26;
      if (|_writeValid_28_T)
        regfile_28 <= data_27;
      if (|_writeValid_29_T)
        regfile_29 <= data_28;
      if (|_writeValid_30_T)
        regfile_30 <= data_29;
      if (|_writeValid_31_T)
        regfile_31 <= data_30;
      if (|{scoreboard_set, scoreboard_clr0})
        scoreboard <= {scoreboard[31:1] & ~scoreboard_clr0 | scoreboard_set[31:1], 1'h0};
      readDataReady_0 <= io_readAddr_0_valid | io_readSet_0_valid;
      readDataReady_1 <= io_readAddr_1_valid | io_readSet_1_valid;
      if (io_readSet_0_valid)
        readDataBits_0 <= io_readSet_0_value;
      else if (io_readAddr_0_valid)
        readDataBits_0 <=
          io_readAddr_0_addr == 5'h0 | _wdata_0_value_1_T & (|_writeValid_1_T)
          | _wdata_0_value_2_T & (|_writeValid_2_T) | _wdata_0_value_3_T
          & (|_writeValid_3_T) | _wdata_0_value_4_T & (|_writeValid_4_T)
          | _wdata_0_value_5_T & (|_writeValid_5_T) | _wdata_0_value_6_T
          & (|_writeValid_6_T) | _wdata_0_value_7_T & (|_writeValid_7_T)
          | _wdata_0_value_8_T & (|_writeValid_8_T) | _wdata_0_value_9_T
          & (|_writeValid_9_T) | _wdata_0_value_10_T & (|_writeValid_10_T)
          | _wdata_0_value_11_T & (|_writeValid_11_T) | _wdata_0_value_12_T
          & (|_writeValid_12_T) | _wdata_0_value_13_T & (|_writeValid_13_T)
          | _wdata_0_value_14_T & (|_writeValid_14_T) | _wdata_0_value_15_T
          & (|_writeValid_15_T) | _wdata_0_value_16_T & (|_writeValid_16_T)
          | _wdata_0_value_17_T & (|_writeValid_17_T) | _wdata_0_value_18_T
          & (|_writeValid_18_T) | _wdata_0_value_19_T & (|_writeValid_19_T)
          | _wdata_0_value_20_T & (|_writeValid_20_T) | _wdata_0_value_21_T
          & (|_writeValid_21_T) | _wdata_0_value_22_T & (|_writeValid_22_T)
          | _wdata_0_value_23_T & (|_writeValid_23_T) | _wdata_0_value_24_T
          & (|_writeValid_24_T) | _wdata_0_value_25_T & (|_writeValid_25_T)
          | _wdata_0_value_26_T & (|_writeValid_26_T) | _wdata_0_value_27_T
          & (|_writeValid_27_T) | _wdata_0_value_28_T & (|_writeValid_28_T)
          | _wdata_0_value_29_T & (|_writeValid_29_T) | _wdata_0_value_30_T
          & (|_writeValid_30_T) | (&io_readAddr_0_addr) & (|_writeValid_31_T)
            ? (_wdata_0_value_1_T ? data : 32'h0) | (_wdata_0_value_2_T ? data_1 : 32'h0)
              | (_wdata_0_value_3_T ? data_2 : 32'h0)
              | (_wdata_0_value_4_T ? data_3 : 32'h0)
              | (_wdata_0_value_5_T ? data_4 : 32'h0)
              | (_wdata_0_value_6_T ? data_5 : 32'h0)
              | (_wdata_0_value_7_T ? data_6 : 32'h0)
              | (_wdata_0_value_8_T ? data_7 : 32'h0)
              | (_wdata_0_value_9_T ? data_8 : 32'h0)
              | (_wdata_0_value_10_T ? data_9 : 32'h0)
              | (_wdata_0_value_11_T ? data_10 : 32'h0)
              | (_wdata_0_value_12_T ? data_11 : 32'h0)
              | (_wdata_0_value_13_T ? data_12 : 32'h0)
              | (_wdata_0_value_14_T ? data_13 : 32'h0)
              | (_wdata_0_value_15_T ? data_14 : 32'h0)
              | (_wdata_0_value_16_T ? data_15 : 32'h0)
              | (_wdata_0_value_17_T ? data_16 : 32'h0)
              | (_wdata_0_value_18_T ? data_17 : 32'h0)
              | (_wdata_0_value_19_T ? data_18 : 32'h0)
              | (_wdata_0_value_20_T ? data_19 : 32'h0)
              | (_wdata_0_value_21_T ? data_20 : 32'h0)
              | (_wdata_0_value_22_T ? data_21 : 32'h0)
              | (_wdata_0_value_23_T ? data_22 : 32'h0)
              | (_wdata_0_value_24_T ? data_23 : 32'h0)
              | (_wdata_0_value_25_T ? data_24 : 32'h0)
              | (_wdata_0_value_26_T ? data_25 : 32'h0)
              | (_wdata_0_value_27_T ? data_26 : 32'h0)
              | (_wdata_0_value_28_T ? data_27 : 32'h0)
              | (_wdata_0_value_29_T ? data_28 : 32'h0)
              | (_wdata_0_value_30_T ? data_29 : 32'h0)
              | ((&io_readAddr_0_addr) ? data_30 : 32'h0)
            : rdata_0_value_5_0;
      if (io_readSet_1_valid)
        readDataBits_1 <= io_readSet_1_value;
      else if (io_readAddr_1_valid)
        readDataBits_1 <= rwdata_1;
      write_fail <=
        io_writeData_0_valid & io_writeData_1_valid
        & io_writeData_0_bits_addr == io_writeData_1_bits_addr
        & (|io_writeData_0_bits_addr);
      write_fail_1 <=
        io_writeData_0_valid & io_writeData_2_valid
        & io_writeData_0_bits_addr == io_writeData_2_bits_addr
        & (|io_writeData_0_bits_addr);
      write_fail_2 <=
        io_writeData_1_valid & io_writeData_2_valid
        & io_writeData_1_bits_addr == io_writeData_2_bits_addr
        & (|io_writeData_1_bits_addr);
      scoreboard_error <=
        (scoreboard & scoreboard_clr) != scoreboard_clr & ~io_debugWriteValid;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:35];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h24; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        regfile_1 = _RANDOM[6'h1];
        regfile_2 = _RANDOM[6'h2];
        regfile_3 = _RANDOM[6'h3];
        regfile_4 = _RANDOM[6'h4];
        regfile_5 = _RANDOM[6'h5];
        regfile_6 = _RANDOM[6'h6];
        regfile_7 = _RANDOM[6'h7];
        regfile_8 = _RANDOM[6'h8];
        regfile_9 = _RANDOM[6'h9];
        regfile_10 = _RANDOM[6'hA];
        regfile_11 = _RANDOM[6'hB];
        regfile_12 = _RANDOM[6'hC];
        regfile_13 = _RANDOM[6'hD];
        regfile_14 = _RANDOM[6'hE];
        regfile_15 = _RANDOM[6'hF];
        regfile_16 = _RANDOM[6'h10];
        regfile_17 = _RANDOM[6'h11];
        regfile_18 = _RANDOM[6'h12];
        regfile_19 = _RANDOM[6'h13];
        regfile_20 = _RANDOM[6'h14];
        regfile_21 = _RANDOM[6'h15];
        regfile_22 = _RANDOM[6'h16];
        regfile_23 = _RANDOM[6'h17];
        regfile_24 = _RANDOM[6'h18];
        regfile_25 = _RANDOM[6'h19];
        regfile_26 = _RANDOM[6'h1A];
        regfile_27 = _RANDOM[6'h1B];
        regfile_28 = _RANDOM[6'h1C];
        regfile_29 = _RANDOM[6'h1D];
        regfile_30 = _RANDOM[6'h1E];
        regfile_31 = _RANDOM[6'h1F];
        scoreboard = _RANDOM[6'h20];
        readDataReady_0 = _RANDOM[6'h21][0];
        readDataReady_1 = _RANDOM[6'h21][1];
        readDataBits_0 = {_RANDOM[6'h21][31:2], _RANDOM[6'h22][1:0]};
        readDataBits_1 = {_RANDOM[6'h22][31:2], _RANDOM[6'h23][1:0]};
        write_fail = _RANDOM[6'h23][2];
        write_fail_1 = _RANDOM[6'h23][3];
        write_fail_2 = _RANDOM[6'h23][4];
        scoreboard_error = _RANDOM[6'h23][5];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        regfile_1 = 32'h0;
        regfile_2 = 32'h0;
        regfile_3 = 32'h0;
        regfile_4 = 32'h0;
        regfile_5 = 32'h0;
        regfile_6 = 32'h0;
        regfile_7 = 32'h0;
        regfile_8 = 32'h0;
        regfile_9 = 32'h0;
        regfile_10 = 32'h0;
        regfile_11 = 32'h0;
        regfile_12 = 32'h0;
        regfile_13 = 32'h0;
        regfile_14 = 32'h0;
        regfile_15 = 32'h0;
        regfile_16 = 32'h0;
        regfile_17 = 32'h0;
        regfile_18 = 32'h0;
        regfile_19 = 32'h0;
        regfile_20 = 32'h0;
        regfile_21 = 32'h0;
        regfile_22 = 32'h0;
        regfile_23 = 32'h0;
        regfile_24 = 32'h0;
        regfile_25 = 32'h0;
        regfile_26 = 32'h0;
        regfile_27 = 32'h0;
        regfile_28 = 32'h0;
        regfile_29 = 32'h0;
        regfile_30 = 32'h0;
        regfile_31 = 32'h0;
        scoreboard = 32'h0;
        readDataReady_0 = 1'h0;
        readDataReady_1 = 1'h0;
        readDataBits_0 = 32'h0;
        readDataBits_1 = 32'h0;
        write_fail = 1'h0;
        write_fail_1 = 1'h0;
        write_fail_2 = 1'h0;
        scoreboard_error = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_target_0_data = busAddr_0;
  assign io_busPort_addr_0 = busAddr_0;
  assign io_busPort_data_0 = io_readSet_1_valid ? io_readSet_1_value : rwdata_1;
  assign io_debugBusPort_data =
    (io_debugBusPort_idx == 5'h1 ? regfile_1 : 32'h0)
    | (io_debugBusPort_idx == 5'h2 ? regfile_2 : 32'h0)
    | (io_debugBusPort_idx == 5'h3 ? regfile_3 : 32'h0)
    | (io_debugBusPort_idx == 5'h4 ? regfile_4 : 32'h0)
    | (io_debugBusPort_idx == 5'h5 ? regfile_5 : 32'h0)
    | (io_debugBusPort_idx == 5'h6 ? regfile_6 : 32'h0)
    | (io_debugBusPort_idx == 5'h7 ? regfile_7 : 32'h0)
    | (io_debugBusPort_idx == 5'h8 ? regfile_8 : 32'h0)
    | (io_debugBusPort_idx == 5'h9 ? regfile_9 : 32'h0)
    | (io_debugBusPort_idx == 5'hA ? regfile_10 : 32'h0)
    | (io_debugBusPort_idx == 5'hB ? regfile_11 : 32'h0)
    | (io_debugBusPort_idx == 5'hC ? regfile_12 : 32'h0)
    | (io_debugBusPort_idx == 5'hD ? regfile_13 : 32'h0)
    | (io_debugBusPort_idx == 5'hE ? regfile_14 : 32'h0)
    | (io_debugBusPort_idx == 5'hF ? regfile_15 : 32'h0)
    | (io_debugBusPort_idx == 5'h10 ? regfile_16 : 32'h0)
    | (io_debugBusPort_idx == 5'h11 ? regfile_17 : 32'h0)
    | (io_debugBusPort_idx == 5'h12 ? regfile_18 : 32'h0)
    | (io_debugBusPort_idx == 5'h13 ? regfile_19 : 32'h0)
    | (io_debugBusPort_idx == 5'h14 ? regfile_20 : 32'h0)
    | (io_debugBusPort_idx == 5'h15 ? regfile_21 : 32'h0)
    | (io_debugBusPort_idx == 5'h16 ? regfile_22 : 32'h0)
    | (io_debugBusPort_idx == 5'h17 ? regfile_23 : 32'h0)
    | (io_debugBusPort_idx == 5'h18 ? regfile_24 : 32'h0)
    | (io_debugBusPort_idx == 5'h19 ? regfile_25 : 32'h0)
    | (io_debugBusPort_idx == 5'h1A ? regfile_26 : 32'h0)
    | (io_debugBusPort_idx == 5'h1B ? regfile_27 : 32'h0)
    | (io_debugBusPort_idx == 5'h1C ? regfile_28 : 32'h0)
    | (io_debugBusPort_idx == 5'h1D ? regfile_29 : 32'h0)
    | (io_debugBusPort_idx == 5'h1E ? regfile_30 : 32'h0)
    | ((&io_debugBusPort_idx) ? regfile_31 : 32'h0);
  assign io_readData_0_valid = readDataReady_0;
  assign io_readData_0_data = readDataBits_0;
  assign io_readData_1_valid = readDataReady_1;
  assign io_readData_1_data = readDataBits_1;
  assign io_scoreboard_regd = scoreboard;
  assign io_scoreboard_comb = scoreboard & {~scoreboard_clr0, 1'h1};
endmodule

