// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RetirementBuffer(
  input         clock,
                reset,
                io_inst_0_ready,
                io_inst_0_valid,
  input  [31:0] io_inst_0_bits_addr,
                io_inst_0_bits_inst,
                io_targets_0,
                io_jalrTargets_0,
  input         io_jump_0,
                io_branch_0,
                io_storeComplete_valid,
  input  [31:0] io_storeComplete_bits,
  input         io_writeAddrScalar_0_valid,
  input  [4:0]  io_writeAddrScalar_0_addr,
  input         io_writeDataScalar_0_valid,
  input  [4:0]  io_writeDataScalar_0_bits_addr,
  input         io_writeDataScalar_1_valid,
  input  [4:0]  io_writeDataScalar_1_bits_addr,
  input         io_writeDataScalar_2_valid,
  input  [4:0]  io_writeDataScalar_2_bits_addr,
  input         io_writeAddrVector_0_valid,
  input  [4:0]  io_writeAddrVector_0_addr,
  input         io_writeDataVector_0_valid,
  input  [4:0]  io_writeDataVector_0_bits_addr,
  input  [31:0] io_writeDataVector_0_bits_uop_pc,
  input         io_writeDataVector_0_bits_last_uop_valid,
                io_fault_valid,
  input  [31:0] io_fault_bits_mepc,
                io_fault_bits_mcause,
  input         io_fault_bits_decode,
  output [2:0]  io_nSpace,
                io_nRetired,
  output        io_empty,
                io_trapPending
);

  wire [2:0]  _instBuffer_io_nEnqueued;
  wire [31:0] _instBuffer_io_dataOut_0_addr;
  wire [6:0]  _instBuffer_io_dataOut_0_idx;
  wire        _instBuffer_io_dataOut_0_trap;
  wire        _instBuffer_io_dataOut_0_isControlFlow;
  wire        _instBuffer_io_dataOut_0_isBranch;
  wire        _instBuffer_io_dataOut_0_isVector;
  wire        _instBuffer_io_dataOut_0_isEcall;
  wire        _instBuffer_io_dataOut_0_isMpause;
  wire [31:0] _instBuffer_io_dataOut_1_addr;
  wire [6:0]  _instBuffer_io_dataOut_1_idx;
  wire        _instBuffer_io_dataOut_1_trap;
  wire        _instBuffer_io_dataOut_1_isControlFlow;
  wire        _instBuffer_io_dataOut_1_isBranch;
  wire        _instBuffer_io_dataOut_1_isVector;
  wire        _instBuffer_io_dataOut_1_linkOk;
  wire        _instBuffer_io_dataOut_1_isEcall;
  wire        _instBuffer_io_dataOut_1_isMpause;
  wire [31:0] _instBuffer_io_dataOut_2_addr;
  wire [6:0]  _instBuffer_io_dataOut_2_idx;
  wire        _instBuffer_io_dataOut_2_trap;
  wire        _instBuffer_io_dataOut_2_isControlFlow;
  wire        _instBuffer_io_dataOut_2_isBranch;
  wire        _instBuffer_io_dataOut_2_isVector;
  wire        _instBuffer_io_dataOut_2_linkOk;
  wire        _instBuffer_io_dataOut_2_isEcall;
  wire        _instBuffer_io_dataOut_2_isMpause;
  wire [31:0] _instBuffer_io_dataOut_3_addr;
  wire [6:0]  _instBuffer_io_dataOut_3_idx;
  wire        _instBuffer_io_dataOut_3_trap;
  wire        _instBuffer_io_dataOut_3_isControlFlow;
  wire        _instBuffer_io_dataOut_3_isBranch;
  wire        _instBuffer_io_dataOut_3_isVector;
  wire        _instBuffer_io_dataOut_3_linkOk;
  wire        _instBuffer_io_dataOut_3_isEcall;
  wire        _instBuffer_io_dataOut_3_isMpause;
  reg         storeComplete_pipe_v;
  reg  [31:0] storeComplete_pipe_b;
  wire        instsWithWriteFired = io_inst_0_ready & io_inst_0_valid;
  wire        decodeFaultValid = io_fault_valid & io_fault_bits_decode;
  wire        noFire0Fault =
    io_fault_valid & ~instsWithWriteFired & io_fault_bits_mcause != 32'h7
    & io_fault_bits_mcause != 32'h5;
  reg  [31:0] regLastTarget;
  reg  [31:0] regLastAddr;
  reg         regLastIsBranch;
  wire        _lane0LinkOk_T_15 = io_inst_0_bits_addr == regLastTarget;
  wire [31:0] _faultLinkOk_T_16 = regLastAddr + 32'h4;
  wire        insts_instr_vectorStore =
    io_inst_0_bits_inst[6:0] == 7'h27
    & (~(|(io_inst_0_bits_inst[14:12])) | io_inst_0_bits_inst[14:12] == 3'h5
       | io_inst_0_bits_inst[14:12] == 3'h6 | (&(io_inst_0_bits_inst[14:12])));
  wire [6:0]  _GEN = {2'h0, io_writeAddrScalar_0_addr};
  wire        insts_vectorStore =
    io_inst_0_bits_inst[6:0] == 7'h27
    & (~(|(io_inst_0_bits_inst[14:12])) | io_inst_0_bits_inst[14:12] == 3'h5
       | io_inst_0_bits_inst[14:12] == 3'h6 | (&(io_inst_0_bits_inst[14:12])));
  reg         resultBuffer_0_valid;
  reg         resultBuffer_0_bits_trap;
  reg         resultBuffer_0_bits_cfDone;
  reg         resultBuffer_1_valid;
  reg         resultBuffer_1_bits_trap;
  reg         resultBuffer_1_bits_cfDone;
  reg         resultBuffer_2_valid;
  reg         resultBuffer_2_bits_trap;
  reg         resultBuffer_2_bits_cfDone;
  reg         resultBuffer_3_valid;
  reg         resultBuffer_3_bits_trap;
  reg         resultBuffer_3_bits_cfDone;
  wire [6:0]  _GEN_0 = {2'h0, io_writeDataScalar_0_bits_addr};
  wire [6:0]  _GEN_1 = {2'h0, io_writeDataScalar_1_bits_addr};
  wire [6:0]  _GEN_2 = {2'h0, io_writeDataScalar_2_bits_addr};
  wire [7:0]  _vectorWriteIdxMap_T_32 = {3'h0, io_writeDataVector_0_bits_addr} + 8'h40;
  wire        nextAddrValid =
    (|(_instBuffer_io_nEnqueued[2:1])) | noFire0Fault | io_inst_0_valid;
  wire        _faultLinkOk_T_15 = io_fault_bits_mepc == regLastTarget;
  wire        newCfDone =
    (|_instBuffer_io_nEnqueued)
    & (~_instBuffer_io_dataOut_0_isControlFlow | nextAddrValid);
  wire        hi =
    resultBuffer_0_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_0_addr == io_fault_bits_mepc | (|_instBuffer_io_nEnqueued)
    & _instBuffer_io_dataOut_0_trap | _instBuffer_io_dataOut_0_isControlFlow & newCfDone
    & (~(nextAddrValid
         & (((|(_instBuffer_io_nEnqueued[2:1]))
               ? _instBuffer_io_dataOut_1_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_15 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_16
                   : ~io_inst_0_valid | _lane0LinkOk_T_15 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_16)
            | _instBuffer_io_dataOut_0_isBranch
            & ((|(_instBuffer_io_nEnqueued[2:1]))
                 ? _instBuffer_io_dataOut_1_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_1_addr) == _instBuffer_io_dataOut_0_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_0_isMpause;
  wire        currentDataDone =
    resultBuffer_0_valid | (|_instBuffer_io_nEnqueued) & ~resultBuffer_0_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_0_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_0_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_0_idx
       | io_writeDataVector_0_valid
       & (_instBuffer_io_dataOut_0_isVector & _instBuffer_io_dataOut_0_idx != 7'h7E
          & io_writeDataVector_0_bits_uop_pc == _instBuffer_io_dataOut_0_addr
          | ~_instBuffer_io_dataOut_0_isVector
          & _vectorWriteIdxMap_T_32 == {1'h0, _instBuffer_io_dataOut_0_idx})
       & io_writeDataVector_0_bits_last_uop_valid | (&_instBuffer_io_dataOut_0_idx)
       | _instBuffer_io_dataOut_0_idx == 7'h7E & storeComplete_pipe_v
       & storeComplete_pipe_b == _instBuffer_io_dataOut_0_addr | hi);
  wire        currentCfDone =
    resultBuffer_0_valid & resultBuffer_0_bits_cfDone | newCfDone;
  wire        nextValid_1 = _instBuffer_io_nEnqueued > 3'h2;
  wire        nextAddrValid_1 = nextValid_1 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_1 =
    (|(_instBuffer_io_nEnqueued[2:1]))
    & (~_instBuffer_io_dataOut_1_isControlFlow | nextAddrValid_1);
  wire        currentTrap_1 =
    resultBuffer_1_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_1_addr == io_fault_bits_mepc
    | (|(_instBuffer_io_nEnqueued[2:1])) & _instBuffer_io_dataOut_1_trap
    | _instBuffer_io_dataOut_1_isControlFlow & newCfDone_1
    & (~(nextAddrValid_1
         & ((nextValid_1
               ? _instBuffer_io_dataOut_2_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_15 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_16
                   : ~io_inst_0_valid | _lane0LinkOk_T_15 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_16)
            | _instBuffer_io_dataOut_1_isBranch
            & (nextValid_1
                 ? _instBuffer_io_dataOut_2_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_2_addr) == _instBuffer_io_dataOut_1_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_1_isMpause;
  wire        currentDataDone_1 =
    resultBuffer_1_valid | (|(_instBuffer_io_nEnqueued[2:1])) & ~resultBuffer_1_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_1_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_1_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_1_idx
       | io_writeDataVector_0_valid
       & (_instBuffer_io_dataOut_1_isVector & _instBuffer_io_dataOut_1_idx != 7'h7E
          & io_writeDataVector_0_bits_uop_pc == _instBuffer_io_dataOut_1_addr
          | ~_instBuffer_io_dataOut_1_isVector
          & _vectorWriteIdxMap_T_32 == {1'h0, _instBuffer_io_dataOut_1_idx})
       & io_writeDataVector_0_bits_last_uop_valid | (&_instBuffer_io_dataOut_1_idx)
       | _instBuffer_io_dataOut_1_idx == 7'h7E & storeComplete_pipe_v
       & storeComplete_pipe_b == _instBuffer_io_dataOut_1_addr | currentTrap_1);
  wire        currentCfDone_1 =
    resultBuffer_1_valid & resultBuffer_1_bits_cfDone | newCfDone_1;
  wire        validBufferEntry_2 = _instBuffer_io_nEnqueued > 3'h2;
  wire        nextAddrValid_2 =
    _instBuffer_io_nEnqueued[2] | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_2 =
    validBufferEntry_2 & (~_instBuffer_io_dataOut_2_isControlFlow | nextAddrValid_2);
  wire        currentTrap_2 =
    resultBuffer_2_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_2_addr == io_fault_bits_mepc | validBufferEntry_2
    & _instBuffer_io_dataOut_2_trap | _instBuffer_io_dataOut_2_isControlFlow & newCfDone_2
    & (~(nextAddrValid_2
         & ((_instBuffer_io_nEnqueued[2]
               ? _instBuffer_io_dataOut_3_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_15 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_16
                   : ~io_inst_0_valid | _lane0LinkOk_T_15 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_16)
            | _instBuffer_io_dataOut_2_isBranch
            & (_instBuffer_io_nEnqueued[2]
                 ? _instBuffer_io_dataOut_3_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_3_addr) == _instBuffer_io_dataOut_2_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_2_isMpause;
  wire        currentDataDone_2 =
    resultBuffer_2_valid | validBufferEntry_2 & ~resultBuffer_2_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_2_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_2_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_2_idx
       | io_writeDataVector_0_valid
       & (_instBuffer_io_dataOut_2_isVector & _instBuffer_io_dataOut_2_idx != 7'h7E
          & io_writeDataVector_0_bits_uop_pc == _instBuffer_io_dataOut_2_addr
          | ~_instBuffer_io_dataOut_2_isVector
          & _vectorWriteIdxMap_T_32 == {1'h0, _instBuffer_io_dataOut_2_idx})
       & io_writeDataVector_0_bits_last_uop_valid | (&_instBuffer_io_dataOut_2_idx)
       | _instBuffer_io_dataOut_2_idx == 7'h7E & storeComplete_pipe_v
       & storeComplete_pipe_b == _instBuffer_io_dataOut_2_addr | currentTrap_2);
  wire        currentCfDone_2 =
    resultBuffer_2_valid & resultBuffer_2_bits_cfDone | newCfDone_2;
  wire        nextAddrValid_3 = noFire0Fault | io_inst_0_valid;
  wire        newCfDone_3 =
    _instBuffer_io_nEnqueued[2]
    & (~_instBuffer_io_dataOut_3_isControlFlow | nextAddrValid_3);
  wire        currentTrap_3 =
    resultBuffer_3_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_3_addr == io_fault_bits_mepc | _instBuffer_io_nEnqueued[2]
    & _instBuffer_io_dataOut_3_trap | _instBuffer_io_dataOut_3_isControlFlow & newCfDone_3
    & (~(nextAddrValid_3
         & ((noFire0Fault
               ? _faultLinkOk_T_15 | regLastIsBranch
                 & io_fault_bits_mepc == _faultLinkOk_T_16
               : ~io_inst_0_valid | _lane0LinkOk_T_15 | regLastIsBranch
                 & io_inst_0_bits_addr == _faultLinkOk_T_16)
            | _instBuffer_io_dataOut_3_isBranch
            & (noFire0Fault
                 ? io_fault_bits_mepc
                 : io_inst_0_valid
                     ? io_inst_0_bits_addr
                     : 32'h0) == _instBuffer_io_dataOut_3_addr + 32'h4)) | noFire0Fault)
    & ~_instBuffer_io_dataOut_3_isMpause;
  wire        currentDataDone_3 =
    resultBuffer_3_valid | _instBuffer_io_nEnqueued[2] & ~resultBuffer_3_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_3_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_3_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_3_idx
       | io_writeDataVector_0_valid
       & (_instBuffer_io_dataOut_3_isVector & _instBuffer_io_dataOut_3_idx != 7'h7E
          & io_writeDataVector_0_bits_uop_pc == _instBuffer_io_dataOut_3_addr
          | ~_instBuffer_io_dataOut_3_isVector
          & _vectorWriteIdxMap_T_32 == {1'h0, _instBuffer_io_dataOut_3_idx})
       & io_writeDataVector_0_bits_last_uop_valid | (&_instBuffer_io_dataOut_3_idx)
       | _instBuffer_io_dataOut_3_idx == 7'h7E & storeComplete_pipe_v
       & storeComplete_pipe_b == _instBuffer_io_dataOut_3_addr | currentTrap_3);
  wire        currentCfDone_3 =
    resultBuffer_3_valid & resultBuffer_3_bits_cfDone | newCfDone_3;
  wire        trapDetected_0 = currentDataDone & hi;
  wire        trapDetected_1 = currentDataDone_1 & currentTrap_1;
  wire        trapDetected_2 = currentDataDone_2 & currentTrap_2;
  wire        hasTrap =
    trapDetected_0 | trapDetected_1 | trapDetected_2 | currentDataDone_3 & currentTrap_3;
  wire [3:0]  _countValid_T_5 =
    ~{currentDataDone_3 & currentCfDone_3,
      currentDataDone_2 & currentCfDone_2,
      currentDataDone_1 & currentCfDone_1,
      currentDataDone & currentCfDone};
  wire [2:0]  countValid =
    _countValid_T_5[0]
      ? 3'h0
      : _countValid_T_5[1]
          ? 3'h1
          : _countValid_T_5[2] ? 3'h2 : _countValid_T_5[3] ? 3'h3 : 3'h4;
  wire [2:0]  _GEN_3 =
    {1'h0,
     (trapDetected_0 ? 2'h0 : trapDetected_1 ? 2'h1 : {1'h1, ~trapDetected_2}) + 2'h1};
  wire        trapReadyToRetire = hasTrap & _GEN_3 <= countValid;
  wire [2:0]  deqReady = trapReadyToRetire ? _GEN_3 : countValid;
  reg  [2:0]  deqReady_reg;
  reg  [2:0]  retiredEcalls_reg;
  reg         io_trapPending_REG;
  wire [11:0] shifted =
    {currentDataDone_3,
     currentTrap_3,
     currentCfDone_3,
     currentDataDone_2,
     currentTrap_2,
     currentCfDone_2,
     currentDataDone_1,
     currentTrap_1,
     currentCfDone_1,
     currentDataDone,
     hi,
     currentCfDone} >> {2'h0, deqReady} * 5'h3;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      storeComplete_pipe_v <= 1'h0;
      regLastTarget <= 32'h0;
      regLastAddr <= 32'h0;
      regLastIsBranch <= 1'h0;
      resultBuffer_0_valid <= 1'h0;
      resultBuffer_0_bits_trap <= 1'h0;
      resultBuffer_0_bits_cfDone <= 1'h0;
      resultBuffer_1_valid <= 1'h0;
      resultBuffer_1_bits_trap <= 1'h0;
      resultBuffer_1_bits_cfDone <= 1'h0;
      resultBuffer_2_valid <= 1'h0;
      resultBuffer_2_bits_trap <= 1'h0;
      resultBuffer_2_bits_cfDone <= 1'h0;
      resultBuffer_3_valid <= 1'h0;
      resultBuffer_3_bits_trap <= 1'h0;
      resultBuffer_3_bits_cfDone <= 1'h0;
      deqReady_reg <= 3'h0;
      retiredEcalls_reg <= 3'h0;
      io_trapPending_REG <= 1'h0;
    end
    else begin
      storeComplete_pipe_v <= io_storeComplete_valid;
      if (instsWithWriteFired) begin
        regLastTarget <=
          io_inst_0_bits_inst[6:0] == 7'h67 ? io_jalrTargets_0 : io_targets_0;
        regLastAddr <= io_inst_0_bits_addr;
        regLastIsBranch <= io_branch_0;
      end
      resultBuffer_0_valid <= ~trapReadyToRetire & shifted[2];
      resultBuffer_0_bits_trap <= ~trapReadyToRetire & shifted[1];
      resultBuffer_0_bits_cfDone <= ~trapReadyToRetire & shifted[0];
      resultBuffer_1_valid <= ~trapReadyToRetire & shifted[5];
      resultBuffer_1_bits_trap <= ~trapReadyToRetire & shifted[4];
      resultBuffer_1_bits_cfDone <= ~trapReadyToRetire & shifted[3];
      resultBuffer_2_valid <= ~trapReadyToRetire & shifted[8];
      resultBuffer_2_bits_trap <= ~trapReadyToRetire & shifted[7];
      resultBuffer_2_bits_cfDone <= ~trapReadyToRetire & shifted[6];
      resultBuffer_3_valid <= ~trapReadyToRetire & shifted[11];
      resultBuffer_3_bits_trap <= ~trapReadyToRetire & shifted[10];
      resultBuffer_3_bits_cfDone <= ~trapReadyToRetire & shifted[9];
      deqReady_reg <= deqReady;
      retiredEcalls_reg <=
        {1'h0,
         {1'h0, (|deqReady) & _instBuffer_io_dataOut_0_isEcall}
           + {1'h0, (|(deqReady[2:1])) & _instBuffer_io_dataOut_1_isEcall}}
        + {1'h0,
           {1'h0, deqReady > 3'h2 & _instBuffer_io_dataOut_2_isEcall}
             + {1'h0, deqReady[2] & _instBuffer_io_dataOut_3_isEcall}};
      io_trapPending_REG <= hasTrap & ~trapReadyToRetire;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io_storeComplete_valid)
      storeComplete_pipe_b <= io_storeComplete_bits;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;
        end
        storeComplete_pipe_v = _RANDOM[2'h0][0];
        storeComplete_pipe_b = {_RANDOM[2'h0][31:1], _RANDOM[2'h1][0]};
        regLastTarget = {_RANDOM[2'h1][31:1], _RANDOM[2'h2][0]};
        regLastAddr = {_RANDOM[2'h2][31:1], _RANDOM[2'h3][0]};
        regLastIsBranch = _RANDOM[2'h3][1];
        resultBuffer_0_valid = _RANDOM[2'h3][2];
        resultBuffer_0_bits_trap = _RANDOM[2'h3][3];
        resultBuffer_0_bits_cfDone = _RANDOM[2'h3][4];
        resultBuffer_1_valid = _RANDOM[2'h3][5];
        resultBuffer_1_bits_trap = _RANDOM[2'h3][6];
        resultBuffer_1_bits_cfDone = _RANDOM[2'h3][7];
        resultBuffer_2_valid = _RANDOM[2'h3][8];
        resultBuffer_2_bits_trap = _RANDOM[2'h3][9];
        resultBuffer_2_bits_cfDone = _RANDOM[2'h3][10];
        resultBuffer_3_valid = _RANDOM[2'h3][11];
        resultBuffer_3_bits_trap = _RANDOM[2'h3][12];
        resultBuffer_3_bits_cfDone = _RANDOM[2'h3][13];
        deqReady_reg = _RANDOM[2'h3][20:18];
        retiredEcalls_reg = _RANDOM[2'h3][23:21];
        io_trapPending_REG = _RANDOM[2'h3][24];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        storeComplete_pipe_v = 1'h0;
        regLastTarget = 32'h0;
        regLastAddr = 32'h0;
        regLastIsBranch = 1'h0;
        resultBuffer_0_valid = 1'h0;
        resultBuffer_0_bits_trap = 1'h0;
        resultBuffer_0_bits_cfDone = 1'h0;
        resultBuffer_1_valid = 1'h0;
        resultBuffer_1_bits_trap = 1'h0;
        resultBuffer_1_bits_cfDone = 1'h0;
        resultBuffer_2_valid = 1'h0;
        resultBuffer_2_bits_trap = 1'h0;
        resultBuffer_2_bits_cfDone = 1'h0;
        resultBuffer_3_valid = 1'h0;
        resultBuffer_3_bits_trap = 1'h0;
        resultBuffer_3_bits_cfDone = 1'h0;
        deqReady_reg = 3'h0;
        retiredEcalls_reg = 3'h0;
        io_trapPending_REG = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CircularBufferMulti_2 instBuffer (
    .clock                      (clock),
    .reset                      (reset),
    .io_enqValid
      ({1'h0, {1'h0, instsWithWriteFired} + {1'h0, decodeFaultValid | noFire0Fault}}),
    .io_enqData_0_addr          (noFire0Fault ? io_fault_bits_mepc : io_inst_0_bits_addr),
    .io_enqData_0_idx
      (io_writeAddrVector_0_valid
         ? {2'h0, io_writeAddrVector_0_addr} - 7'h40
         : noFire0Fault
             ? (io_writeAddrScalar_0_valid & (|io_writeAddrScalar_0_addr)
                  ? _GEN
                  : {6'h3F,
                     ~(io_inst_0_bits_inst[6:0] == 7'h23 | insts_instr_vectorStore)})
             : io_writeAddrScalar_0_valid & (|io_writeAddrScalar_0_addr)
                 ? _GEN
                 : {6'h3F, ~(io_inst_0_bits_inst[6:0] == 7'h23 | insts_vectorStore)}),
    .io_enqData_0_trap
      (noFire0Fault | decodeFaultValid & io_fault_bits_mepc == io_inst_0_bits_addr),
    .io_enqData_0_isControlFlow (io_jump_0 | io_branch_0),
    .io_enqData_0_isBranch      (io_branch_0),
    .io_enqData_0_isVector
      (noFire0Fault
         ? io_writeAddrVector_0_valid | insts_instr_vectorStore
         : io_writeAddrVector_0_valid | insts_vectorStore),
    .io_enqData_0_linkOk
      (noFire0Fault
         ? io_fault_bits_mepc == regLastTarget | regLastIsBranch
           & io_fault_bits_mepc == _faultLinkOk_T_16
         : _lane0LinkOk_T_15 | regLastIsBranch
           & io_inst_0_bits_addr == _faultLinkOk_T_16),
    .io_enqData_0_isEcall       (io_inst_0_bits_inst == 32'h73),
    .io_enqData_0_isMpause      (io_inst_0_bits_inst == 32'h8000073),
    .io_enqData_1_addr          (32'h0),
    .io_enqData_1_idx           (7'h0),
    .io_enqData_1_trap          (1'h0),
    .io_enqData_1_isControlFlow (1'h0),
    .io_enqData_1_isBranch      (1'h0),
    .io_enqData_1_isVector      (1'h0),
    .io_enqData_1_linkOk        (1'h0),
    .io_enqData_1_isEcall       (1'h0),
    .io_enqData_1_isMpause      (1'h0),
    .io_enqData_2_addr          (32'h0),
    .io_enqData_2_idx           (7'h0),
    .io_enqData_2_trap          (1'h0),
    .io_enqData_2_isControlFlow (1'h0),
    .io_enqData_2_isBranch      (1'h0),
    .io_enqData_2_isVector      (1'h0),
    .io_enqData_2_linkOk        (1'h0),
    .io_enqData_2_isEcall       (1'h0),
    .io_enqData_2_isMpause      (1'h0),
    .io_enqData_3_addr          (32'h0),
    .io_enqData_3_idx           (7'h0),
    .io_enqData_3_trap          (1'h0),
    .io_enqData_3_isControlFlow (1'h0),
    .io_enqData_3_isBranch      (1'h0),
    .io_enqData_3_isVector      (1'h0),
    .io_enqData_3_linkOk        (1'h0),
    .io_enqData_3_isEcall       (1'h0),
    .io_enqData_3_isMpause      (1'h0),
    .io_nEnqueued               (_instBuffer_io_nEnqueued),
    .io_nSpace                  (io_nSpace),
    .io_dataOut_0_addr          (_instBuffer_io_dataOut_0_addr),
    .io_dataOut_0_idx           (_instBuffer_io_dataOut_0_idx),
    .io_dataOut_0_trap          (_instBuffer_io_dataOut_0_trap),
    .io_dataOut_0_isControlFlow (_instBuffer_io_dataOut_0_isControlFlow),
    .io_dataOut_0_isBranch      (_instBuffer_io_dataOut_0_isBranch),
    .io_dataOut_0_isVector      (_instBuffer_io_dataOut_0_isVector),
    .io_dataOut_0_linkOk        (/* unused */),
    .io_dataOut_0_isEcall       (_instBuffer_io_dataOut_0_isEcall),
    .io_dataOut_0_isMpause      (_instBuffer_io_dataOut_0_isMpause),
    .io_dataOut_1_addr          (_instBuffer_io_dataOut_1_addr),
    .io_dataOut_1_idx           (_instBuffer_io_dataOut_1_idx),
    .io_dataOut_1_trap          (_instBuffer_io_dataOut_1_trap),
    .io_dataOut_1_isControlFlow (_instBuffer_io_dataOut_1_isControlFlow),
    .io_dataOut_1_isBranch      (_instBuffer_io_dataOut_1_isBranch),
    .io_dataOut_1_isVector      (_instBuffer_io_dataOut_1_isVector),
    .io_dataOut_1_linkOk        (_instBuffer_io_dataOut_1_linkOk),
    .io_dataOut_1_isEcall       (_instBuffer_io_dataOut_1_isEcall),
    .io_dataOut_1_isMpause      (_instBuffer_io_dataOut_1_isMpause),
    .io_dataOut_2_addr          (_instBuffer_io_dataOut_2_addr),
    .io_dataOut_2_idx           (_instBuffer_io_dataOut_2_idx),
    .io_dataOut_2_trap          (_instBuffer_io_dataOut_2_trap),
    .io_dataOut_2_isControlFlow (_instBuffer_io_dataOut_2_isControlFlow),
    .io_dataOut_2_isBranch      (_instBuffer_io_dataOut_2_isBranch),
    .io_dataOut_2_isVector      (_instBuffer_io_dataOut_2_isVector),
    .io_dataOut_2_linkOk        (_instBuffer_io_dataOut_2_linkOk),
    .io_dataOut_2_isEcall       (_instBuffer_io_dataOut_2_isEcall),
    .io_dataOut_2_isMpause      (_instBuffer_io_dataOut_2_isMpause),
    .io_dataOut_3_addr          (_instBuffer_io_dataOut_3_addr),
    .io_dataOut_3_idx           (_instBuffer_io_dataOut_3_idx),
    .io_dataOut_3_trap          (_instBuffer_io_dataOut_3_trap),
    .io_dataOut_3_isControlFlow (_instBuffer_io_dataOut_3_isControlFlow),
    .io_dataOut_3_isBranch      (_instBuffer_io_dataOut_3_isBranch),
    .io_dataOut_3_isVector      (_instBuffer_io_dataOut_3_isVector),
    .io_dataOut_3_linkOk        (_instBuffer_io_dataOut_3_linkOk),
    .io_dataOut_3_isEcall       (_instBuffer_io_dataOut_3_isEcall),
    .io_dataOut_3_isMpause      (_instBuffer_io_dataOut_3_isMpause),
    .io_deqReady                (deqReady),
    .io_flush                   (trapReadyToRetire)
  );
  assign io_nRetired = deqReady_reg - retiredEcalls_reg;
  assign io_empty = _instBuffer_io_nEnqueued == 3'h0;
  assign io_trapPending = io_trapPending_REG;
endmodule

