// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
// description: 
// This is the top module of MUL/MAC wrapper
// Contains instantiation of MUL_ex and MAC_ex
// Contains ex arbiter
//
// feature list:
// 1. Instantiation of MUL ex and MAC ex
// 2. Arbitration to uop0/1 to use MUL or MAC
// 3. Pop MUL_RS 


`ifndef HDL_VERILOG_RVV_DESIGN_RVV_SVH
`include "rvv_backend.svh"
`endif
`ifndef RVV_ASSERT__SVH
`include "rvv_backend_sva.svh"
`endif

module rvv_backend_mulmac (
  clk,
  rst_n,
  trap_flush_rvv,
  uop_valid_rs2ex,
  mac_uop_rs2ex,
  pop,
  res_valid_ex2rob,
  res_ex2rob,
  res_ready_rob2ex
);

//global signals
input   logic                     clk;
input   logic                     rst_n;
input   logic                     trap_flush_rvv;

//MUL_RS to MUL_EX 
input   logic     [`NUM_MUL-1:0]  uop_valid_rs2ex;
input   MUL_RS_t  [`NUM_MUL-1:0]  mac_uop_rs2ex;
output  logic     [`NUM_MUL-1:0]  pop;

//MUL_EX to ROB
output  logic     [`NUM_MUL-1:0]  res_valid_ex2rob;
output  PU2ROB_t  [`NUM_MUL-1:0]  res_ex2rob;
input   logic     [`NUM_MUL-1:0]  res_ready_rob2ex;

// Wires & Regs
logic             [`NUM_MUL-1:0]  mac_valid;
MUL_RS_t          [`NUM_MUL-1:0]  mac_uop;
logic             [`NUM_MUL-1:0]  mac_ready;
logic             [`NUM_MUL-1:0]  mac_pipe_vld_en;
logic             [`NUM_MUL-1:0]  mac_pipe_data_en;
integer                            lane_idx;
integer                            search_idx;
integer                            selected_idx;
logic             [`NUM_MUL-1:0]  uop_taken;

genvar                            i;

// handshake
assign mac_ready = ~res_valid_ex2rob | res_ready_rob2ex;

always_comb begin
  // WORKTREE-EXPERIMENT: remove the 2-lane hard-code so later MAC-lane
  // expansion can be evaluated without first rewriting this wrapper again.
  mac_valid = 'b0;
  mac_uop   = 'b0;
  pop       = 'b0;
  uop_taken = 'b0;

  for (lane_idx = 0; lane_idx < `NUM_MUL; lane_idx++) begin
    selected_idx = -1;

    if (mac_ready[lane_idx]) begin
      for (search_idx = 0; search_idx < `NUM_MUL; search_idx++) begin
        if ((selected_idx < 0) && uop_valid_rs2ex[search_idx] && !uop_taken[search_idx]) begin
          selected_idx = search_idx;
        end
      end

      if (selected_idx >= 0) begin
        mac_valid[lane_idx] = 1'b1;
        mac_uop[lane_idx]   = mac_uop_rs2ex[selected_idx];
        pop[selected_idx]   = 1'b1;
        uop_taken[selected_idx] = 1'b1;
      end
    end
  end
end

// pipe register enable
assign mac_pipe_vld_en  = mac_valid | res_valid_ex2rob&res_ready_rob2ex;  // enable for pipeline vld register
assign mac_pipe_data_en = mac_valid;                                      // enable for pipeline data register

// Inst of MAC-ex
generate
  for(i=0;i<`NUM_MUL;i++) begin: INST_MAC
    rvv_backend_mac_unit #(
    ) u_mac (
      // Outputs
      .mac2rob_uop_valid  (res_valid_ex2rob[i]),
      .mac2rob_uop_data   (res_ex2rob[i]),
      // Inputs
      .clk                (clk), 
      .rst_n              (rst_n), 
      .rs2mac_uop_valid   (mac_valid[i]), 
      .rs2mac_uop_data    (mac_uop[i]),
      .mac_pipe_vld_en    (mac_pipe_vld_en[i]),
      .mac_pipe_data_en   (mac_pipe_data_en[i]),
      .trap_flush_rvv     (trap_flush_rvv)
    );
  end

endgenerate

endmodule