// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
module RvvCoreWrapper(
    input clk,
    input rstn,
    input logic [6:0] vstart,
    input logic [1:0] vxrm,
    input logic vxsat,
    input logic [2:0] frm,
    input inst_0_valid,
    input [31:0] inst_0_bits_pc,
    input [1:0] inst_0_bits_opcode,
    input [24:0] inst_0_bits_bits,
    input rs_0_valid,
    input [31:0] rs_0_data,
    input rs_1_valid,
    input [31:0] rs_1_data,
    input [31:0] frs_0,
    output inst_0_ready,
    output rd_0_valid,
    output [4:0] rd_0_bits_addr,
    output [31:0] rd_0_bits_data,
    output async_rd_valid,
    output [4:0] async_rd_bits_addr,
    output [31:0] async_rd_bits_data,
    input async_rd_ready,
    output async_frd_valid,
    output [4:0] async_frd_bits_addr,
    output [31:0] async_frd_bits_data,
    input async_frd_ready,
    output rvv2lsu_0_valid,
    output rvv2lsu_0_bits_idx_valid,
    output [4:0] rvv2lsu_0_bits_idx_bits_addr,
    output [128-1:0] rvv2lsu_0_bits_idx_bits_data,
    output rvv2lsu_0_bits_vregfile_valid,
    output [4:0] rvv2lsu_0_bits_vregfile_bits_addr,
    output [128-1:0] rvv2lsu_0_bits_vregfile_bits_data,
    output rvv2lsu_0_bits_mask_valid,
    output [(128/8)-1:0] rvv2lsu_0_bits_mask_bits,
    input rvv2lsu_0_ready,
    output rvv2lsu_1_valid,
    output rvv2lsu_1_bits_idx_valid,
    output [4:0] rvv2lsu_1_bits_idx_bits_addr,
    output [128-1:0] rvv2lsu_1_bits_idx_bits_data,
    output rvv2lsu_1_bits_vregfile_valid,
    output [4:0] rvv2lsu_1_bits_vregfile_bits_addr,
    output [128-1:0] rvv2lsu_1_bits_vregfile_bits_data,
    output rvv2lsu_1_bits_mask_valid,
    output [(128/8)-1:0] rvv2lsu_1_bits_mask_bits,
    input rvv2lsu_1_ready,
    input lsu2rvv_0_valid,
    input [4:0] lsu2rvv_0_bits_addr,
    input [128-1:0] lsu2rvv_0_bits_data,
    input  lsu2rvv_0_bits_last,
    output lsu2rvv_0_ready,
    input lsu2rvv_1_valid,
    input [4:0] lsu2rvv_1_bits_addr,
    input [128-1:0] lsu2rvv_1_bits_data,
    input  lsu2rvv_1_bits_last,
    output lsu2rvv_1_ready,
    output vcsr_valid,
    output [6:0] vcsr_vstart,
    output [1:0] vcsr_xrm,
    output vcsr_vxsat,
    input vcsr_ready,
    output configStateValid,
    output [7:0] configVl,
    output [6:0] configVstart,
    output configMa,
    output configTa,
    output [1:0] configXrm,
    output [2:0] configSew,
    output [2:0] configLmul,
    output [2:0] configLmulOrig,
    output configVill,
    output [31:0] configMtype,
    output logic rvv_idle,
    output logic [3:0] queue_capacity,

    output rd_rob2rt_o_0_valid,
    output rd_rob2rt_o_0_w_valid,
    output [4:0] rd_rob2rt_o_0_w_index,
    output [127:0] rd_rob2rt_o_0_w_data,
    output rd_rob2rt_o_0_w_type,
    output [15:0] rd_rob2rt_o_0_vd_type,
    output rd_rob2rt_o_0_trap_flag,
    output rd_rob2rt_o_0_vector_csr_vl,
    output rd_rob2rt_o_0_vector_csr_vstart,
    output rd_rob2rt_o_0_vector_csr_ma,
    output rd_rob2rt_o_0_vector_csr_ta,
    output rd_rob2rt_o_0_vector_csr_xrm,
    output rd_rob2rt_o_0_vector_csr_sew,
    output rd_rob2rt_o_0_vector_csr_lmul,
    output rd_rob2rt_o_0_vector_csr_lmul_orig,
    output rd_rob2rt_o_0_vector_csr_vill,
    output [15:0] rd_rob2rt_o_0_vxsaturate,
    output [31:0] rd_rob2rt_o_0_uop_pc,
    output rd_rob2rt_o_0_last_uop_valid,
            
    output trap_valid,
    output [31:0] trap_bits_pc,
    output [1:0] trap_bits_opcode,
    output [24:0] trap_bits_bits,
    output wr_vxsat_valid_o,
    output wr_vxsat_o
);
  logic [1-1:0] inst_valid;
  assign inst_valid[0] = inst_0_valid;
  RVVInstruction [1-1:0] inst_data;
  assign inst_data[0].pc = inst_0_bits_pc;
  assign inst_data[0].opcode = RVVOpCode'(inst_0_bits_opcode);
  assign inst_data[0].bits = inst_0_bits_bits;
  logic [1-1:0] inst_ready;
  logic [2*1-1:0] reg_read_valid;
  assign reg_read_valid[0] = rs_0_valid;
  assign reg_read_valid[1] = rs_1_valid;
  logic [2*1-1:0][31:0] reg_read_data;
  assign reg_read_data[0] = rs_0_data;
  assign reg_read_data[1] = rs_1_data;
  logic [1-1:0][31:0] freg_read_data;
  assign freg_read_data[0] = frs_0;
  logic [`NUM_LSU-1:0] uop_lsu_valid_rvv2lsu;
  logic [`NUM_LSU-1:0] uop_lsu_idx_valid_rvv2lsu;
  logic [`NUM_LSU-1:0][4:0] uop_lsu_idx_addr_rvv2lsu;
  logic [`NUM_LSU-1:0][128-1:0] uop_lsu_idx_data_rvv2lsu;
  logic [`NUM_LSU-1:0] uop_lsu_vregfile_valid_rvv2lsu;
  logic [`NUM_LSU-1:0][4:0] uop_lsu_vregfile_addr_rvv2lsu;
  logic [`NUM_LSU-1:0][128-1:0] uop_lsu_vregfile_data_rvv2lsu;
  logic [`NUM_LSU-1:0] uop_lsu_v0_valid_rvv2lsu;
  logic [`NUM_LSU-1:0][(128/8)-1:0] uop_lsu_v0_data_rvv2lsu;
  logic [`NUM_LSU-1:0] uop_lsu_ready_lsu2rvv;
  assign rvv2lsu_0_valid = uop_lsu_valid_rvv2lsu[0];
  assign rvv2lsu_0_bits_idx_valid = uop_lsu_idx_valid_rvv2lsu[0];
  assign rvv2lsu_0_bits_idx_bits_addr = uop_lsu_idx_addr_rvv2lsu[0];
  assign rvv2lsu_0_bits_idx_bits_data = uop_lsu_idx_data_rvv2lsu[0];
  assign rvv2lsu_0_bits_vregfile_valid = uop_lsu_vregfile_valid_rvv2lsu[0];
  assign rvv2lsu_0_bits_vregfile_bits_addr = uop_lsu_vregfile_addr_rvv2lsu[0];
  assign rvv2lsu_0_bits_vregfile_bits_data = uop_lsu_vregfile_data_rvv2lsu[0];
  assign rvv2lsu_0_bits_mask_valid = uop_lsu_v0_valid_rvv2lsu[0];
  assign rvv2lsu_0_bits_mask_bits = uop_lsu_v0_data_rvv2lsu[0];
  assign uop_lsu_ready_lsu2rvv[0] = rvv2lsu_0_ready;

  generate
    if (`NUM_LSU > 1) begin : gen_lsu_port1
      assign rvv2lsu_1_valid = uop_lsu_valid_rvv2lsu[1];
      assign rvv2lsu_1_bits_idx_valid = uop_lsu_idx_valid_rvv2lsu[1];
      assign rvv2lsu_1_bits_idx_bits_addr = uop_lsu_idx_addr_rvv2lsu[1];
      assign rvv2lsu_1_bits_idx_bits_data = uop_lsu_idx_data_rvv2lsu[1];
      assign rvv2lsu_1_bits_vregfile_valid = uop_lsu_vregfile_valid_rvv2lsu[1];
      assign rvv2lsu_1_bits_vregfile_bits_addr = uop_lsu_vregfile_addr_rvv2lsu[1];
      assign rvv2lsu_1_bits_vregfile_bits_data = uop_lsu_vregfile_data_rvv2lsu[1];
      assign rvv2lsu_1_bits_mask_valid = uop_lsu_v0_valid_rvv2lsu[1];
      assign rvv2lsu_1_bits_mask_bits = uop_lsu_v0_data_rvv2lsu[1];
      assign uop_lsu_ready_lsu2rvv[1] = rvv2lsu_1_ready;
    end else begin : gen_lsu_port1_tieoff
      assign rvv2lsu_1_valid = 1'b0;
      assign rvv2lsu_1_bits_idx_valid = 1'b0;
      assign rvv2lsu_1_bits_idx_bits_addr = '0;
      assign rvv2lsu_1_bits_idx_bits_data = '0;
      assign rvv2lsu_1_bits_vregfile_valid = 1'b0;
      assign rvv2lsu_1_bits_vregfile_bits_addr = '0;
      assign rvv2lsu_1_bits_vregfile_bits_data = '0;
      assign rvv2lsu_1_bits_mask_valid = 1'b0;
      assign rvv2lsu_1_bits_mask_bits = '0;
    end
  endgenerate
  logic [`NUM_LSU-1:0] uop_lsu_valid_lsu2rvv;
  logic [`NUM_LSU-1:0][4:0] uop_lsu_addr_lsu2rvv;
  logic [`NUM_LSU-1:0][128-1:0] uop_lsu_wdata_lsu2rvv;
  logic [`NUM_LSU-1:0] uop_lsu_last_lsu2rvv;
  logic [`NUM_LSU-1:0] uop_lsu_ready_rvv2lsu;
  assign uop_lsu_valid_lsu2rvv[0] = lsu2rvv_0_valid;
  assign uop_lsu_addr_lsu2rvv[0] = lsu2rvv_0_bits_addr;
  assign uop_lsu_wdata_lsu2rvv[0] = lsu2rvv_0_bits_data;
  assign uop_lsu_last_lsu2rvv[0] = lsu2rvv_0_bits_last;
  assign lsu2rvv_0_ready = uop_lsu_ready_rvv2lsu[0];

  generate
    if (`NUM_LSU > 1) begin : gen_lsu_fb1
      assign uop_lsu_valid_lsu2rvv[1] = lsu2rvv_1_valid;
      assign uop_lsu_addr_lsu2rvv[1] = lsu2rvv_1_bits_addr;
      assign uop_lsu_wdata_lsu2rvv[1] = lsu2rvv_1_bits_data;
      assign uop_lsu_last_lsu2rvv[1] = lsu2rvv_1_bits_last;
      assign lsu2rvv_1_ready = uop_lsu_ready_rvv2lsu[1];
    end else begin : gen_lsu_fb1_tieoff
      assign lsu2rvv_1_ready = 1'b0;
    end
  endgenerate
  logic [1-1:0] reg_write_valid;
  logic [1-1:0][4:0] reg_write_addr;
  logic [1-1:0][31:0] reg_write_data;
  RVVConfigState vector_csr;
  assign vcsr_vstart = vector_csr.vstart;
  assign vcsr_xrm = vector_csr.xrm;
  assign vcsr_vxsat = vector_csr.xsat;
  RVVConfigState config_state;
  ROB2RT_t [0:0] rd_rob2rt_o;
  logic [0:0] rd_valid_rob2rt_o;
  RVVInstruction trap_data;
  RvvCore#(.N (1)) core(
      .clk(clk),
      .rstn(rstn),
      .vstart(vstart),
      .vxrm(vxrm),
      .vxsat(vxsat),
      .frm(frm),
      .inst_valid(inst_valid),
      .inst_data(inst_data),
      .inst_ready(inst_ready),
      .reg_read_valid(reg_read_valid),
      .reg_read_data(reg_read_data),
      .freg_read_data(freg_read_data),
      .reg_write_valid(reg_write_valid),
      .reg_write_addr(reg_write_addr),
      .reg_write_data(reg_write_data),
      .async_rd_valid(async_rd_valid),
      .async_rd_addr(async_rd_bits_addr),
      .async_rd_data(async_rd_bits_data),
      .async_rd_ready(async_rd_ready),
      .async_frd_valid(async_frd_valid),
      .async_frd_addr(async_frd_bits_addr),
      .async_frd_data(async_frd_bits_data),
      .async_frd_ready(async_frd_ready),
      .uop_lsu_valid_rvv2lsu(uop_lsu_valid_rvv2lsu),
      .uop_lsu_idx_valid_rvv2lsu(uop_lsu_idx_valid_rvv2lsu),
      .uop_lsu_idx_addr_rvv2lsu(uop_lsu_idx_addr_rvv2lsu),
      .uop_lsu_idx_data_rvv2lsu(uop_lsu_idx_data_rvv2lsu),
      .uop_lsu_vregfile_valid_rvv2lsu(uop_lsu_vregfile_valid_rvv2lsu),
      .uop_lsu_vregfile_addr_rvv2lsu(uop_lsu_vregfile_addr_rvv2lsu),
      .uop_lsu_vregfile_data_rvv2lsu(uop_lsu_vregfile_data_rvv2lsu),
      .uop_lsu_v0_valid_rvv2lsu(uop_lsu_v0_valid_rvv2lsu),
      .uop_lsu_v0_data_rvv2lsu(uop_lsu_v0_data_rvv2lsu),
      .uop_lsu_ready_lsu2rvv(uop_lsu_ready_lsu2rvv),
      .uop_lsu_valid_lsu2rvv(uop_lsu_valid_lsu2rvv),
      .uop_lsu_addr_lsu2rvv(uop_lsu_addr_lsu2rvv),
      .uop_lsu_wdata_lsu2rvv(uop_lsu_wdata_lsu2rvv),
      .uop_lsu_last_lsu2rvv(uop_lsu_last_lsu2rvv),
      .uop_lsu_ready_rvv2lsu(uop_lsu_ready_rvv2lsu),
      .vcsr_valid(vcsr_valid),
      .vector_csr(vector_csr),
      .vcsr_ready(vcsr_ready),
      .config_state_valid(configStateValid),
      .config_state(config_state),
      .rvv_idle(rvv_idle),
      .queue_capacity(queue_capacity),
      .rd_valid_rob2rt_o(rd_valid_rob2rt_o),
      .rd_rob2rt_o(rd_rob2rt_o),
      .trap_valid_o(trap_valid),
      .trap_data_o(trap_data),
      .wr_vxsat_valid_o(wr_vxsat_valid_o),
      .wr_vxsat_o(wr_vxsat_o)
  );
  assign rd_rob2rt_o_0_valid = rd_valid_rob2rt_o[0];
  assign rd_rob2rt_o_0_w_valid = rd_rob2rt_o[0].w_valid;
  assign rd_rob2rt_o_0_w_index = rd_rob2rt_o[0].w_index;
  assign rd_rob2rt_o_0_w_data = rd_rob2rt_o[0].w_data;
  assign rd_rob2rt_o_0_w_type = rd_rob2rt_o[0].w_type;
  assign rd_rob2rt_o_0_vd_type = rd_rob2rt_o[0].vd_type;
  assign rd_rob2rt_o_0_trap_flag = rd_rob2rt_o[0].trap_flag;
  assign rd_rob2rt_o_0_vector_csr_vl = rd_rob2rt_o[0].vector_csr.vl;
  assign rd_rob2rt_o_0_vector_csr_vstart = rd_rob2rt_o[0].vector_csr.vstart;
  assign rd_rob2rt_o_0_vector_csr_ma = rd_rob2rt_o[0].vector_csr.ma;
  assign rd_rob2rt_o_0_vector_csr_ta = rd_rob2rt_o[0].vector_csr.ta;
  assign rd_rob2rt_o_0_vector_csr_xrm = rd_rob2rt_o[0].vector_csr.xrm;
  assign rd_rob2rt_o_0_vector_csr_sew = rd_rob2rt_o[0].vector_csr.sew;
  assign rd_rob2rt_o_0_vector_csr_lmul = rd_rob2rt_o[0].vector_csr.lmul;
  assign rd_rob2rt_o_0_vector_csr_lmul_orig = rd_rob2rt_o[0].vector_csr.lmul_orig;
  assign rd_rob2rt_o_0_vector_csr_vill = rd_rob2rt_o[0].vector_csr.vill;
  assign rd_rob2rt_o_0_vxsaturate = rd_rob2rt_o[0].vxsaturate;
`ifdef TB_SUPPORT
  assign rd_rob2rt_o_0_uop_pc = rd_rob2rt_o[0].uop_pc;
  assign rd_rob2rt_o_0_last_uop_valid = rd_rob2rt_o[0].last_uop_valid;
`else
  assign rd_rob2rt_o_0_uop_pc = 32'b0;
  assign rd_rob2rt_o_0_last_uop_valid = 1'b0;
`endif
  assign trap_bits_pc = trap_data.pc;
  assign trap_bits_opcode = trap_data.opcode;
  assign trap_bits_bits = trap_data.bits;
  assign inst_0_ready = inst_ready[0];
  assign rd_0_valid = reg_write_valid[0];
  assign rd_0_bits_addr = reg_write_addr[0];
  assign rd_0_bits_data = reg_write_data[0];
  assign configVl = config_state.vl;
  assign configVstart = config_state.vstart;
  assign configMa = config_state.ma;
  assign configTa = config_state.ta;
  assign configXrm = config_state.xrm;
  assign configSew = config_state.sew;
  assign configLmul = config_state.lmul;
  assign configLmulOrig = config_state.lmul_orig;
  assign configVill = config_state.vill;
`ifdef ZVT_ON
  assign configMtype = {8'd0, config_state.tm, 2'd0, config_state.tk, 3'd0, config_state.mtwiden};
`else
  assign configMtype = 32'd0;
`endif
endmodule
