// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SCore(
  input          clock,
                 reset,
  input  [31:0]  io_csr_in_value_0,
  output [31:0]  io_csr_out_value_0,
                 io_csr_out_value_1,
                 io_csr_out_value_2,
                 io_csr_out_value_3,
                 io_csr_out_value_4,
                 io_csr_out_value_5,
                 io_csr_out_value_6,
                 io_csr_out_value_7,
                 io_csr_out_value_8,
  output         io_halted,
                 io_fault,
                 io_wfi,
  input          io_irq,
                 io_dm_debug_req,
                 io_dm_resume_req,
                 io_dm_csr_valid,
  input  [4:0]   io_dm_csr_bits_addr,
  input  [11:0]  io_dm_csr_bits_index,
  input  [4:0]   io_dm_csr_bits_rs1,
  input  [1:0]   io_dm_csr_bits_op,
  input  [31:0]  io_dm_csr_rs1,
  output         io_dm_csr_rd_valid,
  output [31:0]  io_dm_csr_rd_bits,
  output         io_dm_scalar_rd_ready,
  input          io_dm_scalar_rd_valid,
  input  [4:0]   io_dm_scalar_rd_bits_addr,
  input  [31:0]  io_dm_scalar_rd_bits_data,
  input  [4:0]   io_dm_scalar_rs_idx,
  output [31:0]  io_dm_scalar_rs_data,
  output         io_dm_debug_mode,
  input          io_timer_irq,
                 io_software_irq,
  output         io_ibus_valid,
  input          io_ibus_ready,
  output [31:0]  io_ibus_addr,
  input  [127:0] io_ibus_rdata,
  input          io_ibus_fault_valid,
  output         io_dbus_valid,
                 io_dbus_write,
  output [31:0]  io_dbus_addr,
  output [127:0] io_dbus_wdata,
  output [15:0]  io_dbus_wmask,
  input  [127:0] io_dbus_rdata,
  output         io_ebus_dbus_valid,
  input          io_ebus_dbus_ready,
  output         io_ebus_dbus_write,
  output [31:0]  io_ebus_dbus_pc,
                 io_ebus_dbus_addr,
  output [4:0]   io_ebus_dbus_size,
  output [127:0] io_ebus_dbus_wdata,
  output [15:0]  io_ebus_dbus_wmask,
  input  [127:0] io_ebus_dbus_rdata,
  input          io_ebus_fault_valid,
                 io_ebus_fault_bits_write,
  input  [31:0]  io_ebus_fault_bits_addr,
                 io_ebus_fault_bits_epc,
  input          io_rvvcore_inst_0_ready,
  output         io_rvvcore_inst_0_valid,
  output [31:0]  io_rvvcore_inst_0_bits_pc,
  output [1:0]   io_rvvcore_inst_0_bits_opcode,
  output [24:0]  io_rvvcore_inst_0_bits_bits,
  output         io_rvvcore_rs_0_valid,
  output [31:0]  io_rvvcore_rs_0_data,
  output         io_rvvcore_rs_1_valid,
  output [31:0]  io_rvvcore_rs_1_data,
  input          io_rvvcore_rd_0_valid,
  input  [4:0]   io_rvvcore_rd_0_bits_addr,
  input  [31:0]  io_rvvcore_rd_0_bits_data,
  output         io_rvvcore_rvv2lsu_0_ready,
  input          io_rvvcore_rvv2lsu_0_valid,
                 io_rvvcore_rvv2lsu_0_bits_idx_valid,
  input  [127:0] io_rvvcore_rvv2lsu_0_bits_idx_bits_data,
  input          io_rvvcore_rvv2lsu_0_bits_vregfile_valid,
  input  [127:0] io_rvvcore_rvv2lsu_0_bits_vregfile_bits_data,
  input          io_rvvcore_rvv2lsu_0_bits_mask_valid,
  input  [15:0]  io_rvvcore_rvv2lsu_0_bits_mask_bits,
  input          io_rvvcore_lsu2rvv_0_ready,
  output         io_rvvcore_lsu2rvv_0_valid,
  output [4:0]   io_rvvcore_lsu2rvv_0_bits_addr,
  output [127:0] io_rvvcore_lsu2rvv_0_bits_data,
  output         io_rvvcore_lsu2rvv_0_bits_last,
  input          io_rvvcore_configState_valid,
  input  [7:0]   io_rvvcore_configState_bits_vl,
  input  [6:0]   io_rvvcore_configState_bits_vstart,
  input          io_rvvcore_configState_bits_ma,
                 io_rvvcore_configState_bits_ta,
  input  [2:0]   io_rvvcore_configState_bits_sew,
                 io_rvvcore_configState_bits_lmul,
                 io_rvvcore_configState_bits_lmul_orig,
  input          io_rvvcore_configState_bits_vill,
  output         io_rvvcore_async_rd_ready,
  input          io_rvvcore_async_rd_valid,
  input  [4:0]   io_rvvcore_async_rd_bits_addr,
  input  [31:0]  io_rvvcore_async_rd_bits_data,
  input          io_rvvcore_trap_valid,
  input  [31:0]  io_rvvcore_trap_bits_pc,
  input  [1:0]   io_rvvcore_trap_bits_opcode,
  input  [24:0]  io_rvvcore_trap_bits_bits,
  input  [6:0]   io_rvvcore_csr_vstart,
  input  [1:0]   io_rvvcore_csr_vxrm,
  input          io_rvvcore_csr_vxsat,
  output [2:0]   io_rvvcore_csr_frm,
  output         io_rvvcore_csr_vstart_write_valid,
  output [6:0]   io_rvvcore_csr_vstart_write_bits,
  output         io_rvvcore_csr_vxrm_write_valid,
  output [1:0]   io_rvvcore_csr_vxrm_write_bits,
  output         io_rvvcore_csr_vxsat_write_valid,
                 io_rvvcore_csr_vxsat_write_bits,
  input          io_rvvcore_rvv_idle,
  input  [3:0]   io_rvvcore_queue_capacity,
  input          io_rvvcore_rd_rob2rt_o_0_valid,
  input  [4:0]   io_rvvcore_rd_rob2rt_o_0_w_index,
  input  [31:0]  io_rvvcore_rd_rob2rt_o_0_uop_pc,
  input          io_rvvcore_rd_rob2rt_o_0_last_uop_valid
);

  wire        _arb_io_in_1_ready;
  wire        _arb_io_out_valid;
  wire [4:0]  _arb_io_out_bits_addr;
  wire [31:0] _arb_io_out_bits_data;
  wire        _csrReqArbiter_io_out_valid;
  wire [4:0]  _csrReqArbiter_io_out_bits_addr;
  wire [11:0] _csrReqArbiter_io_out_bits_index;
  wire [4:0]  _csrReqArbiter_io_out_bits_rs1;
  wire [1:0]  _csrReqArbiter_io_out_bits_op;
  wire        _dvu_io_req_ready;
  wire        _dvu_io_rd_valid;
  wire [4:0]  _dvu_io_rd_bits_addr;
  wire [31:0] _dvu_io_rd_bits_data;
  wire        _mlu_io_rd_valid;
  wire [4:0]  _mlu_io_rd_bits_addr;
  wire [31:0] _mlu_io_rd_bits_data;
  wire        _bru_0_io_csr_in_mode_valid;
  wire        _bru_0_io_csr_in_mcause_valid;
  wire [31:0] _bru_0_io_csr_in_mcause_bits;
  wire        _bru_0_io_csr_in_mepc_valid;
  wire [31:0] _bru_0_io_csr_in_mepc_bits;
  wire        _bru_0_io_csr_in_mtval_valid;
  wire [31:0] _bru_0_io_csr_in_mtval_bits;
  wire        _bru_0_io_csr_in_halt;
  wire        _bru_0_io_csr_in_fault;
  wire        _bru_0_io_csr_in_wfi;
  wire        _bru_0_io_rd_valid;
  wire [4:0]  _bru_0_io_rd_bits_addr;
  wire [31:0] _bru_0_io_rd_bits_data;
  wire        _bru_0_io_taken_valid;
  wire [31:0] _bru_0_io_taken_value;
  wire        _bru_0_io_actually_taken;
  wire [31:0] _bru_0_io_real_target;
  wire        _bru_0_io_interlock;
  wire        _alu_0_io_rd_valid;
  wire [4:0]  _alu_0_io_rd_bits_addr;
  wire [31:0] _alu_0_io_rd_bits_data;
  wire [2:0]  _retirement_buffer_io_nSpace;
  wire [2:0]  _retirement_buffer_io_nRetired;
  wire        _retirement_buffer_io_empty;
  wire        _retirement_buffer_io_trapPending;
  wire        _fault_manager_io_out_valid;
  wire [31:0] _fault_manager_io_out_bits_mepc;
  wire [31:0] _fault_manager_io_out_bits_mtval;
  wire [31:0] _fault_manager_io_out_bits_mcause;
  wire        _fault_manager_io_out_bits_decode;
  wire        _lsu_io_req_0_ready;
  wire        _lsu_io_rd_valid;
  wire [4:0]  _lsu_io_rd_bits_addr;
  wire [31:0] _lsu_io_rd_bits_data;
  wire        _lsu_io_ibus_valid;
  wire [31:0] _lsu_io_ibus_addr;
  wire        _lsu_io_fault_valid;
  wire        _lsu_io_fault_bits_write;
  wire [31:0] _lsu_io_fault_bits_addr;
  wire [31:0] _lsu_io_fault_bits_epc;
  wire [2:0]  _lsu_io_queueCapacity;
  wire        _lsu_io_active;
  wire        _lsu_io_storeComplete_valid;
  wire [31:0] _lsu_io_storeComplete_bits;
  wire        _dispatch_io_csrFault_0;
  wire        _dispatch_io_jalFault_0;
  wire        _dispatch_io_jalrFault_0;
  wire        _dispatch_io_bxxFault_0;
  wire        _dispatch_io_undefFault_0;
  wire        _dispatch_io_rvvFault_0;
  wire [31:0] _dispatch_io_bruTarget_0;
  wire        _dispatch_io_inst_0_ready;
  wire        _dispatch_io_rs1Read_0_valid;
  wire [4:0]  _dispatch_io_rs1Read_0_addr;
  wire        _dispatch_io_rs1Set_0_valid;
  wire [31:0] _dispatch_io_rs1Set_0_value;
  wire        _dispatch_io_rs2Read_0_valid;
  wire [4:0]  _dispatch_io_rs2Read_0_addr;
  wire        _dispatch_io_rs2Set_0_valid;
  wire [31:0] _dispatch_io_rs2Set_0_value;
  wire        _dispatch_io_rdMark_0_valid;
  wire [4:0]  _dispatch_io_rdMark_0_addr;
  wire        _dispatch_io_busRead_0_immen;
  wire [31:0] _dispatch_io_busRead_0_immed;
  wire        _dispatch_io_rvvRdMark_0_valid;
  wire [4:0]  _dispatch_io_rvvRdMark_0_addr;
  wire        _dispatch_io_alu_0_valid;
  wire [4:0]  _dispatch_io_alu_0_bits_addr;
  wire [4:0]  _dispatch_io_alu_0_bits_op;
  wire        _dispatch_io_bru_0_valid;
  wire        _dispatch_io_bru_0_bits_fwd;
  wire [3:0]  _dispatch_io_bru_0_bits_op;
  wire [31:0] _dispatch_io_bru_0_bits_pc;
  wire [31:0] _dispatch_io_bru_0_bits_target;
  wire [4:0]  _dispatch_io_bru_0_bits_link;
  wire        _dispatch_io_csr_valid;
  wire [4:0]  _dispatch_io_csr_bits_addr;
  wire [11:0] _dispatch_io_csr_bits_index;
  wire [4:0]  _dispatch_io_csr_bits_rs1;
  wire [1:0]  _dispatch_io_csr_bits_op;
  wire        _dispatch_io_lsu_0_valid;
  wire        _dispatch_io_lsu_0_bits_store;
  wire [4:0]  _dispatch_io_lsu_0_bits_addr;
  wire [4:0]  _dispatch_io_lsu_0_bits_op;
  wire [31:0] _dispatch_io_lsu_0_bits_pc;
  wire [2:0]  _dispatch_io_lsu_0_bits_elemWidth;
  wire [2:0]  _dispatch_io_lsu_0_bits_nfields;
  wire [4:0]  _dispatch_io_lsu_0_bits_bit24To20;
  wire        _dispatch_io_mlu_0_valid;
  wire [4:0]  _dispatch_io_mlu_0_bits_addr;
  wire [2:0]  _dispatch_io_mlu_0_bits_op;
  wire        _dispatch_io_dvu_0_valid;
  wire [4:0]  _dispatch_io_dvu_0_bits_addr;
  wire [1:0]  _dispatch_io_dvu_0_bits_op;
  wire        _dispatch_io_branch_0;
  wire        _dispatch_io_jump_0;
  wire        _csr_io_rd_valid;
  wire [4:0]  _csr_io_rd_bits_addr;
  wire [31:0] _csr_io_rd_bits_data;
  wire [31:0] _csr_io_bru_out_mepc;
  wire [31:0] _csr_io_bru_out_mtvec;
  wire        _csr_io_bru_out_interrupt;
  wire [31:0] _csr_io_bru_out_interrupt_cause;
  wire        _csr_io_halted;
  wire        _csr_io_wfi;
  wire        _csr_io_dm_debug_mode;
  wire        _csr_io_dm_entering_debug_mode;
  wire        _csr_io_dm_single_step;
  wire        _csr_io_dm_dcsr_step;
  wire        _csr_io_dm_debug_pc_valid;
  wire [31:0] _csr_io_dm_debug_pc_bits;
  wire        _fetch_io_ibus_valid;
  wire [31:0] _fetch_io_ibus_addr;
  wire        _fetch_io_inst_lanes_0_valid;
  wire [31:0] _fetch_io_inst_lanes_0_bits_addr;
  wire [31:0] _fetch_io_inst_lanes_0_bits_inst;
  wire        _fetch_io_inst_lanes_0_bits_brchFwd;
  wire [31:0] _fetch_io_pc;
  wire        _fetch_io_fault_valid;
  wire [31:0] _fetch_io_fault_bits;
  wire [31:0] _regfile_io_target_0_data;
  wire [31:0] _regfile_io_busPort_addr_0;
  wire [31:0] _regfile_io_busPort_data_0;
  wire        _regfile_io_readData_0_valid;
  wire [31:0] _regfile_io_readData_0_data;
  wire        _regfile_io_readData_1_valid;
  wire [31:0] _regfile_io_readData_1_data;
  wire [31:0] _regfile_io_scoreboard_regd;
  wire [31:0] _regfile_io_scoreboard_comb;
  reg         csr_io_rs1_REG;
  reg         stepTriggeredReg;
  wire        regfile_io_writeData_0_valid =
    _csr_io_rd_valid | _alu_0_io_rd_valid | _bru_0_io_rd_valid | io_rvvcore_rd_0_valid;
  wire [4:0]  regfile_io_writeData_0_bits_addr =
    (_csr_io_rd_valid ? _csr_io_rd_bits_addr : 5'h0)
    | (_alu_0_io_rd_valid ? _alu_0_io_rd_bits_addr : 5'h0)
    | (_bru_0_io_rd_valid ? _bru_0_io_rd_bits_addr : 5'h0)
    | (io_rvvcore_rd_0_valid ? io_rvvcore_rd_0_bits_addr : 5'h0);
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      csr_io_rs1_REG <= 1'h0;
      stepTriggeredReg <= 1'h0;
    end
    else begin
      csr_io_rs1_REG <= _dispatch_io_csr_valid;
      stepTriggeredReg <=
        ~_csr_io_dm_debug_mode & _csr_io_dm_dcsr_step & _dispatch_io_inst_0_ready
        & _fetch_io_inst_lanes_0_valid;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        csr_io_rs1_REG = _RANDOM[/*Zero width*/ 1'b0][0];
        stepTriggeredReg = _RANDOM[/*Zero width*/ 1'b0][1];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        csr_io_rs1_REG = 1'h0;
        stepTriggeredReg = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Regfile regfile (
    .clock                    (clock),
    .reset                    (reset),
    .io_readAddr_0_valid      (_dispatch_io_rs1Read_0_valid),
    .io_readAddr_0_addr       (_dispatch_io_rs1Read_0_addr),
    .io_readAddr_1_valid      (_dispatch_io_rs2Read_0_valid),
    .io_readAddr_1_addr       (_dispatch_io_rs2Read_0_addr),
    .io_readSet_0_valid       (_dispatch_io_rs1Set_0_valid),
    .io_readSet_0_value       (_dispatch_io_rs1Set_0_value),
    .io_readSet_1_valid       (_dispatch_io_rs2Set_0_valid),
    .io_readSet_1_value       (_dispatch_io_rs2Set_0_value),
    .io_writeAddr_0_valid     (_dispatch_io_rdMark_0_valid),
    .io_writeAddr_0_addr      (_dispatch_io_rdMark_0_addr),
    .io_busAddr_0_immen       (_dispatch_io_busRead_0_immen),
    .io_busAddr_0_immed       (_dispatch_io_busRead_0_immed),
    .io_target_0_data         (_regfile_io_target_0_data),
    .io_busPort_addr_0        (_regfile_io_busPort_addr_0),
    .io_busPort_data_0        (_regfile_io_busPort_data_0),
    .io_debugBusPort_idx      (io_dm_scalar_rs_idx),
    .io_debugBusPort_data     (io_dm_scalar_rs_data),
    .io_debugWriteValid       (io_dm_scalar_rd_valid),
    .io_readData_0_valid      (_regfile_io_readData_0_valid),
    .io_readData_0_data       (_regfile_io_readData_0_data),
    .io_readData_1_valid      (_regfile_io_readData_1_valid),
    .io_readData_1_data       (_regfile_io_readData_1_data),
    .io_writeData_0_valid     (regfile_io_writeData_0_valid),
    .io_writeData_0_bits_addr (regfile_io_writeData_0_bits_addr),
    .io_writeData_0_bits_data
      ((_csr_io_rd_valid ? _csr_io_rd_bits_data : 32'h0)
       | (_alu_0_io_rd_valid ? _alu_0_io_rd_bits_data : 32'h0)
       | (_bru_0_io_rd_valid ? _bru_0_io_rd_bits_data : 32'h0)
       | (io_rvvcore_rd_0_valid ? io_rvvcore_rd_0_bits_data : 32'h0)),
    .io_writeData_1_valid     (_arb_io_out_valid),
    .io_writeData_1_bits_addr (_arb_io_out_bits_addr),
    .io_writeData_1_bits_data (_arb_io_out_bits_data),
    .io_writeData_2_valid     (_lsu_io_rd_valid),
    .io_writeData_2_bits_addr (_lsu_io_rd_bits_addr),
    .io_writeData_2_bits_data (_lsu_io_rd_bits_data),
    .io_writeMask_2_valid     (_lsu_io_fault_valid),
    .io_scoreboard_regd       (_regfile_io_scoreboard_regd),
    .io_scoreboard_comb       (_regfile_io_scoreboard_comb)
  );
  UncachedFetch fetch (
    .clock                        (clock),
    .reset                        (reset),
    .io_csr_value_0               (io_csr_in_value_0),
    .io_debug_pc_valid            (_csr_io_dm_debug_pc_valid),
    .io_debug_pc_bits             (_csr_io_dm_debug_pc_bits),
    .io_ibus_valid                (_fetch_io_ibus_valid),
    .io_ibus_ready                (~_lsu_io_ibus_valid & io_ibus_ready),
    .io_ibus_addr                 (_fetch_io_ibus_addr),
    .io_ibus_rdata                (io_ibus_rdata),
    .io_ibus_fault_valid          (~_lsu_io_ibus_valid & io_ibus_fault_valid),
    .io_inst_lanes_0_ready        (_dispatch_io_inst_0_ready),
    .io_inst_lanes_0_valid        (_fetch_io_inst_lanes_0_valid),
    .io_inst_lanes_0_bits_addr    (_fetch_io_inst_lanes_0_bits_addr),
    .io_inst_lanes_0_bits_inst    (_fetch_io_inst_lanes_0_bits_inst),
    .io_inst_lanes_0_bits_brchFwd (_fetch_io_inst_lanes_0_bits_brchFwd),
    .io_branch_0_valid            (_bru_0_io_taken_valid),
    .io_branch_0_value            (_bru_0_io_taken_value),
    .io_pc                        (_fetch_io_pc),
    .io_fault_valid               (_fetch_io_fault_valid),
    .io_fault_bits                (_fetch_io_fault_bits)
  );
  Csr csr (
    .clock                      (clock),
    .reset                      (reset),
    .io_csr_in_value_12         (_fetch_io_pc),
    .io_csr_out_value_0         (io_csr_out_value_0),
    .io_csr_out_value_1         (io_csr_out_value_1),
    .io_csr_out_value_2         (io_csr_out_value_2),
    .io_csr_out_value_3         (io_csr_out_value_3),
    .io_csr_out_value_4         (io_csr_out_value_4),
    .io_csr_out_value_5         (io_csr_out_value_5),
    .io_csr_out_value_6         (io_csr_out_value_6),
    .io_csr_out_value_7         (io_csr_out_value_7),
    .io_csr_out_value_8         (io_csr_out_value_8),
    .io_req_valid               (_csrReqArbiter_io_out_valid),
    .io_req_bits_addr           (_csrReqArbiter_io_out_bits_addr),
    .io_req_bits_index          (_csrReqArbiter_io_out_bits_index),
    .io_req_bits_rs1            (_csrReqArbiter_io_out_bits_rs1),
    .io_req_bits_op             (_csrReqArbiter_io_out_bits_op),
    .io_rs1_valid               (~csr_io_rs1_REG | _regfile_io_readData_0_valid),
    .io_rs1_data
      (csr_io_rs1_REG ? _regfile_io_readData_0_data : io_dm_csr_rs1),
    .io_rd_valid                (_csr_io_rd_valid),
    .io_rd_bits_addr            (_csr_io_rd_bits_addr),
    .io_rd_bits_data            (_csr_io_rd_bits_data),
    .io_bru_in_mode_valid       (_bru_0_io_csr_in_mode_valid),
    .io_bru_in_mcause_valid     (_bru_0_io_csr_in_mcause_valid),
    .io_bru_in_mcause_bits      (_bru_0_io_csr_in_mcause_bits),
    .io_bru_in_mepc_valid       (_bru_0_io_csr_in_mepc_valid),
    .io_bru_in_mepc_bits        (_bru_0_io_csr_in_mepc_bits),
    .io_bru_in_mtval_valid      (_bru_0_io_csr_in_mtval_valid),
    .io_bru_in_mtval_bits       (_bru_0_io_csr_in_mtval_bits),
    .io_bru_in_halt             (_bru_0_io_csr_in_halt),
    .io_bru_in_fault            (_bru_0_io_csr_in_fault),
    .io_bru_in_wfi              (_bru_0_io_csr_in_wfi),
    .io_bru_out_mepc            (_csr_io_bru_out_mepc),
    .io_bru_out_mtvec           (_csr_io_bru_out_mtvec),
    .io_bru_out_interrupt       (_csr_io_bru_out_interrupt),
    .io_bru_out_interrupt_cause (_csr_io_bru_out_interrupt_cause),
    .io_rvv_vstart              (io_rvvcore_csr_vstart),
    .io_rvv_vl                  (io_rvvcore_configState_bits_vl[6:0]),
    .io_rvv_vtype
      ({io_rvvcore_configState_bits_vill,
        23'h0,
        io_rvvcore_configState_bits_ma,
        io_rvvcore_configState_bits_ta,
        io_rvvcore_configState_bits_sew,
        io_rvvcore_configState_bits_lmul_orig}),
    .io_rvv_vxrm                (io_rvvcore_csr_vxrm),
    .io_rvv_vxsat               (io_rvvcore_csr_vxsat),
    .io_rvv_vstart_write_valid  (io_rvvcore_csr_vstart_write_valid),
    .io_rvv_vstart_write_bits   (io_rvvcore_csr_vstart_write_bits),
    .io_rvv_vxrm_write_valid    (io_rvvcore_csr_vxrm_write_valid),
    .io_rvv_vxrm_write_bits     (io_rvvcore_csr_vxrm_write_bits),
    .io_rvv_vxsat_write_valid   (io_rvvcore_csr_vxsat_write_valid),
    .io_rvv_vxsat_write_bits    (io_rvvcore_csr_vxsat_write_bits),
    .io_rvv_frm                 (io_rvvcore_csr_frm),
    .io_counters_nRetired       (_retirement_buffer_io_nRetired),
    .io_halted                  (_csr_io_halted),
    .io_fault                   (io_fault),
    .io_wfi                     (_csr_io_wfi),
    .io_irq                     (io_irq),
    .io_dm_debug_req            (io_dm_debug_req | stepTriggeredReg),
    .io_dm_resume_req           (io_dm_resume_req),
    .io_dm_debug_mode           (_csr_io_dm_debug_mode),
    .io_dm_entering_debug_mode  (_csr_io_dm_entering_debug_mode),
    .io_dm_single_step          (_csr_io_dm_single_step),
    .io_dm_dcsr_step            (_csr_io_dm_dcsr_step),
    .io_dm_current_pc           (_fetch_io_inst_lanes_0_bits_addr),
    .io_dm_next_pc
      (_bru_0_io_actually_taken
         ? _bru_0_io_real_target
         : _fetch_io_inst_lanes_0_bits_addr),
    .io_dm_debug_pc_valid       (_csr_io_dm_debug_pc_valid),
    .io_dm_debug_pc_bits        (_csr_io_dm_debug_pc_bits),
    .io_timer_irq               (io_timer_irq),
    .io_software_irq            (io_software_irq)
  );
  DispatchV2 dispatch (
    .clock                             (clock),
    .reset                             (reset),
    .io_halted
      (_csr_io_halted | _csr_io_wfi | _csr_io_dm_debug_mode
       | _csr_io_dm_entering_debug_mode),
    .io_lsuActive                      (_lsu_io_active),
    .io_scoreboard_regd                (_regfile_io_scoreboard_regd),
    .io_scoreboard_comb                (_regfile_io_scoreboard_comb),
    .io_branchTaken                    (_bru_0_io_taken_valid),
    .io_csrFault_0                     (_dispatch_io_csrFault_0),
    .io_jalFault_0                     (_dispatch_io_jalFault_0),
    .io_jalrFault_0                    (_dispatch_io_jalrFault_0),
    .io_bxxFault_0                     (_dispatch_io_bxxFault_0),
    .io_undefFault_0                   (_dispatch_io_undefFault_0),
    .io_rvvFault_0                     (_dispatch_io_rvvFault_0),
    .io_bruTarget_0                    (_dispatch_io_bruTarget_0),
    .io_jalrTarget_0_data              (_regfile_io_target_0_data),
    .io_interlock                      (_bru_0_io_interlock),
    .io_inst_0_ready                   (_dispatch_io_inst_0_ready),
    .io_inst_0_valid                   (_fetch_io_inst_lanes_0_valid),
    .io_inst_0_bits_addr               (_fetch_io_inst_lanes_0_bits_addr),
    .io_inst_0_bits_inst               (_fetch_io_inst_lanes_0_bits_inst),
    .io_inst_0_bits_brchFwd            (_fetch_io_inst_lanes_0_bits_brchFwd),
    .io_rs1Read_0_valid                (_dispatch_io_rs1Read_0_valid),
    .io_rs1Read_0_addr                 (_dispatch_io_rs1Read_0_addr),
    .io_rs1Set_0_valid                 (_dispatch_io_rs1Set_0_valid),
    .io_rs1Set_0_value                 (_dispatch_io_rs1Set_0_value),
    .io_rs2Read_0_valid                (_dispatch_io_rs2Read_0_valid),
    .io_rs2Read_0_addr                 (_dispatch_io_rs2Read_0_addr),
    .io_rs2Set_0_valid                 (_dispatch_io_rs2Set_0_valid),
    .io_rs2Set_0_value                 (_dispatch_io_rs2Set_0_value),
    .io_rdMark_0_valid                 (_dispatch_io_rdMark_0_valid),
    .io_rdMark_0_addr                  (_dispatch_io_rdMark_0_addr),
    .io_busRead_0_immen                (_dispatch_io_busRead_0_immen),
    .io_busRead_0_immed                (_dispatch_io_busRead_0_immed),
    .io_rvvRdMark_0_valid              (_dispatch_io_rvvRdMark_0_valid),
    .io_rvvRdMark_0_addr               (_dispatch_io_rvvRdMark_0_addr),
    .io_alu_0_valid                    (_dispatch_io_alu_0_valid),
    .io_alu_0_bits_addr                (_dispatch_io_alu_0_bits_addr),
    .io_alu_0_bits_op                  (_dispatch_io_alu_0_bits_op),
    .io_bru_0_valid                    (_dispatch_io_bru_0_valid),
    .io_bru_0_bits_fwd                 (_dispatch_io_bru_0_bits_fwd),
    .io_bru_0_bits_op                  (_dispatch_io_bru_0_bits_op),
    .io_bru_0_bits_pc                  (_dispatch_io_bru_0_bits_pc),
    .io_bru_0_bits_target              (_dispatch_io_bru_0_bits_target),
    .io_bru_0_bits_link                (_dispatch_io_bru_0_bits_link),
    .io_csr_valid                      (_dispatch_io_csr_valid),
    .io_csr_bits_addr                  (_dispatch_io_csr_bits_addr),
    .io_csr_bits_index                 (_dispatch_io_csr_bits_index),
    .io_csr_bits_rs1                   (_dispatch_io_csr_bits_rs1),
    .io_csr_bits_op                    (_dispatch_io_csr_bits_op),
    .io_lsu_0_ready                    (_lsu_io_req_0_ready),
    .io_lsu_0_valid                    (_dispatch_io_lsu_0_valid),
    .io_lsu_0_bits_store               (_dispatch_io_lsu_0_bits_store),
    .io_lsu_0_bits_addr                (_dispatch_io_lsu_0_bits_addr),
    .io_lsu_0_bits_op                  (_dispatch_io_lsu_0_bits_op),
    .io_lsu_0_bits_pc                  (_dispatch_io_lsu_0_bits_pc),
    .io_lsu_0_bits_elemWidth           (_dispatch_io_lsu_0_bits_elemWidth),
    .io_lsu_0_bits_nfields             (_dispatch_io_lsu_0_bits_nfields),
    .io_lsu_0_bits_bit24To20           (_dispatch_io_lsu_0_bits_bit24To20),
    .io_lsuQueueCapacity               (_lsu_io_queueCapacity),
    .io_mlu_0_valid                    (_dispatch_io_mlu_0_valid),
    .io_mlu_0_bits_addr                (_dispatch_io_mlu_0_bits_addr),
    .io_mlu_0_bits_op                  (_dispatch_io_mlu_0_bits_op),
    .io_dvu_0_ready                    (_dvu_io_req_ready),
    .io_dvu_0_valid                    (_dispatch_io_dvu_0_valid),
    .io_dvu_0_bits_addr                (_dispatch_io_dvu_0_bits_addr),
    .io_dvu_0_bits_op                  (_dispatch_io_dvu_0_bits_op),
    .io_rvv_0_ready                    (io_rvvcore_inst_0_ready),
    .io_rvv_0_valid                    (io_rvvcore_inst_0_valid),
    .io_rvv_0_bits_pc                  (io_rvvcore_inst_0_bits_pc),
    .io_rvv_0_bits_opcode              (io_rvvcore_inst_0_bits_opcode),
    .io_rvv_0_bits_bits                (io_rvvcore_inst_0_bits_bits),
    .io_rvvState_valid                 (io_rvvcore_configState_valid),
    .io_rvvState_bits_vstart           (io_rvvcore_configState_bits_vstart),
    .io_rvvIdle                        (io_rvvcore_rvv_idle),
    .io_rvvQueueCapacity               (io_rvvcore_queue_capacity),
    .io_retirement_buffer_nSpace       (_retirement_buffer_io_nSpace),
    .io_retirement_buffer_empty        (_retirement_buffer_io_empty),
    .io_retirement_buffer_trap_pending (_retirement_buffer_io_trapPending),
    .io_single_step                    (_csr_io_dm_single_step | _csr_io_dm_dcsr_step),
    .io_branch_0                       (_dispatch_io_branch_0),
    .io_jump_0                         (_dispatch_io_jump_0)
  );
  LsuV3 lsu (
    .clock                                (clock),
    .reset                                (reset),
    .io_req_0_ready                       (_lsu_io_req_0_ready),
    .io_req_0_valid                       (_dispatch_io_lsu_0_valid),
    .io_req_0_bits_store                  (_dispatch_io_lsu_0_bits_store),
    .io_req_0_bits_addr                   (_dispatch_io_lsu_0_bits_addr),
    .io_req_0_bits_op                     (_dispatch_io_lsu_0_bits_op),
    .io_req_0_bits_pc                     (_dispatch_io_lsu_0_bits_pc),
    .io_req_0_bits_elemWidth              (_dispatch_io_lsu_0_bits_elemWidth),
    .io_req_0_bits_nfields                (_dispatch_io_lsu_0_bits_nfields),
    .io_req_0_bits_bit24To20              (_dispatch_io_lsu_0_bits_bit24To20),
    .io_busPort_addr_0                    (_regfile_io_busPort_addr_0),
    .io_busPort_data_0                    (_regfile_io_busPort_data_0),
    .io_rd_valid                          (_lsu_io_rd_valid),
    .io_rd_bits_addr                      (_lsu_io_rd_bits_addr),
    .io_rd_bits_data                      (_lsu_io_rd_bits_data),
    .io_ibus_valid                        (_lsu_io_ibus_valid),
    .io_ibus_ready                        (_lsu_io_ibus_valid & io_ibus_ready),
    .io_ibus_addr                         (_lsu_io_ibus_addr),
    .io_ibus_rdata                        (io_ibus_rdata),
    .io_dbus_valid                        (io_dbus_valid),
    .io_dbus_write                        (io_dbus_write),
    .io_dbus_addr                         (io_dbus_addr),
    .io_dbus_wdata                        (io_dbus_wdata),
    .io_dbus_wmask                        (io_dbus_wmask),
    .io_dbus_rdata                        (io_dbus_rdata),
    .io_fault_valid                       (_lsu_io_fault_valid),
    .io_fault_bits_write                  (_lsu_io_fault_bits_write),
    .io_fault_bits_addr                   (_lsu_io_fault_bits_addr),
    .io_fault_bits_epc                    (_lsu_io_fault_bits_epc),
    .io_ebus_dbus_valid                   (io_ebus_dbus_valid),
    .io_ebus_dbus_ready                   (io_ebus_dbus_ready),
    .io_ebus_dbus_write                   (io_ebus_dbus_write),
    .io_ebus_dbus_pc                      (io_ebus_dbus_pc),
    .io_ebus_dbus_addr                    (io_ebus_dbus_addr),
    .io_ebus_dbus_size                    (io_ebus_dbus_size),
    .io_ebus_dbus_wdata                   (io_ebus_dbus_wdata),
    .io_ebus_dbus_wmask                   (io_ebus_dbus_wmask),
    .io_ebus_dbus_rdata                   (io_ebus_dbus_rdata),
    .io_ebus_fault_valid                  (io_ebus_fault_valid),
    .io_ebus_fault_bits_write             (io_ebus_fault_bits_write),
    .io_ebus_fault_bits_addr              (io_ebus_fault_bits_addr),
    .io_ebus_fault_bits_epc               (io_ebus_fault_bits_epc),
    .io_rvv2lsu_0_ready                   (io_rvvcore_rvv2lsu_0_ready),
    .io_rvv2lsu_0_valid                   (io_rvvcore_rvv2lsu_0_valid),
    .io_rvv2lsu_0_bits_idx_valid          (io_rvvcore_rvv2lsu_0_bits_idx_valid),
    .io_rvv2lsu_0_bits_idx_bits_data      (io_rvvcore_rvv2lsu_0_bits_idx_bits_data),
    .io_rvv2lsu_0_bits_vregfile_valid     (io_rvvcore_rvv2lsu_0_bits_vregfile_valid),
    .io_rvv2lsu_0_bits_vregfile_bits_data (io_rvvcore_rvv2lsu_0_bits_vregfile_bits_data),
    .io_rvv2lsu_0_bits_mask_valid         (io_rvvcore_rvv2lsu_0_bits_mask_valid),
    .io_rvv2lsu_0_bits_mask_bits          (io_rvvcore_rvv2lsu_0_bits_mask_bits),
    .io_lsu2rvv_0_ready                   (io_rvvcore_lsu2rvv_0_ready),
    .io_lsu2rvv_0_valid                   (io_rvvcore_lsu2rvv_0_valid),
    .io_lsu2rvv_0_bits_addr               (io_rvvcore_lsu2rvv_0_bits_addr),
    .io_lsu2rvv_0_bits_data               (io_rvvcore_lsu2rvv_0_bits_data),
    .io_lsu2rvv_0_bits_last               (io_rvvcore_lsu2rvv_0_bits_last),
    .io_rvvState_bits_sew                 (io_rvvcore_configState_bits_sew),
    .io_rvvState_bits_lmul                (io_rvvcore_configState_bits_lmul),
    .io_rvvState_bits_lmul_orig           (io_rvvcore_configState_bits_lmul_orig),
    .io_queueCapacity                     (_lsu_io_queueCapacity),
    .io_active                            (_lsu_io_active),
    .io_storeComplete_valid               (_lsu_io_storeComplete_valid),
    .io_storeComplete_bits                (_lsu_io_storeComplete_bits)
  );
  FaultManager fault_manager (
    .io_in_fault_0_csr             (_dispatch_io_csrFault_0),
    .io_in_fault_0_jal             (_dispatch_io_jalFault_0),
    .io_in_fault_0_jalr            (_dispatch_io_jalrFault_0),
    .io_in_fault_0_bxx             (_dispatch_io_bxxFault_0),
    .io_in_fault_0_undef           (_dispatch_io_undefFault_0),
    .io_in_fault_0_rvv             (_dispatch_io_rvvFault_0),
    .io_in_pc_0_pc                 (_fetch_io_inst_lanes_0_bits_addr),
    .io_in_memory_fault_valid      (_lsu_io_fault_valid),
    .io_in_memory_fault_bits_write (_lsu_io_fault_bits_write),
    .io_in_memory_fault_bits_addr  (_lsu_io_fault_bits_addr),
    .io_in_memory_fault_bits_epc   (_lsu_io_fault_bits_epc),
    .io_in_rvv_fault_valid         (io_rvvcore_trap_valid),
    .io_in_rvv_fault_bits_mepc     (io_rvvcore_trap_bits_pc),
    .io_in_rvv_fault_bits_mtval
      ({io_rvvcore_trap_bits_bits,
        io_rvvcore_trap_bits_opcode == 2'h2
          ? 7'h57
          : {1'h0,
             io_rvvcore_trap_bits_opcode == 2'h1
               ? 6'h27
               : {3'h0, {3{io_rvvcore_trap_bits_opcode == 2'h0}}}}}),
    .io_in_undef_0_inst            (_fetch_io_inst_lanes_0_bits_inst),
    .io_in_jal_0_target            (_dispatch_io_bruTarget_0),
    .io_in_jalr_0_target           (_regfile_io_target_0_data),
    .io_in_fetchFault_valid
      (_fetch_io_fault_valid & ~_bru_0_io_taken_valid
       & _regfile_io_scoreboard_regd == 32'h0 & io_rvvcore_rvv_idle & ~_lsu_io_active
       & ~_fetch_io_inst_lanes_0_valid),
    .io_in_fetchFault_bits         (_fetch_io_fault_bits),
    .io_out_valid                  (_fault_manager_io_out_valid),
    .io_out_bits_mepc              (_fault_manager_io_out_bits_mepc),
    .io_out_bits_mtval             (_fault_manager_io_out_bits_mtval),
    .io_out_bits_mcause            (_fault_manager_io_out_bits_mcause),
    .io_out_bits_decode            (_fault_manager_io_out_bits_decode)
  );
  RetirementBuffer retirement_buffer (
    .clock                                    (clock),
    .reset                                    (reset),
    .io_inst_0_ready                          (_dispatch_io_inst_0_ready),
    .io_inst_0_valid                          (_fetch_io_inst_lanes_0_valid),
    .io_inst_0_bits_addr                      (_fetch_io_inst_lanes_0_bits_addr),
    .io_inst_0_bits_inst                      (_fetch_io_inst_lanes_0_bits_inst),
    .io_targets_0                             (_dispatch_io_bruTarget_0),
    .io_jalrTargets_0                         (_regfile_io_target_0_data),
    .io_jump_0                                (_dispatch_io_jump_0),
    .io_branch_0                              (_dispatch_io_branch_0),
    .io_storeComplete_valid                   (_lsu_io_storeComplete_valid),
    .io_storeComplete_bits                    (_lsu_io_storeComplete_bits),
    .io_writeAddrScalar_0_valid               (_dispatch_io_rdMark_0_valid),
    .io_writeAddrScalar_0_addr                (_dispatch_io_rdMark_0_addr),
    .io_writeDataScalar_0_valid               (regfile_io_writeData_0_valid),
    .io_writeDataScalar_0_bits_addr           (regfile_io_writeData_0_bits_addr),
    .io_writeDataScalar_1_valid               (_arb_io_out_valid),
    .io_writeDataScalar_1_bits_addr           (_arb_io_out_bits_addr),
    .io_writeDataScalar_2_valid               (_lsu_io_rd_valid),
    .io_writeDataScalar_2_bits_addr           (_lsu_io_rd_bits_addr),
    .io_writeAddrVector_0_valid               (_dispatch_io_rvvRdMark_0_valid),
    .io_writeAddrVector_0_addr                (_dispatch_io_rvvRdMark_0_addr),
    .io_writeDataVector_0_valid               (io_rvvcore_rd_rob2rt_o_0_valid),
    .io_writeDataVector_0_bits_addr           (io_rvvcore_rd_rob2rt_o_0_w_index),
    .io_writeDataVector_0_bits_uop_pc         (io_rvvcore_rd_rob2rt_o_0_uop_pc),
    .io_writeDataVector_0_bits_last_uop_valid (io_rvvcore_rd_rob2rt_o_0_last_uop_valid),
    .io_fault_valid                           (_fault_manager_io_out_valid),
    .io_fault_bits_mepc                       (_fault_manager_io_out_bits_mepc),
    .io_fault_bits_mcause                     (_fault_manager_io_out_bits_mcause),
    .io_fault_bits_decode                     (_fault_manager_io_out_bits_decode),
    .io_nSpace                                (_retirement_buffer_io_nSpace),
    .io_nRetired                              (_retirement_buffer_io_nRetired),
    .io_empty                                 (_retirement_buffer_io_empty),
    .io_trapPending                           (_retirement_buffer_io_trapPending)
  );
  Alu alu_0 (
    .clock            (clock),
    .reset            (reset),
    .io_req_valid     (_dispatch_io_alu_0_valid),
    .io_req_bits_addr (_dispatch_io_alu_0_bits_addr),
    .io_req_bits_op   (_dispatch_io_alu_0_bits_op),
    .io_rs1_valid     (_regfile_io_readData_0_valid),
    .io_rs1_data      (_regfile_io_readData_0_data),
    .io_rs2_valid     (_regfile_io_readData_1_valid),
    .io_rs2_data      (_regfile_io_readData_1_data),
    .io_rd_valid      (_alu_0_io_rd_valid),
    .io_rd_bits_addr  (_alu_0_io_rd_bits_addr),
    .io_rd_bits_data  (_alu_0_io_rd_bits_data)
  );
  Bru bru_0 (
    .clock                        (clock),
    .reset                        (reset),
    .io_req_valid                 (_dispatch_io_bru_0_valid),
    .io_req_bits_fwd              (_dispatch_io_bru_0_bits_fwd),
    .io_req_bits_op               (_dispatch_io_bru_0_bits_op),
    .io_req_bits_pc               (_dispatch_io_bru_0_bits_pc),
    .io_req_bits_target           (_dispatch_io_bru_0_bits_target),
    .io_req_bits_link             (_dispatch_io_bru_0_bits_link),
    .io_csr_in_mode_valid         (_bru_0_io_csr_in_mode_valid),
    .io_csr_in_mcause_valid       (_bru_0_io_csr_in_mcause_valid),
    .io_csr_in_mcause_bits        (_bru_0_io_csr_in_mcause_bits),
    .io_csr_in_mepc_valid         (_bru_0_io_csr_in_mepc_valid),
    .io_csr_in_mepc_bits          (_bru_0_io_csr_in_mepc_bits),
    .io_csr_in_mtval_valid        (_bru_0_io_csr_in_mtval_valid),
    .io_csr_in_mtval_bits         (_bru_0_io_csr_in_mtval_bits),
    .io_csr_in_halt               (_bru_0_io_csr_in_halt),
    .io_csr_in_fault              (_bru_0_io_csr_in_fault),
    .io_csr_in_wfi                (_bru_0_io_csr_in_wfi),
    .io_csr_out_mepc              (_csr_io_bru_out_mepc),
    .io_csr_out_mtvec             (_csr_io_bru_out_mtvec),
    .io_csr_out_interrupt         (_csr_io_bru_out_interrupt),
    .io_csr_out_interrupt_cause   (_csr_io_bru_out_interrupt_cause),
    .io_rs1_valid                 (_regfile_io_readData_0_valid),
    .io_rs1_data                  (_regfile_io_readData_0_data),
    .io_rs2_valid                 (_regfile_io_readData_1_valid),
    .io_rs2_data                  (_regfile_io_readData_1_data),
    .io_rd_valid                  (_bru_0_io_rd_valid),
    .io_rd_bits_addr              (_bru_0_io_rd_bits_addr),
    .io_rd_bits_data              (_bru_0_io_rd_bits_data),
    .io_taken_valid               (_bru_0_io_taken_valid),
    .io_taken_value               (_bru_0_io_taken_value),
    .io_actually_taken            (_bru_0_io_actually_taken),
    .io_real_target               (_bru_0_io_real_target),
    .io_target_data               (_regfile_io_target_0_data),
    .io_interlock                 (_bru_0_io_interlock),
    .io_fault_manager_valid       (_fault_manager_io_out_valid),
    .io_fault_manager_bits_mepc   (_fault_manager_io_out_bits_mepc),
    .io_fault_manager_bits_mtval  (_fault_manager_io_out_bits_mtval),
    .io_fault_manager_bits_mcause (_fault_manager_io_out_bits_mcause)
  );
  Mlu mlu (
    .clock              (clock),
    .reset              (reset),
    .io_req_0_valid     (_dispatch_io_mlu_0_valid),
    .io_req_0_bits_addr (_dispatch_io_mlu_0_bits_addr),
    .io_req_0_bits_op   (_dispatch_io_mlu_0_bits_op),
    .io_rs1_0_valid     (_regfile_io_readData_0_valid),
    .io_rs1_0_data      (_regfile_io_readData_0_data),
    .io_rs2_0_valid     (_regfile_io_readData_1_valid),
    .io_rs2_0_data      (_regfile_io_readData_1_data),
    .io_rd_valid        (_mlu_io_rd_valid),
    .io_rd_bits_addr    (_mlu_io_rd_bits_addr),
    .io_rd_bits_data    (_mlu_io_rd_bits_data)
  );
  Dvu dvu (
    .clock            (clock),
    .reset            (reset),
    .io_req_ready     (_dvu_io_req_ready),
    .io_req_valid     (_dispatch_io_dvu_0_valid),
    .io_req_bits_addr (_dispatch_io_dvu_0_bits_addr),
    .io_req_bits_op   (_dispatch_io_dvu_0_bits_op),
    .io_rs1_data      (_regfile_io_readData_0_data),
    .io_rs2_data      (_regfile_io_readData_1_data),
    .io_rd_ready      (_arb_io_in_1_ready),
    .io_rd_valid      (_dvu_io_rd_valid),
    .io_rd_bits_addr  (_dvu_io_rd_bits_addr),
    .io_rd_bits_data  (_dvu_io_rd_bits_data)
  );
  Arbiter2_CsrCmd csrReqArbiter (
    .io_in_0_valid      (_dispatch_io_csr_valid),
    .io_in_0_bits_addr  (_dispatch_io_csr_bits_addr),
    .io_in_0_bits_index (_dispatch_io_csr_bits_index),
    .io_in_0_bits_rs1   (_dispatch_io_csr_bits_rs1),
    .io_in_0_bits_op    (_dispatch_io_csr_bits_op),
    .io_in_1_valid      (io_dm_csr_valid),
    .io_in_1_bits_addr  (io_dm_csr_bits_addr),
    .io_in_1_bits_index (io_dm_csr_bits_index),
    .io_in_1_bits_rs1   (io_dm_csr_bits_rs1),
    .io_in_1_bits_op    (io_dm_csr_bits_op),
    .io_out_valid       (_csrReqArbiter_io_out_valid),
    .io_out_bits_addr   (_csrReqArbiter_io_out_bits_addr),
    .io_out_bits_index  (_csrReqArbiter_io_out_bits_index),
    .io_out_bits_rs1    (_csrReqArbiter_io_out_bits_rs1),
    .io_out_bits_op     (_csrReqArbiter_io_out_bits_op)
  );
  Arbiter4_RegfileWriteDataIO arb (
    .io_in_0_valid     (_mlu_io_rd_valid),
    .io_in_0_bits_addr (_mlu_io_rd_bits_addr),
    .io_in_0_bits_data (_mlu_io_rd_bits_data),
    .io_in_1_ready     (_arb_io_in_1_ready),
    .io_in_1_valid     (_dvu_io_rd_valid),
    .io_in_1_bits_addr (_dvu_io_rd_bits_addr),
    .io_in_1_bits_data (_dvu_io_rd_bits_data),
    .io_in_2_ready     (io_rvvcore_async_rd_ready),
    .io_in_2_valid     (io_rvvcore_async_rd_valid),
    .io_in_2_bits_addr (io_rvvcore_async_rd_bits_addr),
    .io_in_2_bits_data (io_rvvcore_async_rd_bits_data),
    .io_in_3_ready     (io_dm_scalar_rd_ready),
    .io_in_3_valid     (io_dm_scalar_rd_valid),
    .io_in_3_bits_addr (io_dm_scalar_rd_bits_addr),
    .io_in_3_bits_data (io_dm_scalar_rd_bits_data),
    .io_out_valid      (_arb_io_out_valid),
    .io_out_bits_addr  (_arb_io_out_bits_addr),
    .io_out_bits_data  (_arb_io_out_bits_data)
  );
  assign io_halted = _csr_io_halted;
  assign io_wfi = _csr_io_wfi;
  assign io_dm_csr_rd_valid = _csr_io_rd_valid;
  assign io_dm_csr_rd_bits = _csr_io_rd_bits_data;
  assign io_dm_debug_mode = _csr_io_dm_debug_mode;
  assign io_ibus_valid = _lsu_io_ibus_valid ? _lsu_io_ibus_valid : _fetch_io_ibus_valid;
  assign io_ibus_addr = _lsu_io_ibus_valid ? _lsu_io_ibus_addr : _fetch_io_ibus_addr;
  assign io_rvvcore_rs_0_valid = _regfile_io_readData_0_valid;
  assign io_rvvcore_rs_0_data = _regfile_io_readData_0_data;
  assign io_rvvcore_rs_1_valid = _regfile_io_readData_1_valid;
  assign io_rvvcore_rs_1_data = _regfile_io_readData_1_data;
endmodule

